Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2019-05, with the labels that each got.

#7333 Add Y2DEBUG=1 ZYPP_MEDIA_CURL_DEBUG=1 to yast2 modules invocation
  lib/kdump_utils.pm
  lib/registration.pm
  lib/repo_tools.pm
  lib/y2lan_restart_common.pm
  lib/y2logsstep.pm
  lib/y2snapper_common.pm
  lib/y2x11test.pm
  tests/autoyast/clone.pm
  tests/autoyast/verify_btrfs_clone.pm
  tests/autoyast/verify_disk_as_pv_clone.pm
  tests/console/yast2_apparmor.pm
  tests/console/yast2_bootloader.pm
  tests/console/yast2_clone_system.pm
  tests/console/yast2_dns_server.pm
  tests/console/yast2_ftp.pm
  tests/console/yast2_http.pm
  tests/console/yast2_i.pm
  tests/console/yast2_lan.pm
  tests/console/yast2_lan_hostname.pm
  tests/console/yast2_nfs_client.pm
  tests/console/yast2_nfs_server.pm
  tests/console/yast2_nis.pm
  tests/console/yast2_ntpclient.pm
  tests/console/yast2_proxy.pm
  tests/console/yast2_registration.pm
  tests/console/yast2_rmt.pm
  tests/console/yast2_samba.pm
  tests/console/yast2_snapper_ncurses.pm
  tests/console/yast2_tftp.pm
  tests/console/yast2_vnc.pm
  tests/console/yast2_xinetd.pm
  tests/iscsi/iscsi_client.pm
  tests/iscsi/iscsi_server.pm
  tests/x11/nis_client.pm
  tests/x11/nis_server.pm
  tests/x11/yast2_snapper.pm
Labels: Ready

#7418 validate_packages_and_patterns.pm: Use zypper with --non-interactive
  tests/console/validate_packages_and_patterns.pm
Labels: bug

#7419 Install lttng-tools explicitly for slert12sp4
  tests/rt/kmp_modules.pm
Labels: Ready

#6402 Apply new parameters usage of assert_and_click
  lib/power_action_utils.pm
  lib/registration.pm
  tests/caasp/oci_overview.pm
  tests/installation/select_patterns_and_packages.pm
  tests/x11/dolphin.pm
  tests/x11/firefox/firefox_downloading.pm
  tests/x11/firefox/firefox_rss.pm
  tests/x11/gnomecase/nautilus_permission.pm
  tests/x11/libreoffice/libreoffice_mainmenu_components.pm
  tests/x11/libreoffice/libreoffice_recent_documents.pm
  tests/x11/oocalc.pm
  tests/x11/ooffice.pm
  tests/x11/seahorse.pm
Labels: notready

#7213 Add fadump for spvm backends
  lib/kdump_utils.pm
  products/sle/main.pm
  tests/console/kdump_and_crash.pm
Labels: enhancement

#7500 Type RT reg code in scc wizard
  lib/registration.pm
Labels: Ready

#7509 Increase timeout for results for nested openQA job
  tests/openqa/webui/test_results.pm
Labels: WIP
