Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2019-11, with the labels that each got.

#8823 Use xz for y2logs compression except 12-sp1
  lib/opensusebasetest.pm
  lib/qam.pm
Labels: Ready

#8682 Verify mount types
  tests/jeos/firstrun.pm
Labels: Ready

#8895 Increase timout for SLE registration
  lib/registration.pm
Labels: Ready

#8799 Use regexp against STDOUT instead of screen check
  lib/systemd_testsuite_test.pm
  tests/systemd_testsuite/binary_tests.pm
Labels: enhancement

#8948 Wicked: add AUTOYAST variable to test suite yaml
  schedule/create_hdd_autoyast_wicked.yaml
Labels: WIP
