Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2019-12, with the labels that each got.

#9017 Use human readable dmesg timestamp
  lib/power_action_utils.pm
  tests/shutdown/cleanup_before_shutdown.pm
Labels: Ready

#8981 Add new test suite sdk+desktop
  schedule/jeos/sle/hyperv/jeos-base+sdk+desktop.yaml
  schedule/jeos/sle/hyperv/jeos-extratest.yaml
  schedule/jeos/sle/kvm/jeos-base+sdk+desktop.yaml
  schedule/jeos/sle/kvm/jeos-extratest.yaml
  schedule/jeos/sle/xen/hvm/jeos-base+sdk+desktop.yaml
  schedule/jeos/sle/xen/hvm/jeos-extratest.yaml
  schedule/jeos/sle/xen/pv/jeos-base+sdk+desktop.yaml
  schedule/jeos/sle/xen/pv/jeos-extratest.yaml
  tests/toolchain/gcc_compilation.pm
  tests/toolchain/gcc_fortran_compilation.pm
  tests/toolchain/install.pm
Labels: Ready

#9020 Fix qam-gnome yaml for s390x
  schedule/qam/15-SP1/qam-gnome.yaml
  schedule/qam/15/qam-gnome.yaml
Labels: Ready

#9112 Add and increase wait time in wireshark test
  tests/x11/wireshark.pm
Labels: Ready

#9088 Fix older HANA versions installation
  lib/sles4sap.pm
  tests/sles4sap/hana_install.pm
  tests/sles4sap/wizard_hana_install.pm
Labels: WIP

#9133 Get rid of xorg needle in console test
  tests/console/x_vt.pm
Labels: Ready

#9154 Kick off LTP on JeOS
  schedule/jeos/sle/hyperv/jeos-ltp.yaml
  schedule/jeos/sle/kvm/jeos-ltp.yaml
  schedule/jeos/sle/xen/hvm/jeos-ltp.yaml
  schedule/jeos/sle/xen/pv/jeos-ltp.yaml
  tests/kernel/boot_ltp.pm
  tests/kernel/install_ltp.pm
Labels: Ready

#9111 Register addons properly in YaST addon module
  lib/registration.pm
  tests/installation/addon_products_via_SCC_yast2.pm
  tests/installation/addon_products_yast2.pm
Labels: Ready

#9205 Select always system role for Full media
  lib/version_utils.pm
Labels: Ready, bug
