Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2020-02, with the labels that each got.

#9481 Use sleep 2, same as in every other sssd test script
  data/sssd-tests/krb/test.sh
Labels: Ready

#9483 Use wait_still_screen to make yast2_i more robust
  tests/console/yast2_i.pm
Labels: Ready

#9520 Wait before assert_and_click, to avoid movement of click area
  tests/yast2_gui/yast2_storage_ng.pm
Labels: Ready

#9511 Adapt WSL test suite for YaST2 firstboot and registration
  tests/wsl/firstrun.pm
  tests/wsl/prepare_wsl_feature.pm
Labels: Ready, enhancement

#9590 Change SBD_DELAY_START from 'no' to 'yes'
  data/ha/sbd.template
Labels: WIP

#9634 Fix and make yast2_instserver test more robust
  tests/yast2_gui/yast2_instserver.pm
Labels: Ready

#9641 Increase timeout for libqca* install
  tests/console/libqca2.pm
Labels: Ready

#9651 Remove the workaround for bug 1129504
  tests/installation/disable_grub_timeout.pm
Labels: Ready
