Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2020-11, with the labels that each got.

#11328 Check if gnome packagekit is already installed
  tests/update/updates_packagekit_gpk.pm
Labels: hacktoberfest-accepted

#11267 Add workaround for workqueue lockup
  lib/susedistribution.pm
Labels: hacktoberfest-accepted

#11357 Wicked basic wlan
  tests/wicked/before_test.pm
  tests/wicked/wlan/sut/t00_prepare.pm
  tests/wicked/wlan/sut/t03_wpa_psk.pm
Labels: WIP

#11286 workaround: Uninstall btrfsmaintenance bsc#1174436
  tests/autoyast/autoyast_reboot.pm
Labels: Ready

#11396 Update version of existing kernel iso
  tests/x11/firefox/firefox_downloading.pm
Labels: Ready

#11398 Fix evolution auth pop-up when it's not focused
  lib/x11test.pm
  tests/x11/evolution/evolution_smoke.pm
Labels: Ready

#11393 Use virtio console on maintenance incident installation test
  tests/qam-updinstall/update_install.pm
Labels: Ready

#11457 Schedule disk_activation on s390x backend
  schedule/functional/allpatterns.yaml
Labels: notready
