Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2020-06, with the labels that each got.

#10414 wicked: Install custom wicked rpm
  tests/wicked/before_test.pm
Labels: WIP

#10401 Add check for pvm lpar's shutdown and activation state
  lib/bootloader_pvm.pm
Labels: notready

#10419 Separate container runtimes test cases
  lib/main_common.pm
  products/opensuse/main.pm
  schedule/jeos/sle/hyperv/jeos-extratest.yaml
  schedule/jeos/sle/jeos-container-engines_and_tools.yaml
  schedule/jeos/sle/kvm/jeos-extratest.yaml
  schedule/jeos/sle/xen/hvm/jeos-extratest.yaml
  schedule/jeos/sle/xen/pv/jeos-extratest.yaml
  tests/console/docker_compose.pm
  tests/console/podman.pm
Labels: Ready

#10479 userspace_nfs_v4: Increase timeout for tar archive
  tests/qa_automation/qa_run.pm
Labels: Ready

#10502 Make help menu check in firefox test more robust
  tests/x11/firefox.pm
Labels: Ready

#10506 Containers: move SLE base image specific test to a new section
  schedule/containers/extra_tests_textmode_containers.yaml
  schedule/containers/sle_image_on_sle_host.yaml
Labels: Ready

#10508 Clean up after packman testing
  tests/console/sqlite3.pm
  tests/console/zypper_extend.pm
Labels: Ready

#10519 Start installer on Live CD with icon click
  tests/installation/live_installation.pm
Labels: Ready

#10536 yaml: Merge scc tests into one
  schedule/qam/common/qam-scc.yaml
  tests/console/suseconnect.pm
Labels: Ready
