Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2021-11, with the labels that each got.

#13574 php7_postgresql: Update postgresql version handling
  lib/apachetest.pm
  tests/console/postgresql_server.pm
Labels: Ready

#13609 php7_postgresql: Use old version handling for 12 SP3 and older
  lib/apachetest.pm
Labels: Ready

#13623 php7_postgresql: Use old version handling if postgresql96 is installed
  lib/apachetest.pm
Labels: Ready

#13624 Set mouse_hide in init_desktop_runner to 1
  lib/susedistribution.pm
Labels: Ready

#13654 emaillink: Remove soft fail on fixed mutt email
  tests/x11/firefox/firefox_emaillink.pm
Labels: Ready

#13645 Cleanup lib/main_common.pm into lib/main_containers.pm
  lib/main_common.pm
  lib/main_containers.pm
Labels: notready

#13660 Enable firewall on SLE 15+ all archs
  data/autoyast_qam/15_installation.xml.ep
Labels: Ready

#13695 Add usbguard test case into openQA
  schedule/security/usbguard.yaml
  tests/security/usbguard/usbguard.pm
Labels: WIP

#13732 Avoid failures due to un-refreshed screen & bsc#1192992 workaround
  lib/opensusebasetest.pm
  lib/susedistribution.pm
  lib/x11utils.pm
Labels: Ready

#13745 libnettle8: Check support for ED448 signature
  schedule/jeos/sle/fips.yaml
  tests/fips/gnutls/gnutls_base_check.pm
Labels: Ready

#13680 Public Cloud CLI: Small fixes
  lib/main_publiccloud.pm
  schedule/publiccloud/publiccloud_cli.yml
  tests/publiccloud/aws_cli.pm
  tests/publiccloud/azure_cli.pm
  tests/publiccloud/google_cli.pm
Labels: Ready
