Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2021-03, with the labels that each got.

#12069 Fix a small error in Public Cloud library
  lib/publiccloud/instance.pm
Labels: WIP

#12118 apache: Check apache subprocesses instead of pid file
  tests/console/apache.pm
Labels: Ready

#12075 Openldap to 389ds migration tools test case
  data/openldap_to_389ds/aci.ldif
  data/openldap_to_389ds/db.ldif
  data/openldap_to_389ds/instance.inf
  data/openldap_to_389ds/slapd.conf
  data/openldap_to_389ds/sssd.conf
  schedule/migration/openldap_to_389ds.yaml
  tests/migration/openldap_to_389ds.pm
Labels: Ready

#12038 MicroOS: Add basic tests for Toolbox
  products/microos/main.pm
  schedule/sle-micro/containers.yaml
  tests/microos/toolbox.pm
Labels: Ready

#12115 SLE Micro: SSH installation test for DVD flavor
  schedule/sle-micro/remote_ssh_controller.yaml
  schedule/sle-micro/remote_ssh_target.yaml
  tests/installation/welcome.pm
Labels: Ready

#12153 Slim consoletests on Public Cloud down
  schedule/publiccloud/mau-extratests-publiccloud.yml
Labels: notready

#12126 ncurses: Try to draw a bold red line and upload more info on failure
  tests/console/ncurses.pm
Labels: WIP

#12141 Check rotation of journal logs
  tests/console/journalctl.pm
Labels: Ready

#12152 Fix TableSample change in libreoffice macro
  lib/x11test.pm
  tests/x11/libreoffice/libreoffice_default_theme.pm
  tests/x11/libreoffice/libreoffice_double_click_file.pm
  tests/x11/libreoffice/libreoffice_open_specified_file.pm
  tests/x11/libreoffice/libreoffice_pyuno_bridge_no_evolution_dep.pm
Labels: Ready

#12189 clamav: First update db from local mirror
  tests/console/clamav.pm
Labels: Ready

#12190 rmt_feature: Fix failure due to incomplete credentials
  lib/repo_tools.pm
Labels: Ready

#12191 libreoffice: Use old and new table macro behavior based on version
  tests/x11/libreoffice/libreoffice_pyuno_bridge_no_evolution_dep.pm
Labels: Ready
