Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2022-02, with the labels that each got.

#14138 Zypper migration: make target regex more flexible
  tests/migration/online_migration/zypper_migration.pm
Labels: Ready

#13808 Fix packagekit plasma test skipping by the installing updates phase
  tests/update/updates_packagekit_kde.pm
Labels: Ready

#14119 Use name & device from nmcli * show output
  tests/network/setup_multimachine.pm
Labels: Ready

#14159 Add workaround for pip3 conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready

#14151 Add wait_for_purge_kernels to avoid RPM lock
  lib/registration.pm
  lib/utils.pm
Labels: Ready

#14162 Substitute SAP repo to LTSS
  tests/qam-updinstall/update_install.pm
Labels: Ready

#14194 ncurses: run 'dialog' using enter_cmd instead of script_run
  tests/console/ncurses.pm
Labels: Ready

#14187 Use dummy IPs instead of NTP pools
  lib/services/ntpd.pm
  tests/console/ntp.pm
Labels: Ready

#14214 Fix mr_test failure on ipmi
  lib/sles4sap.pm
  tests/boot/boot_from_pxe.pm
  tests/sles4sap/saptune/mr_test.pm
Labels: Ready

#14248 Update chrony NTP test case
  tests/console/ntp_client.pm
Labels: Ready

#14283 [Proposal] Refactor add_suseconnect_product with retries
  lib/registration.pm
Labels: notready

#14273 Create container runtime smoke test
  lib/containers/containerd_crictl.pm
  lib/containers/containerd_nerdctl.pm
  lib/containers/utils.pm
  lib/services/docker.pm
  tests/containers/containerd_crictl.pm
  tests/containers/containerd_nerdctl.pm
  tests/containers/docker.pm
  tests/containers/podman.pm
Labels: WIP

#14296 Add workaround for bsc#1196114
  tests/migration/online_migration/zypper_migration.pm
Labels: Ready
