Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2022-10, with the labels that each got.

#15656 Ensure localhost entry in SUT /etc/hosts file before svn test
  tests/security/libserf/libserf.pm
Labels: hacktoberfest-accepted

#15680 return value for qesap_execute
  lib/qesapdeployment.pm
Labels: WIP

#15671 Adjust timeout in kdump_and_crash for aarch64
  lib/kdump_utils.pm
Labels: Ready

#15524 Adapt test suite configuration with YAML feature default+flows for non-product selection in s390x
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
  schedule/yast/textmode_installation_minimal_role/textmode_installation_minimal_role@s390x.yaml
Labels: qe-yast

#15701 Adjust bootloader_start on s390x to new YaST start message
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-yast

#15700 Add sync after dd in snapper_cleanup_timeline
  tests/console/snapper_cleanup_timeline.pm
Labels: qe-yast, qe-yam

#15539 Enable libyui-rest-api in test suites for SLE-15-SP4
  schedule/yast/maintenance/create_hdd_transactional_server_dev.yaml
  schedule/yast/maintenance/lvm_thin_provisioning_dev.yaml
  schedule/yast/maintenance/ncurses_interactive_installation_dev.yaml
  schedule/yast/maintenance/qam-yast_self_update_dev.yaml
  schedule/yast/maintenance/yast-mru-install-minimal-with-addons.yaml
  schedule/yast/maintenance/yast-mru-install_dev.yaml
Labels: qe-yam

#15723 Install curl if not present when running script_output
  tests/console/orphaned_packages_check.pm
  tests/console/zypper_lifecycle.pm
Labels: qe-yam

#15422 Provisioning slem
  data/microos/butane/config.fcc
  data/microos/butane/script
  schedule/sle-micro/raw_image.yaml
  tests/microos/disk_boot.pm
  tests/microos/verify_setup.pm
Labels: Ready

#15673 Add offline autoyast installation ha test on SLES 12SP4
  data/autoyast_sle15/create_hdd/create_hdd_ha_sles_12sp4.xml.ep
  schedule/yast/maintenance/ha_autoyast_create_hdd_maintenance_s390x.yaml
Labels: qe-yam

#15675 Replace select_patterns when unselecting all patterns
  lib/y2_installbase.pm
  schedule/yast/minimal+base/minimal+base@yast.yaml
  tests/installation/select_only_visible_patterns_from_top.pm
Labels: qe-yam

#15716 Remove validation from svirt-hyperv failing jobs
  schedule/yast/lvm_raid1/lvm+raid1_sle15_svirt-hyperv.yaml
  schedule/yast/minimal+base/minimal+base@yast-svirt-hyperv.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@svirt-hyperv.yaml
Labels: qe-yam

#15751 Add ha autoyast installation profile for sle15
  data/autoyast_sle15/create_hdd/create_hdd_ha_aarch64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_ppc64le.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_s390x.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_x86_64.xml.ep
  schedule/yast/autoyast/autoyast_ha.yaml
  schedule/yast/autoyast/autoyast_ha_spvm.yaml
Labels: qe-yam

#15756 Apply keyboard based workaround for bsc1189550
  lib/y2_installbase.pm
Labels: qe-yam

#15760 Exclude rebootmgr in transactional_server_helper_apps
  schedule/yast/transactional_server/transactional_server_helper_apps_exclude_rebootmgr.yaml
Labels: qe-yam

#15750 Modify Autoyast profile for HA
  data/autoyast_sle12/create_hdd/create_hdd_ha_sles.xml.ep
  schedule/yast/maintenance/autoyast_create_hdd_maintenance.yaml
  schedule/yast/maintenance/autoyast_create_hdd_maintenance_deregister.yaml
Labels: qe-yam

#15795 Install yast2-migration package when creating hdd for HA on ppc64le
  data/autoyast_sle15/create_hdd/create_hdd_ha_ppc64le.xml.ep
Labels: qe-yam

#15777 Update yamllint to produce github annotations
  .github/workflows/ci.yml
Labels: enhancement

#15753 Record soft-failure in test suite installer_extended for product modules not available in early phase
  tests/installation/module_registration/verify_module_registration.pm
Labels: qe-yam
