Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2022-05, with the labels that each got.

#14761 Use serial console on support_server
  lib/mm_network.pm
  schedule/ha/bv/ha_supportserver.yaml
  schedule/sles4sap/ha_supportserver.yaml
  tests/support_server/setup.pm
Labels: Ready

#14746 Modify lib/mm_network.pm and use for tests/network/firewalld_policy_objects.pm use
  lib/mailtest.pm
  lib/mm_network.pm
  lib/mm_tests.pm
  tests/console/ipsec_tools_h2h.pm
  tests/network/firewalld_policy_objects.pm
  tests/ses/nodes_preparation.pm
  tests/slenkins/slenkins_control_network.pm
  tests/slepos/prepare.pm
Labels: Ready

#14827 Fix multimachine networking in x11 tests
  lib/x11test.pm
Labels: Ready

#14891 Add conditional schedule for validate_beta_message
  schedule/yast/installer_extended/installer_extended.yaml
  schedule/yast/installer_extended/installer_extended@pvm.yaml
  schedule/yast/installer_extended/installer_extended@s390x.yaml
Labels: WIP

#14873 JeOS: expand image information
  lib/main_common.pm
  schedule/jeos/sle/jeos-main.yaml
  schedule/jeos/sle/rpi/jeos-main.yaml
  tests/jeos/image_info.pm
Labels: Ready

#14934 Fix suppotconfig log file name to upload
  lib/hacluster.pm
Labels: Ready

#14958 Prevent known issues on HPC break the mvapich2 tests
  tests/hpc/mpi_master.pm
Labels: WIP

#14700 Add initial podman pods test
  data/containers/hello-kubic.yaml
  lib/main_containers.pm
  tests/containers/podman_pods.pm
Labels: blocked
