Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2022-06, with the labels that each got.

#15071 Run slurm configuration merely against compute nodes
  lib/hpcbase.pm
Labels: Verification-Runs-needed

#15089 Introduce PUBLIC_CLOUD_STORAGE_ACCOUNT variable
  data/publiccloud/terraform/azure.tf
  lib/publiccloud/azure.pm
  lib/publiccloud/gcp_client.pm
  lib/publiccloud/provider.pm
  variables.md
Labels: WIP

#15113 Fix yast2_storage_ng in sp4
  tests/yast2_gui/yast2_storage_ng.pm
Labels: qe-yast

#15135 Fix textmode product shortcuts on 15-SP4
  tests/installation/welcome.pm
Labels: Ready

#14849 Migration of XFS and USB_install tests to enhanced scheduler
  schedule/yast/sle/flows/unregistered.yaml
  schedule/yast/sle/guided_xfs/guided_xfs.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_s390x_zvm.yaml
  schedule/yast/sle/usb_install.yaml
  schedule/yast/usb_install.yaml
  schedule/yast/xfs/xfs.yaml
  schedule/yast/xfs/xfs@s390x_svirt.yaml
  schedule/yast/xfs/xfs@s390x_zVM.yaml
  schedule/yast/xfs/xfs@svirt-xen-hvm.yaml
  schedule/yast/xfs/xfs@svirt-xen-pv.yaml
  schedule/yast/xfs/xfs_spvm.yaml
Labels: qe-yast
