Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2022-11, with the labels that each got.

#15496 Create equivalent yast2_firewall test module based on libyui-rest-api
  lib/Distribution/Opensuse/Tumbleweed.pm
  lib/YaST/Firewall/ChangeZonePage.pm
  lib/YaST/Firewall/FirewallController.pm
  lib/YaST/Firewall/InterfacesPage.pm
  lib/YaST/Firewall/MainPage.pm
  lib/YaST/Firewall/PortsPage.pm
  lib/YaST/Firewall/ServicesPage.pm
  lib/YaST/Firewall/StartUpPage.pm
  lib/YaST/Firewall/ZonePage.pm
  lib/YaST/Firewall/ZonesPage.pm
  schedule/yast/opensuse/yast2_gui/yast2_gui.yaml
  schedule/yast/yast2_gui/yast2_gui_sle.yaml
  test_data/yast/yast2_gui.yaml
  tests/yast2_gui/yast2_firewall_set_default_zone.pm
  tests/yast2_gui/yast2_firewall_set_default_zone_prepare.pm
  tests/yast2_gui/yast2_firewall_set_interface.pm
  tests/yast2_gui/yast2_firewall_set_service_port.pm
  tests/yast2_gui/yast2_firewall_start_service.pm
  tests/yast2_gui/yast2_firewall_stop_service.pm
Labels: qe-yam

#15836 Fix select_serial_terminal for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15496
  tests/yast2_gui/yast2_firewall_set_default_zone.pm
  tests/yast2_gui/yast2_firewall_set_interface.pm
  tests/yast2_gui/yast2_firewall_set_service_port.pm
  tests/yast2_gui/yast2_firewall_start_service.pm
  tests/yast2_gui/yast2_firewall_stop_service.pm
Labels: qe-yam

#15828 disable GRUB_TIMEOUT in grub_test_snapshot.pm
  tests/boot/grub_test_snapshot.pm
Labels: qe-yam

#15807 Expect display manager to appear earlier on boot
  lib/bootloader_setup.pm
  lib/opensusebasetest.pm
Labels: qe-yam

#15873 Increase timeout for booting to local disk
  lib/bootloader_setup.pm
Labels: qe-yam

#15843 Adapt test suites for power VM
  lib/grub_utils.pm
  schedule/yast/releasenotes_origin+unregistered@pvm.yaml
  tests/installation/release_notes_from_url.pm
Labels: qe-yam

#15761 Split register_extensions_and_modules to handle separately additional registration
  schedule/yast/maintenance/lvm_thin_provisioning_dev.yaml
  schedule/yast/maintenance/ncurses_interactive_installation_dev.yaml
  schedule/yast/maintenance/qam-yast_self_update_dev.yaml
  schedule/yast/maintenance/yast-mru-install_dev.yaml
  schedule/yast/maintenance/yast_mru_install_minimal_with_addons_aarch64_dev.yaml
  schedule/yast/maintenance/yast_mru_install_minimal_with_addons_s390x_dev.yaml
  schedule/yast/maintenance/yast_mru_install_minimal_with_addons_x86_dev.yaml
  schedule/yast/qam-yast_self_update.yaml
  schedule/yast/qam-yast_self_update_libyui.yaml
  schedule/yast/sle/flows/default_sle15sp4.yaml
  tests/installation/module_registration/add_additional_regcodes.pm
  tests/installation/module_registration/import_untrusted_gnpupg_key.pm
  tests/installation/module_registration/register_extensions_and_modules.pm
  tests/installation/select_only_visible_patterns_from_top.pm
Labels: qe-yam

#15581 Enable libyui-rest-api in test suites for SLE15SP3 MU dev group
  schedule/yast/maintenance/create_hdd_transactional_server_sle15sp3_dev.yaml
  schedule/yast/maintenance/lvm_thin_provisioning_sle15sp3_dev.yaml
  schedule/yast/maintenance/ncurses_interactive_installation_sle15sp3_dev.yaml
  schedule/yast/maintenance/qam-yast_self_update_sle15sp3_dev.yaml
  schedule/yast/maintenance/yast-mru-install-minimal-with-addons_sle15sp3_aarch64_dev.yaml
  schedule/yast/maintenance/yast-mru-install-minimal-with-addons_sle15sp3_s390x_dev.yaml
  schedule/yast/maintenance/yast-mru-install-minimal-with-addons_sle15sp3_x86_dev.yaml
  schedule/yast/maintenance/yast-mru-install_sle15sp3_dev.yaml
  schedule/yast/sle/flows/default_sle15sp3.yaml
Labels: qe-yam

#15852 Adapt modify_existing_partition for PowerVM
  schedule/yast/modify_existing_partition/modify_existing_partition@spvm.yaml
  test_data/yast/modify_existing_partition/modify_existing_partition@spvm.yaml
Labels: qe-yam

#15839 Select last item on select_patterns
  lib/y2_installbase.pm
Labels: qe-yam

#15905 Move ansible on sle from extra_tests_textmode to extra_tests_phub
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_phub.yaml
Labels: Ready

#15920 Install opens-iscsi package in iscsi_client
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#15919 Update SLES textmode keyboard shortcut for 15-SP4 Full
  tests/installation/welcome.pm
Labels: Ready

#15928 update_install: Auto accept license in zypper dup
  tests/qam-updinstall/update_install.pm
Labels: Ready

#15933 Expect ip instead of FQDN in ibft validation
  tests/installation/validation/ibft.pm
Labels: qe-yam

#15944 Set patterns to default for HPC installations of system role
  schedule/hpc/installation_node_dev.yaml
  schedule/hpc/installation_server.yaml
Labels: Ready

#15940 Collect AVC generated by each test module
  lib/consoletest.pm
  tests/console/journal_check.pm
  tests/microos/cockpit_service.pm
  tests/microos/disk_boot.pm
  tests/microos/enable_lp_module.pm
  tests/microos/image_checks.pm
  tests/microos/libzypp_config.pm
  tests/microos/networking.pm
  tests/microos/one_line_checks.pm
  tests/microos/rcshell_start.pm
  tests/microos/rebuild_initrd.pm
  tests/microos/selfinstall.pm
  tests/microos/services_enabled.pm
  tests/microos/toolbox.pm
  tests/microos/verify_setup.pm
  tests/transactional/enable_selinux.pm
  tests/transactional/filesystem_ro.pm
  tests/transactional/health_check.pm
  tests/transactional/host_config.pm
  tests/transactional/install_updates.pm
  tests/transactional/tdup.pm
  tests/transactional/trup_install_tar.pm
  tests/transactional/trup_smoke.pm
  tests/transactional/verify_undelete_snapshots.pm
Labels: Ready

#15886 Create default yaml for s390x zVM and adapt test suites to use it in YaST group
  schedule/yast/minimal+base/minimal+base@s390x_zvm.yaml
  schedule/yast/minimal+base/minimal+base@yast-s390x-disk-activation.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x-zVM.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x_zvm.yaml
  schedule/yast/sle/flows/default_s390x_zvm.yaml
  schedule/yast/sle/guided_btrfs/guided_btrfs_s390x_zvm.yaml
  schedule/yast/sle/guided_ext4/guided_ext4_s390x_zvm.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_s390x_zvm.yaml
  schedule/yast/ssh-x/ssh-x@s390x_zvm.yaml
  schedule/yast/textmode/textmode@s390x_zvm.yaml
Labels: qe-yam

#15840 Add a test suite to create a hdd for sap migration
  data/autoyast_sle12/create_hdd/create_hdd_sap_sles.xml.ep
Labels: qe-yam

#15994 Ensure s390x kvm instance is accessible via ssh
  data/containers/autoyast_containers.xml.ep
Labels: qe-yam

#15774 PC LTP runtime python version default
  tests/publiccloud/run_ltp.pm
  variables.md
Labels: WIP

#15889 Apply workaround to force screen refresh on YaST QT window
  lib/YaST/NetworkSettings/NetworkCardSetup/BondSlavesTab.pm
  lib/YaST/NetworkSettings/NetworkCardSetup/BridgedDevicesTab.pm
  lib/YaST/NetworkSettings/NetworkCardSetup/DeviceTypeDialog.pm
  lib/YaST/NetworkSettings/OverviewTab.pm
  lib/YaST/workarounds.pm
  lib/registration.pm
  lib/y2snapper_common.pm
  tests/iscsi/iscsi_client.pm
  tests/iscsi/iscsi_server.pm
  tests/x11/nis_server.pm
  tests/yast2_gui/yast2_bootloader.pm
  tests/yast2_gui/yast2_control_center.pm
  tests/yast2_gui/yast2_hostnames.pm
  tests/yast2_gui/yast2_instserver.pm
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam
