Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-01, with the labels that each got.

#16164 Extend time to wait yast2-keyboard-ui screen
  tests/yast2_gui/yast2_keyboard.pm
Labels: qe-yam

#16180 iscsi_client: Wait for yast window to finish
  tests/iscsi/iscsi_client.pm
Labels: Ready

#16098 Apply firewall restart after each command that change configuration only in SLE
  tests/yast2_gui/yast2_firewall_set_default_zone.pm
  tests/yast2_gui/yast2_firewall_set_default_zone_prepare.pm
  tests/yast2_gui/yast2_firewall_set_interface.pm
  tests/yast2_gui/yast2_firewall_set_service_port.pm
Labels: qe-yam

#16192 Revisit wrong settings for HA migrations
  data/autoyast_sle15/create_hdd/create_hdd_ha_aarch64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_ppc64le.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_s390x.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_ha_x86_64.xml.ep
Labels: qe-yam

#16235 Revert "Add softfail for 'gnome_music' test due to known issue"
  tests/x11/gnome_music.pm
Labels: qe-core

#16221 Do SAP/LTSS module substitution on SLE 15+
  tests/qam-updinstall/update_install.pm
Labels: Ready

#16154 Create 15SP4 qcow for SLEHPC via autoyast
  data/autoyast_sle15/create_hdd/create_hdd_hpc_development_node_aarch64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_hpc_development_node_x86_64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_hpc_management_server_aarch64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_hpc_management_server_x86_64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_hpc_textmode_aarch64.xml.ep
  data/autoyast_sle15/create_hdd/create_hdd_hpc_textmode_x86_64.xml.ep
  schedule/yast/autoyast/autoyast_create_hdd.yaml
Labels: qe-yam

#16173 Add an autoyast profile for a ppc64le pcm case
  data/autoyast_sle15/autoyast_pcm_lgm_allpatterns_ppc64le.xml.ep
  schedule/migration/autoyast_milestone_test_online_pre@pvm.yaml
Labels: qe-yam

#16094 Create a daily auto-installation for SLE 12 SP5 aarch64
  data/autoyast_sle12/create_hdd/create_hdd_sles_regression_aarch64.xml.ep
  schedule/yast/autoyast/autoyast_create_hdd_sdk_gnome.yaml
Labels: qe-yam

#16240 Start sshd service for test 'sshterm'
  tests/x11/sshxterm.pm
Labels: qe-core

#16243 Need install yast2-iscsi-client for iscsi-client x11 test
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#16224 Remove workaround for 'start_systemd_testkit_offline'
  tests/console/start_systemd_testkit_offline.pm
Labels: qe-core

#16241 Bump wait_serial timeout in yast2_clone_system
  tests/console/yast2_clone_system.pm
Labels: qe-yam

#16258 Prevent install_SLES from being called part 2
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x_zvm.yaml
Labels: qe-yam

#16268 Install open-iscsi before running yast2-iscsi-client
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#16267 wicked: Increase timeout for test-ext-firwall.sh on aarch64
  lib/wickedbase.pm
  tests/wicked/startandstop/sut/t18_firewall_extension.pm
Labels: Ready

#16253 Make sure httpd2-prefork pid is shown up in apache test
  tests/console/apache.pm
Labels: qe-core

#16196 Do not add SBD playbook for native fencing
  data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
  schedule/sles4sap/publiccloud_hanasr.yml
  tests/sles4sap/publiccloud/qesap_terraform.pm
Labels: WIP

#16290 SElinux select box handling
  tests/installation/enable_selinux.pm
Labels: WIP

#16298 Provide workaround for iscsi failure bsc#1207157
  lib/YaST/workarounds.pm
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#16271 Call show_tasks_in_blocked_state in post_fail_hook
  lib/consoletest.pm
  lib/utils.pm
  lib/x11test.pm
Labels: Ready, qe-core

#16311 Cleanup gpg-agent.conf when it was created on gpg_ver >= 2.1
  tests/console/gpg.pm
Labels: Ready

#16312 Improve log collection for consolebase based tests and systemd enabled services
  lib/Utils/Systemd.pm
Labels: qe-core
