Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-11, with the labels that each got.

#18117 sssd: create config directory if not pre-existing
  lib/services/389ds_sssd_client.pm
  tests/console/sssd_389ds_functional.pm
  tests/migration/openldap_configuration.pm
Labels: Ready

#18120 Explicit servername in ca-certificates test
  tests/console/ca_certificates_mozilla.pm
Labels: qe-core

#18080 pre-install zypper-migration-plugin for support images
  data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
Labels: qe-yam

#18124 zypper_lifecycle_toolchain: Use pipe as field separator
  tests/console/zypper_lifecycle_toolchain.pm
Labels: Ready, qe-core

#18045 Introduce a new test for python-beautifulsoup4
  data/python/bs4/python3-beautifulsoup4-test.py
  data/python/bs4/testpage.html
  lib/python_version_utils.pm
  schedule/qam/common/mau-extratests1.yaml
  tests/console/python3_beautifulsoup4.pm
Labels: qe-core

#18134 Add openssh to autoyast package list on s390x
  data/autoyast_sle15/mini_s390x.xml
Labels: qe-yam

#18092 Fix system-role issue on aarch64 on TW
  tests/installation/system_role.pm
Labels: qe-yam

#18140 Add Workaround for bsc#1202478
  lib/utils.pm
Labels: WIP, qe-yam

#18113 Remove addon_products_via_SCC_yast2 and addon_products_yast2 modules which be used in the old installer
  products/sle/main.pm
  schedule/rt/sle12/rt_tunning.yaml
  schedule/rt/sle12/sles+rt-net.yaml
  schedule/rt/sle12/sles+rt.yaml
  schedule/yast/sles+sdk+proxy_SCC_via_YaST.yaml
  tests/installation/addon_products_via_SCC_yast2.pm
  tests/installation/addon_products_yast2.pm
Labels: qe-yam

#18160 Skip zypper-migration-plugin for sles15sp3
  tests/migration/online_migration/pre_migration.pm
Labels: qe-yam

#18163 Add Server-Applications module on SLED
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#18155 Remove soft failure in module verify_module_registration
  schedule/yast/installer_extended/installer_extended_x86_64.yaml
  test_data/yast/installer_extended/installer_extended_aarch64.yaml
  test_data/yast/installer_extended/installer_extended_ppc64le_s390x.yaml
  tests/installation/module_registration/verify_module_registration.pm
Labels: qe-yam

#18179 Remove zypper-migration-plugin check
  tests/migration/online_migration/pre_migration.pm
Labels: qe-yam

#18151 Remove workaround for bsc1194917
  lib/services/hpcpackage_remain.pm
Labels: qe-yam

#18152 Change to use serial_terminal for scc_deregistration
  lib/utils.pm
  tests/console/scc_deregistration.pm
Labels: qe-yam

#18173 Remove soft_fail when modifying kernel multiversion
  lib/migration.pm
  tests/console/system_prepare.pm
  tests/migration/online_migration/post_migration.pm
  tests/migration/online_migration/zypper_patch.pm
  tests/update/patch_sle.pm
Labels: qe-yam

#18198 Test for firewalld container in ALP product
  lib/mm_network.pm
  schedule/alp/firewalld_container.yaml
  tests/microos/workloads/firewalld-container/firewalld_client.pm
  tests/microos/workloads/firewalld-container/firewalld_server.pm
Labels: qe-core

#18208 Change the 't=' to 'config:type=' for sle12sp5 autoyast profile
  data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles12sp5_install_default_patterns_ppc64le.xml
  data/yam/autoyast/support_images/sles12sp5_install_default_patterns_x86_64.xml
Labels: qe-yam

#18206 New grub on 15SP6 don't need to type LUKS passphrase
  tests/installation/boot_encrypt.pm
Labels: qe-core

#18225 Add workaround to refresh some yast screen
  lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm
  tests/x11/nis_server.pm
  tests/yast2_gui/yast2_bootloader.pm
Labels: qe-yam

#18228 Fix workaround to refresh some yast screen undefined issue
  lib/YaST/NetworkSettings/NetworkCardSetup/AddressTab.pm
  lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm
Labels: qe-yam
