Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-12, with the labels that each got.

#18235 mail server: Fix thunderbird test due to latest SCC changes
  tests/network/config_services.pm
Labels: Ready, qe-core

#18238 Make coredumps more visible
  lib/Utils/Logging.pm
Labels: qe-core

#18191 Added yaml files for offline migration with public hdd image
  schedule/migration/migration_offline_scc_deregistration_aarch64.yaml
  schedule/migration/migration_offline_scc_deregistration_ppc64le.yaml
  schedule/migration/migration_offline_scc_deregistration_s390x.yaml
  schedule/migration/migration_offline_scc_deregistration_x86_64.yaml
Labels: qe-yam

#18248 Fix no permission to access serial console on ppc64le
  tests/console/prepare_test_data.pm
Labels: qe-yam

#18260 Apply workaround for the gtk glitches for iscsi_client
  lib/yast2_widget_utils.pm
Labels: qe-yam

#18251 Test bonding two network interfaces on ALP
  schedule/alp/bonding.yaml
  tests/microos/network_bonding.pm
Labels: qe-core

#18261 libssh: Use serial terminal
  tests/console/libssh.pm
Labels: Ready, qe-core

#18284 Apply workaround_poo124652 for send_key_until
  lib/YaST/workarounds.pm
  lib/yast2_widget_utils.pm
Labels: qe-yam

#18283 Read network device names from Network Manager
  tests/microos/network_bonding.pm
Labels: qe-core

#18288 Fix version in QR RAID yaml
  schedule/qam/QR/15-SP5/raid/raid5_sle_gpt_prep_boot.yaml
Labels: Ready, qe-core

#18270 New logic to type LUKS passphrase in grub phase
  lib/grub_utils.pm
  lib/opensusebasetest.pm
  lib/utils.pm
  tests/boot/grub_test_snapshot.pm
  tests/installation/boot_encrypt.pm
  tests/x11/reboot_and_install.pm
Labels: qe-core

#18316 Make s390x zKVM SUT hostname more visible
  tests/installation/bootloader_zkvm.pm
Labels: qe-core

#18292 Add ltss to SLES15SP3 textmode default patterns ay installation
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_x86_64.xml
Labels: qe-yam

#18322 Need report failure when zypper migration failed
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#18323 bind: Add auto-agree-with-licenses due to new feature
  data/qam/handle_bind_source_dependencies.sh
Labels: Ready, qe-core

#18335 smt_client: Remove unneeded -p argument from SUSEConnect
  tests/smt/smt_client.pm
Labels: Ready, qe-core

#18246 Move all python related to tests to new test suite
  schedule/functional/extra_tests_gnome.yaml
  schedule/functional/extra_tests_gnome_development.yaml
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_phub.yaml
  schedule/functional/stack_tests_python.yaml
  schedule/qam/12-SP1/mau-extratests-phub.yaml
  schedule/qam/12-SP2/mau-extratests-phub.yaml
  schedule/qam/12-SP3/mau-extratests-phub.yaml
  schedule/qam/12-SP4/mau-extratests-phub.yaml
  schedule/qam/12-SP5/mau-extratests-phub.yaml
  schedule/qam/15-SP1/mau-extratests-phub.yaml
  schedule/qam/15-SP2/mau-extratests-phub.yaml
  schedule/qam/15-SP2/qam-gnome.yaml
  schedule/qam/15-SP3/mau-extratests-phub.yaml
  schedule/qam/15-SP3/qam-gnome.yaml
  schedule/qam/15-SP4/mau-extratests-phub.yaml
  schedule/qam/15-SP4/qam-gnome.yaml
  schedule/qam/15-SP5/mau-extratests-phub.yaml
  schedule/qam/15-SP5/qam-gnome.yaml
  schedule/qam/15/mau-extratests-phub.yaml
  schedule/qam/common/mau-extratests1.yaml
Labels: qe-core

#18363 Add extra customer repos also during installation
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/12_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
  data/autoyast_qam/15_installation.xml.ep
  tests/installation/add_update_test_repo.pm
Labels: Ready, qe-core

#18336 Added LTSS addon to the sles15sp3 gnome autoyast profile
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
Labels: qe-yam

#18329 Add yast glitch workaround for y2snapper_common
  lib/y2snapper_common.pm
  tests/yast2_gui/yast2_bootloader.pm
Labels: qe-yam

#18320 Add workaround for bug#1158557 in disable_grub_timeout
  tests/installation/disable_grub_timeout.pm
Labels: qe-yam

#18348 New test: btrfs balance functionality
  schedule/staging/btrfs_maintenance-staging.yaml
  tests/console/btrfs_balance.pm
Labels: qe-core

#18370 Do not install mariadb after smt pattern
  tests/smt/smt_server_install.pm
Labels: Ready, qe-core

#18373 Add LTSS to SLES15SP4 autoyast profiles
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_minimal_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_x86_64.xml
Labels: qe-yam
