Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-10, with the labels that each got.

#17884 Add extra repos on TERADATA before grub2 update
  tests/qam-minimal/install_update.pm
Labels: Ready, qe-core

#17893 libgcrypt: Use serial terminal
  tests/console/libgcrypt.pm
Labels: Ready, qe-core

#17889 Adjust the assert_screen sequence in agama tests
  tests/yam/agama/auto.pm
Labels: qe-yam

#17699 Rework installation of k3s and kubectl
  data/containers/kubectl/deployment.yml
  data/containers/registries.yaml
  lib/containers/k8s.pm
  tests/containers/kubectl.pm
Labels: Ready

#17906 Issue qam-scc: assert_screen timeout 600
  tests/console/yast2_registration.pm
Labels: qe-yam

#17908 Increase timeout for opensuse repos
  tests/installation/installation_mode.pm
Labels: Ready, qe-core

#17899 Move tests with phub into extratest-phub
  schedule/qam/12-SP1/mau-extratests-phub.yaml
  schedule/qam/12-SP2/mau-extratests-phub.yaml
  schedule/qam/12-SP3/mau-extratests-phub.yaml
  schedule/qam/12-SP4/mau-extratests-phub.yaml
  schedule/qam/12-SP5/mau-extratests-phub.yaml
  schedule/qam/15-SP1/mau-extratests-phub.yaml
  schedule/qam/15-SP2/mau-extratests-phub.yaml
  schedule/qam/15-SP3/mau-extratests-phub.yaml
  schedule/qam/15-SP4/mau-extratests-phub.yaml
  schedule/qam/15-SP5/mau-extratests-phub.yaml
  schedule/qam/15/mau-extratests-phub.yaml
  schedule/qam/common/mau-extratests2.yaml
  tests/console/ansible.pm
  tests/console/systemd_rpm_macros.pm
Labels: Ready, qe-core

#17919 Restore workaround for bsc1202234 on 15-SP2
  data/autoyast_qam/15-common_base_installation.xml.ep
Labels: Ready, qe-core

#17924 ansible: Fix phub module in security group
  tests/console/ansible.pm
Labels: Ready, qe-core

#17927 Use different gw ip based on SUT location/hostname
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/12_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
  data/autoyast_qam/15_installation.xml.ep
  data/autoyast_sle12/autoyast_sles12sp3+alladdons_allpatterns_reg_full_s390x.xml
  data/autoyast_sle12/autoyast_sles12sp3+alladdons_default_reg_full_s390x.xml
  data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_allpatterns_reg_full_s390x.xml
  data/autoyast_sle12/autoyast_sles12sp3+sdk+ha+geo_default_reg_full_s390x.xml
  data/autoyast_sle12/autoyast_sles12sp3_allpatterns_reg_full_s390x.xml
  data/autoyast_sle12/autoyast_sles12sp3_default_reg_full_s390x.xml
  data/autoyast_sle12/ay.xml
  data/qam/dracut/12-SP2_custom_lvm.xml.ep
  data/qam/dracut/12-SP2_custom_usr.xml.ep
  data/qam/dracut/12_custom_lvm.xml.ep
  data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
  data/yam/autoyast/support_images/create_hdd_sles_regression_aarch64.xml.ep
  data/yam/autoyast/support_images/create_hdd_sles_regression_s390x.xml.ep
  data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml
Labels: Ready, qe-core

#17871 Use new NW server for sap tests
  schedule/migration/migration_offline_sap.yaml
  schedule/migration/migration_online_sap.yaml
  schedule/yast/autoyast/autoyast_sap.yaml
Labels: qe-yam

#17750 Split derigister_dropped_modules test module
  schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
  tests/migration/deregister_ltss.pm
  tests/migration/deregister_python2.pm
Labels: qe-yam

#17914 Relax max load average threshold to cope with flakyness
  tests/console/force_scheduled_tasks.pm
Labels: qe-core

#17939 libgcrypt, nginx, mutt: Add verbose for debugging
  lib/services/nginx.pm
  tests/console/libgcrypt.pm
  tests/console/mutt.pm
  tests/console/valgrind.pm
Labels: Ready, qe-core

#17949 add yast2-registration in sle15sp3_mininal_role's profile
  data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_minimal_default_patterns_x86_64.xml
Labels: qe-yam

#17964 Create support image on SLE 15 SP4 with minimal role
  data/yam/autoyast/support_images/sles15sp4_install_minimal_default_patterns_aarch64.xml
Labels: qe-yam

#17962 iotop
  tests/console/iotop.pm
Labels: Ready, qe-core

#17808 Add ay profiles for sles15sp3 default patterns installation
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_default_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_default_patterns_x86_64.xml
Labels: qe-yam

#17931 Upload agama logs using agama cli
  lib/Yam/agama/agama_base.pm
Labels: qe-yam

#17959 Crash Dump Configuration file updated, need update code to validate new values
  test_data/yast/yast2_ncurses/textmode.yaml
Labels: qe-yam

#17972 Add sles15sp4 ay profile for default module pattern install
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_default_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_x86_64.xml
Labels: qe-yam

#17956 Modify addons_with_license conditions
  lib/registration.pm
Labels: qe-yam

#17915 Add autoyast profiles for default modules all patterns in sle15sp5 migration
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
Labels: qe-yam

#17989 Create support image with default modules and all patterns on SLE15SP4
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
Labels: qe-yam

#17990 Add ltss module to workaround bug 1216116
  data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp3_install_textmode_all_patterns_x86_64.xml
Labels: qe-yam

#18005 registration: Wait after confirming update repos
  lib/registration.pm
Labels: Ready, qe-core

#17998 firefox: Drop unused code
  lib/x11test.pm
  tests/x11/firefox/firefox_html5.pm
  tests/x11/plasma_browser_integration.pm
Labels: Ready, qe-core

#18010 Add required package 'openssh' to autoyast config file
  data/yam/autoyast/bug-872532_ix64ph1069.xml
  data/yam/autoyast/bug-876411_btrfs_h5_autoinst.xml
Labels: qe-yam

#18017 zziplib: Add verbose for debugging
  tests/console/zziplib.pm
Labels: Ready, qe-core

#18022 firefox: Increase timout for started firefox
  lib/x11test.pm
Labels: Ready, qe-core

#18036 Remove check_screen for nvidia in autoyast installation
  tests/autoyast/installation.pm
Labels: qe-yam

#16176 sssd: Switch to mdb openldap backend
  data/sssd-tests/krb/slapd.conf
  data/sssd-tests/krb/slapd_old.conf
  data/sssd-tests/ldap-nested-groups/slapd.conf
  data/sssd-tests/ldap-no-auth/slapd.conf
  data/sssd-tests/ldap/slapd.conf
  data/sssd/openldap/slapd.conf
  tests/console/sssd_openldap_functional.pm
Labels: qe-core

#17703 Create test modules for reboot_before_migration and stop_grub_timeout
  schedule/migration/migration_offline_media_all_patterns_x86_64.yaml
  schedule/migration/migration_offline_media_x86_64.yaml
  schedule/migration/migration_offline_scc_all_patterns_x86_64.yaml
  schedule/migration/migration_offline_scc_x86_64.yaml
  tests/migration/reboot_to_migration.pm
Labels: qe-yam

#18043 Kick off reduction of yaml files in YaM scope
  schedule/yam/test_cases/usb_install.yaml
  schedule/yast/sle/flows/default_x86_64_flavor_full.yaml
  schedule/yast/sle/usb_install_x86_64.yaml
Labels: qe-yam

#18037 Deprecating openldap2 test in favor of `389ds` functional tests
  lib/main_common.pm
Labels: qe-core

#18048 Fix occasional xfce Live failures
  tests/x11/xfce_lightdm_logout_login.pm
Labels: Ready, qe-core

#18077 Increase timeout for s390x qcow2 convert & upload
  tests/shutdown/svirt_upload_assets.pm
Labels: Ready
