Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-03, with the labels that each got.

#16492 New module to enable FIPS on transactional servers
  lib/main_micro_alp.pm
  tests/transactional/enable_fips.pm
Labels: Ready

#16479 Fix License screen in s390x, which is now using different UI controls
  lib/Installation/License/Sle/LicenseAgreementController.pm
  tests/installation/licensing/verify_license_translations.pm
Labels: qe-yam

#16382 Add autoyast installation profiles with firewall disabled
  data/autoyast_sle15/create_hdd/create_hdd_gnome_disabled_firewall_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_s390x.xml
  schedule/yast/autoyast/autoyast_create_hdd_gnome.yaml
Labels: qe-yam

#16478 Add workaround for refreshment issue
  tests/x11/addon_products_via_SCC_yast2.pm
Labels: qe-yam

#16498 Remove soft-failure
  lib/nfs_common.pm
Labels: qe-yam

#16499 Use yaml schedule for hpc regression test
  schedule/migration/hpc_regression_test_online.yaml
Labels: qe-yam

#16473 Fix check_system_info related issues
  tests/console/check_system_info.pm
Labels: qe-yam

#16519 Fix an autoyast profile to make it install
  data/autoyast_sle15/create_hdd/create_hdd_gnome_disabled_firewall.xml
Labels: qe-yam

#16503 Unschedule logs_from_installation_system
  schedule/migration/s390x_regression_test_offline.yaml
Labels: WIP, qe-yam

#16520 Remove soft-failure bsc#1195046
  lib/migration.pm
Labels: qe-yam

#16554 Rebuild grub config to wipe fake boot entry
  tests/boot/grub2_test.pm
Labels: qe-core

#16553 Do fully_patch_system instead of just zypper up
  tests/qam-minimal/install_update.pm
Labels: qe-core

#16521 Enable FIPS testing for SLES - Core maintenance
  schedule/qam/common/mau-extratests_fips.yaml
  tests/console/systemd_rpm_macros.pm
Labels: qe-core

#16555 Workaround s390-tools bug on 15-SP4
  tests/qam-minimal/s390tools.pm
Labels: qe-core

#16462 Pass timeout/interval when using regex to find UI element
  lib/Installation/ProductSelection/ProductSelectionController.pm
  lib/YuiRestClient.pm
  tests/installation/product_selection/install_SLES.pm
Labels: qe-yam

#16549 Enable FIPS testing for SLED - Core maintenance
  schedule/qam/15-SP4/qam-regression-firefox_fips.yaml
  schedule/qam/15-SP4/qam-regression-other_fips.yaml
  tests/x11/firefox/firefox_passwd.pm
Labels: qe-core

#16562 Add autoyast profiles for media installation
  data/autoyast_sle15/autoyast_media_install_gnome.xml
  data/autoyast_sle15/autoyast_media_install_gnome_ppc64le.xml.ep
  data/autoyast_sle15/autoyast_media_install_gnome_s390x.xml.ep
  schedule/yast/autoyast/autoyast_media_gnome.yaml
Labels: qe-yam

#16573 FIPS: fix openssl tests for MicroOS
  data/journal_check/bug_refs.json
  lib/main_micro_alp.pm
  tests/fips/openssl/openssl_fips_alglist.pm
  tests/fips/openssl/openssl_fips_cipher.pm
  tests/fips/openssl/openssl_fips_dhparam.pm
  tests/fips/openssl/openssl_fips_hash.pm
Labels: Ready

#16505 Split openldap_to_389ds
  schedule/migration/openldap_to_389ds.yaml
  schedule/migration/x86_regression_test_offline.yaml
  schedule/migration/x86_regression_test_online.yaml
  tests/migration/openldap_configuration.pm
  tests/migration/openldap_to_389ds.pm
Labels: qe-yam

#16551 Fix rmt-chinese issue
  lib/x11utils.pm
  tests/x11/rmt/rmt_chinese.pm
Labels: qe-yam

#16566 Avoid adding openqa repo in leap
  tests/yast2_gui/yast2_control_center.pm
Labels: qe-yam

#16580 Create new yaml schedule copied from yast2_ncurses.yaml for leap
  schedule/yast/opensuse/yast2_ncurses/yast2_ncurses_leap.yaml
Labels: qe-yam

#16565 Fix 'ensure_unlocked_desktop repeated too much' issue
  schedule/yast/autoyast/autoyast_create_hdd_sdk_gnome.yaml
  schedule/yast/maintenance/sap_autoyast_create_hdd_gnome_netweaver_sle12.yaml
Labels: qe-yam

#16586 Soft failure 1195046
  lib/migration.pm
Labels: qe-yam

#16598 boot_to_desktop: Wait longer for grub2 and add BOOTLOADER_TIMEOUT
  tests/boot/boot_to_desktop.pm
Labels: Ready, qe-core

#16605 Apply workaround of bsc#1195046 for all arches
  lib/migration.pm
Labels: qe-yam

#16578 Gather image data in postgresql
  lib/db_utils.pm
  schedule/jeos/sle/jeos-main.yaml
  tests/jeos/image_info.pm
Labels: Ready

#16615 Apply workaround and umount before ending iscsi session
  lib/YaST/workarounds.pm
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#16635 Fix HA mapping in check_system_info
  tests/console/check_system_info.pm
Labels: qe-yam

#16626 Apply refreshment workaround for iscsi_server
  lib/yast2_widget_utils.pm
Labels: qe-yam

#16596 Add 12sp5 autoyast with default pattern image
  data/autoyast_sle12/create_hdd/create_hdd_sles_regression_aarch64.xml.ep
Labels: qe-yam

#16644 Bump timeout in yast2_kdump_use_fadump
  lib/YaST/RestartInfoPage.pm
  tests/console/yast2_kdump_use_fadump.pm
Labels: qe-yam

#16649 Make valgrind test verbose
  data/valgrind/valgrind-test.sh
  tests/console/valgrind.pm
Labels: Ready, qe-core

#16647 Create auto-installation for SLE12SP5 for autoyast migration aarch64
  data/autoyast_sle12/create_hdd/create_hdd_sles_regression_aarch64.xml.ep
  schedule/yast/autoyast/autoyast_create_hdd_sdk_gnome.yaml
Labels: qe-yam

#16662 Add timeout for apply_workaround_poo124652
  lib/y2snapper_common.pm
Labels: qe-core

#16592 Add smoke test for libica
  lib/main_micro_alp.pm
  tests/fips/libica.pm
Labels: Ready

#16676 Fix wrong mount point for swap
  data/autoyast_sle15/autoyast_home_encrypted.xml
Labels: qe-yam

#16687 Remove duplicate tests from extra_tests_textmode
  schedule/functional/extra_tests_textmode.yaml
Labels: qe-core

#16686 Handle reboot on powerVM for patch_and_reboot test
  tests/qa_automation/patch_and_reboot.pm
Labels: qe-core

#16733 Terraform workspace to use jod id
  tests/sles4sap/publiccloud/qesap_terraform.pm
Labels: WIP

#16717 Screensaver can't be always unlocked with key on 15-SP3
  lib/x11utils.pm
Labels: Ready, qe-core

#16743 Fix encrypted drive detection for ALP
  tests/microos/image_checks.pm
Labels: Ready

#16707 Ensure to select bond port yast2_lan_restart_bond
  lib/YaST/NetworkSettings/NetworkCardSetup/BondSlavesTab.pm
Labels: qe-yam

#16742 Use serial_terminal for 'orphaned_packages_check'
  tests/console/orphaned_packages_check.pm
Labels: qe-core

#16722 Create auto-installation for textmode with sle-module-desktop-applications and sle-module-development-tools use libyui-rest-api
  data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64.xml
  schedule/functional/autoyast_create_hdd/autoyast_create_hdd_textmode_libyui.yaml
Labels: qe-yam

#16652 Replace script_ouput by script_ouput_retry in iscsi_configuration
  tests/installation/iscsi_configuration.pm
Labels: qe-yam

#16639 Reboot machine before kexec on UEFI kernel update
  schedule/qam/15-SP2/qam-minimal.yaml
  schedule/qam/15-SP3/qam-minimal.yaml
  schedule/qam/15-SP4/qam-minimal.yaml
  schedule/qam/15/qam-minimal.yaml
  schedule/qam/common/qam-minimal-full-ppc64le.yaml
  schedule/qam/common/qam-minimal-full.yaml
  schedule/qam/common/qam-minimal.yaml
  tests/qam-minimal/check_logs.pm
  tests/qam-minimal/install_patterns.pm
  tests/qam-minimal/install_update.pm
  tests/qam-minimal/s390tools.pm
  tests/qam-minimal/update_minimal.pm
Labels: Ready, qe-core
