Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-02, with the labels that each got.

#16278 Restore sort order in select_device
  lib/YaST/NetworkSettings/OverviewTab.pm
Labels: qe-yam

#16213 Hide passing check messages from the CI logs
  Makefile
  tools/check_metadata
Labels: qe-core

#16316 Revert "Start sshd service for test 'sshterm'"
  tests/x11/sshxterm.pm
Labels: qe-core

#16329 Select gnome role for validate_default_target
  schedule/yast/sle/guided_btrfs/guided_btrfs.yaml
  schedule/yast/sle/guided_ext4/guided_ext4_s390x_kvm.yaml
Labels: qe-yam

#16277 Add known error for yast2_detect_logs
  lib/opensusebasetest.pm
Labels: qe-yam

#16349 Add Distribution provider for ALP
  lib/Distribution/Alp.pm
  lib/DistributionProvider.pm
  products/alp/main.pm
Labels: qe-yam

#16368 Fix product shortcuts for SLE 15 SP5
  tests/installation/welcome.pm
Labels: qe-yam

#16361 Reset the VMs in textmode for xen VMs for test 'user_defined_snapshot'
  tests/x11/user_defined_snapshot.pm
Labels: qe-core

#16366 Update shortcuts for SLES 15-SP5
  tests/installation/disable_grub_timeout.pm
  tests/installation/welcome.pm
Labels: qe-core

#16378 Use correct REGcode for sles4sap migration
  tests/sles4sap/migrate_sles_to_sles4sap.pm
Labels: WIP

#16407 License agreement only showed once for migrations SLE 15 SP5 for s390x
  lib/registration.pm
Labels: qe-yam

#16393 Fix disk selection in iscsi_ibft
  schedule/yast/iscsi_ibft.yaml
Labels: qe-yam

#16413 welcome: Use tab to highlight product instead of kb shortcut
  tests/installation/welcome.pm
Labels: Ready

#16397 Fix chrony default config path
  schedule/yast/autoyast/autoyast_tftp.yaml
  tests/console/verify_config_files.pm
  tests/console/verify_systemd_timesync.pm
  tests/console/yast2_ntpclient.pm
Labels: qe-yam

#16418 Wait before send next key for remove-repository
  lib/registration.pm
Labels: qe-yam

#16381 Add python311 test coverage
  schedule/functional/extra_tests_textmode.yaml
  tests/console/python310_version_check.pm
  tests/console/python3_new_version_check.pm
Labels: qe-core

#16408 Increase timeout for yast2_software_management
  tests/yast2_gui/yast2_software_management.pm
Labels: qe-yam

#16328 Add an autoyast installation schedule file
  schedule/migration/autoyast_offline_pre@pvm.yaml
Labels: qe-yam

#16427 Increase tianocore-secureboot timeout on aarch64
  lib/bootloader_setup.pm
Labels: Ready

#16428 Ensure to press next in nis_server
  tests/x11/nis_server.pm
Labels: qe-yam

#16429 Removed packages in AutoYaST profile
  data/autoyast_sle15/bug-872532_ix64ph1069.xml
  data/autoyast_sle15/bug-876411_btrfs_h5_autoinst.xml
Labels: qe-yam

#16419 Provide a correct schedule for guided_ext4
  schedule/yast/sle/guided_ext4/guided_ext4_s390x_kvm.yaml
  schedule/yast/sle/guided_ext4/guided_ext4_svirt_xen.yaml
Labels: qe-yam

#16436 Adjust disk size in msdos@ppc64le test suite
  test_data/yast/msdos/msdos_hmc.yaml
  test_data/yast/msdos/msdos_ppc64le.yaml
Labels: qe-yam

#16442 Add python3 new version check on QEM tests
  schedule/qam/common/mau-extratests1.yaml
  tests/console/python3_new_version_check.pm
Labels: qe-core

#16310 Improve D-installer POC test suite.
  schedule/yast/opensuse/d_installer.yaml
  tests/installation/d_installer/d_installer_cli_installation.pm
  tests/installation/d_installer/d_installer_cli_setup.pm
  tests/installation/d_installer/d_installer_reboot.pm
  tests/installation/d_installer/d_installer_start_cli.pm
Labels: qe-yam

#16405 Drop sound for all but SLE
  tests/yast2_gui/yast2_control_center.pm
Labels: qe-yam

#16376 Bring back install_SLES on aarch64
  schedule/yast/btrfs/btrfs+warnings.yaml
  schedule/yast/transactional_server/create_hdd_transactional_server.yaml
Labels: qe-yam

#16448 Replace WORKER_HOSTNAME with IP for ay iscsi test
  data/autoyast_sle15/autoyast_iscsi_ibft.xml
  lib/autoyast.pm
  schedule/yast/autoyast/autoyast_iscsi_ibft.yaml
Labels: qe-yam

#16225 Pass timeout/interval when using regex to find UI element
  lib/Installation/ProductSelection/ProductSelectionPage.pm
  lib/YuiRestClient/Filter.pm
  lib/YuiRestClient/Widget/Base.pm
Labels: qe-yam

#16415 Re-write mau-qa_userspace_nfs(v4) test cases
  data/qam/nfs.tar.bz2
  schedule/qam/12-SP3/mau-filesystem.yaml
  schedule/qam/12-SP4/mau-filesystem.yaml
  schedule/qam/12-SP5/mau-filesystem.yaml
  schedule/qam/15-SP1/mau-filesystem.yaml
  schedule/qam/15-SP2/mau-filesystem.yaml
  schedule/qam/15-SP3/mau-filesystem.yaml
  schedule/qam/15-SP4/mau-filesystem.yaml
  tests/network/nfs.pm
Labels: qe-core

#16457 Replace softfail of bsc1204176 with poo reference
  lib/YaST/NetworkSettings/NetworkCardSetup/BondSlavesTab.pm
  lib/YaST/NetworkSettings/NetworkCardSetup/BridgedDevicesTab.pm
  lib/YaST/NetworkSettings/NetworkCardSetup/DeviceTypeDialog.pm
  lib/YaST/NetworkSettings/OverviewTab.pm
  lib/YaST/workarounds.pm
  lib/registration.pm
  lib/y2snapper_common.pm
  tests/iscsi/iscsi_client.pm
  tests/iscsi/iscsi_server.pm
  tests/x11/nis_server.pm
  tests/yast2_gui/yast2_bootloader.pm
  tests/yast2_gui/yast2_control_center.pm
  tests/yast2_gui/yast2_hostnames.pm
  tests/yast2_gui/yast2_instserver.pm
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam

#16242 Create & apply defaults for uefi backend
  schedule/yast/gpt.yaml
  schedule/yast/nvme.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@uefi.yaml
Labels: qe-yam

#16468 Rename sap-b1 pattern to sap-bone in 15-SP5
  tests/sles4sap/patterns.pm
Labels: WIP

#16410 Add textmode installation to staging
  schedule/staging/textmode_install@64bit-staging.yaml
Labels: qe-yam

#16348 Updated iscsi path to /var/lib/iscsi
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#16445 Drop DES, MD5 and add also other protocols
  tests/network/snmp.pm
Labels: Ready, qe-core

#16356 Hide CI passed logs for yaml files checking
  Makefile
  tools/check_yaml
Labels: qe-core
