Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-06, with the labels that each got.

#17186 Enlarge the timeout window when adding unreleasing update repos.
  tests/installation/add_update_test_repo.pm
Labels: qe-yam

#17196 Fix SLE11-SP4 Incidents
  lib/qam.pm
  schedule/qam/common/qam-glibc-sle11.yaml
  tests/kernel/update_kernel.pm
Labels: qe-core

#17206 Add arch_only key for extra repos
  lib/qam.pm
Labels: qe-core

#17039 Implement YaST Control Center Page
  lib/Distribution/Alp.pm
  lib/Yam/ControlCenterPage.pm
  lib/Yam/PageBase.pm
  lib/Yam/ReleaseNotesPage.pm
  products/alp/main.pm
  schedule/alp/alp_yast.yaml
  schedule/yam/control_center_container.yaml
  tests/yam/yast_modules/control_center.pm
Labels: qe-yam

#17205 Test the latest ovn3 and openvswitch3 packages if possible
  tests/console/openvswitch.pm
  tests/console/openvswitch_ssl.pm
  tests/console/ovn.pm
  variables.md
Labels: qe-core

#17190 Automate auto-installation of openSUSE Leap 16.0 on Agama
  data/yam/agama/auto/leap16.json
  data/yam/agama/auto/leap16.sh
Labels: qe-yam

#17063 Create ay test for s390x on o3
  data/zvm.xml
  lib/autoyast.pm
  schedule/yast/autoyast/autoyast_zvm_sles_product_reg.yaml
  tests/installation/bootloader_s390.pm
Labels: qe-yam

#17175 Automate auto-installation which adds user with password
  data/yam/agama/auto/default_alp_bedrock.sh
  data/yam/agama/auto/default_alp_micro.jsonnet
  data/yam/agama/auto/default_tumbleweed.json
  data/yam/agama/auto/default_tumbleweed.sh
  lib/yam/agama/agama_base.pm
  schedule/yam/agama_auto.yaml
  tests/yam/validate/validate_product.pm
  tests/yam/validate/validate_user.pm
Labels: qe-yam

#17208 Fix extra repo arch_only condition
  lib/qam.pm
Labels: Ready, qe-core

#17223 Fix boot timeout and NTP sync issues for year_2038_detection
  lib/main_micro_alp.pm
  schedule/qam/common/mau-extratests2.yaml
  tests/console/year_2038_detection.pm
Labels: qe-core

#17116 Deal with no bounce back on powerKVM
  lib/opensusebasetest.pm
Labels: qe-yam

#17222 Use writeback to fast qemu-img convert
  tests/shutdown/svirt_upload_assets.pm
Labels: qe-yam

#17178 Introduce Kiwi tests to build image locally
  data/kiwi/appliance.kiwi
  data/kiwi/config.sh
  schedule/qam/15-SP4/kiwi_build_local_img.yaml
  schedule/qam/15-SP4/kiwi_validate_local_img.yaml
  tests/kiwi_images_test/kiwi_build_image.pm
  tests/kiwi_images_test/validate_local_kiwi_image.pm
Labels: qe-core

#17228 Integrate yupdate script in openQA in order to get e2e playwright tests from a different repo
  lib/yam/agama/patch_agama_base.pm
  schedule/yam/agama/agama_installation.yaml
  tests/yam/agama/patch_agama.pm
  variables.md
Labels: qe-yam

#16685 Create default yaml if applies for aarch64 and adapt test suites to use it if needed in YaST group
  schedule/yast/btrfs/btrfs+warnings_aarch64.yaml
  schedule/yast/encryption/activate_encrypted_volume+force_recompute_aarch64.yaml
  schedule/yast/encryption/activate_encrypted_volume+import_users_aarch64.yaml
  schedule/yast/encryption/crypt_no_lvm_aarch64.yaml
  schedule/yast/encryption/cryptlvm+cancel_existing_aarch64.yaml
  schedule/yast/encryption/cryptlvm_sle_15_aarch64.yaml
  schedule/yast/encryption/lvm_encrypt_separate_boot_aarch64.yaml
  schedule/yast/encryption/lvm_full_encrypt_aarch64.yaml
  schedule/yast/installer_extended/installer_extended_aarch64.yaml
  schedule/yast/lvm/lvm+cancel_existing_cryptlvm_aarch64.yaml
  schedule/yast/lvm/lvm_sle_aarch64.yaml
  schedule/yast/lvm/lvm_thin_provisioning_aarch64.yaml
  schedule/yast/lvm_multipath_aarch64.yaml
  schedule/yast/lvm_multipath_encrypted_aarch64.yaml
  schedule/yast/lvm_raid1/lvm+raid1_sle15_aarch64.yaml
  schedule/yast/minimal+base/minimal+base@yast_aarch64.yaml
  schedule/yast/minimal+role_minimal/minimal+role_minimal_aarch64.yaml
  schedule/yast/modify_existing_partition/modify_existing_partition_aarch64.yaml
  schedule/yast/raid/raid0_sle_gpt_uefi_aarch64.yaml
  schedule/yast/raid/raid10_sle_gpt_uefi_aarch64.yaml
  schedule/yast/raid/raid1_sle_gpt_uefi_aarch64.yaml
  schedule/yast/raid/raid5_sle_gpt_uefi_aarch64.yaml
  schedule/yast/raid/raid6_sle_gpt_uefi_aarch64.yaml
  schedule/yast/releasenotes_origin+unregistered_aarch64.yaml
  schedule/yast/select_disk/select_disk_aarch64.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration_aarch64.yaml
  schedule/yast/select_modules_and_patterns/select_modules_and_patterns_aarch64.yaml
  schedule/yast/skip_registration/skip_registration_aarch64.yaml
  schedule/yast/sle/flows/default_x86_64.yaml
  schedule/yast/textmode/ha_textmode_aarch64.yaml
  schedule/yast/textmode/ha_textmode_minimal_base_aarch64.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_aarch64.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_minimal_base_aarch64.yaml
  schedule/yast/textmode/textmode_aarch64.yaml
  schedule/yast/textmode_installation_minimal_role/textmode_installation_minimal_role_aarch64.yaml
  schedule/yast/transactional_server/create_hdd_transactional_server_aarch64.yaml
  schedule/yast/yast_hostname/yast_hostname+dhcp_hostname_aarch64.yaml
  schedule/yast/yast_hostname/yast_hostname+linuxrc_hostname_aarch64.yaml
  schedule/yast/yast_hostname/yast_hostname_aarch64.yaml
  schedule/yast/yast_no_self_update/yast_no_self_update_aarch64.yaml
  schedule/yast/yast_self_update/yast_self_update_aarch64.yaml
  test_data/yast/encryption/full_lvm_enc_cancel.yaml
  test_data/yast/encryption/full_lvm_enc_import_user.yaml
  test_data/yast/installation/network_config.yaml
  test_data/yast/installer_extended/installer_extended_aarch64.yaml
  test_data/yast/minimal_base_aarch64.yaml
  test_data/yast/multipath_encrypted.yaml
  test_data/yast/raid/raid1_gpt_uefi_aarch64.yaml
  test_data/yast/raid/raid6_gpt_uefi_aarch64.yaml
  test_data/yast/select_disk_aarch64.yaml
  test_data/yast/select_modules_and_patterns/select_modules_and_patterns_aarch64.yaml
Labels: qe-yam

#17180 Handle vendor change issues in automation for migration cases that with PackageHub installed
  lib/y2_installbase.pm
  lib/y2_logs_helper.pm
Labels: qe-yam

#17260 sys-param: Use public gh repo instead of local
  tests/sles4sap/sys_param_check.pm
Labels: Ready, qe-core

#17256 Add PAYG support for qesap regression
  data/sles4sap/qe_sap_deployment/qesap_azure_no_reg.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
  tests/sles4sap/qesapdeployment/configure.pm
  tests/sles4sap/qesapdeployment/test_cluster.pm
Labels: WIP

#17266 boottime old tests decommissioning
  lib/main_publiccloud.pm
  tests/publiccloud/boottime.pm
  variables.md
Labels: WIP

#17247 Deal with no bounce back on powerKVM
  lib/opensusebasetest.pm
Labels: qe-yam

#16737 Split patch_sle to several modules
  schedule/migration/migration_offline_media_x86_64.yaml
  schedule/migration/migration_offline_scc_x86_64.yaml
  tests/migration/SUSEConnect_register_system.pm
  tests/migration/deregister_system.pm
  tests/migration/drop_unavailable_product_modules.pm
  tests/migration/install_patterns.pm
  tests/migration/patch_and_reboot_system.pm
  tests/migration/setup_sle.pm
Labels: qe-yam

#17269 Enable automation for YaST in Container in ALP in OSD
  schedule/alp/yast_as_workload.yaml
Labels: qe-yam

#17271 Enable updates for autoyast_filesystem_withouthome_yast in Maintenance Updates
  data/filesystem/autoyast_filesystem_withouthome_yast.xml.ep
Labels: qe-yam

#17283 Fix some glitches for yast ppc64le default yaml
  schedule/yast/encryption/activate_encrypted_volume+import_users_pvm.yaml
  schedule/yast/lvm/lvm+cancel_existing_cryptlvm_pvm.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_pvm.yaml
Labels: qe-yam

#17227 prepare_instance updated to retry on error in wait_for_ssh
  lib/publiccloud/instance.pm
  tests/publiccloud/prepare_instance.pm
  variables.md
Labels: WIP

#17296 Add msdos test at YaST job group for aarch64
  schedule/yast/msdos/msdos_aarch64.yaml
  test_data/yast/msdos/msdos_aarch64.yaml
Labels: qe-yam

#17148 Create autoyast installation for sle15 sp3 sdk
  data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_s390x.xml
  lib/registration.pm
  tests/autoyast/installation.pm
Labels: qe-yam

#17291 Don't use default iface 'ovs-system' on xen setup
  tests/installation/bootloader_svirt.pm
Labels: qe-core

#17303 Update yaml schedule for openjdk test
  schedule/qam/15-SP4/qam-regression-other_fips.yaml
  schedule/qam/15-SP5/qam-regression-other_fips.yaml
Labels: Ready, qe-core

#17314 Add retries on autofs client to sync data with server
  tests/network/autofs_client.pm
Labels: qe-core

#17320 prepare_instance update in P.C. to handle ssh connectivity errors
  tests/publiccloud/prepare_instance.pm
Labels: WIP

#17322 Wait for 'zypper purge-kernels' done in update_minimal test
  tests/qam-minimal/update_minimal.pm
Labels: qe-core

#17305 Add network peering to IBSm in sles4sap publiccloud
  data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
  data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
  lib/sles4sap_publiccloud_basetest.pm
  tests/sles4sap/publiccloud/network_peering.pm
Labels: WIP
