Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-04, with the labels that each got.

#16754 Y2K38 Epochalypse
  lib/main_micro_alp.pm
  schedule/functional/extra_tests_textmode.yaml
  tests/console/year_2038_detection.pm
Labels: qe-core

#16792 Fix ext4 & lvm qam-minimal schedule
  schedule/qam/common/qam-minimal.yaml
Labels: Ready, qe-core

#16748 Add yast2-migration-sle for leap to SLE migration
  lib/registration.pm
  tests/migration/online_migration/pre_migration.pm
  tests/migration/online_migration/yast2_migration.pm
Labels: qe-yam

#16804 Allow perl and python extensions in yaml schedule
  lib/main_common.pm
Labels: qe-core

#16810 Replace SCC credentials with variable
  tests/smt/smt_server_install.pm
Labels: Ready, qe-core

#16809 Replace record_softfailure by record_info in zypper_lifecycle
  tests/console/zypper_lifecycle.pm
Labels: qe-yam

#16690 Add autoyast profiles of 15SP4 allpatterns installation
  data/autoyast_sle15/create_hdd/create_hdd_gnome_allpatterns_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_aarch64.xml
Labels: qe-yam

#16830 Handle java license popup during installation
  lib/Distribution/Opensuse/Tumbleweed.pm
  lib/Installation/Popups/AcceptPopup.pm
  lib/Installation/Popups/AcceptPopupController.pm
  tests/installation/confirm_installation.pm
Labels: qe-yam

#16826 Fix code for apply_workaround_poo124652
  lib/YaST/workarounds.pm
Labels: qe-yam

#16833 Change force_scheduled_tasks order for s390 migration tests
  schedule/migration/s390x_regression_test_offline.yaml
  schedule/migration/s390x_regression_test_online.yaml
Labels: qe-yam

#16845 Add PATTERNS condition for accepting java popup
  tests/installation/confirm_installation.pm
Labels: qe-yam

#16749 Workaround bsc#1209083 via reducing matched needle
  tests/autoyast/installation.pm
Labels: qe-yam

#16840 Update workaround for bsc#1207157
  lib/YaST/workarounds.pm
Labels: qe-yam

#16848 Upload zypper log if any issue with test 'patterns'
  tests/console/patterns.pm
Labels: qe-core

#16843 Clean workaround for bsc#1178761
  tests/console/force_scheduled_tasks.pm
Labels: qe-yam

#16852 Unlock screensaver with mouse also on 15-SP2
  lib/x11utils.pm
Labels: Ready, qe-core

#16858 Update autoyast profile of autoyast_bcache.xml
  data/autoyast_sle15/autoyast_bcache.xml
Labels: qe-yam

#16851 sys_param_check: Update code for TW
  tests/sles4sap/sys_param_check.pm
Labels: Ready, qe-core

#16855 Fix assert_screen in apply_workaround_poo124652
  lib/YaST/workarounds.pm
Labels: qe-yam

#16817 Cover year_2038_detection test on TW and Micro-OS
  lib/main_micro_alp.pm
  schedule/functional/extra_tests_textmode.yaml
  tests/console/year_2038_detection.pm
Labels: Ready, qe-core

#16876 Remove Java popup handling
  tests/installation/confirm_installation.pm
Labels: WIP, qe-yam

#16868 Fix needle match timeout for firefox_appearance test
  tests/x11/firefox/firefox_appearance.pm
Labels: qe-core

#16869 Test ovn3 on sles15sp5
  tests/console/ovn.pm
  variables.md
Labels: Ready, qe-core

#16832 Add create_hdd_textmode tests via autoyast
  data/autoyast_opensuse/create_hdd/create_hdd_textmode_aarch64.xml
  data/autoyast_opensuse/create_hdd/create_hdd_textmode_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_ppc64le.xml
  schedule/functional/autoyast_create_hdd/autoyast_create_hdd_textmode.yaml
Labels: Ready, qe-core

#16877 Increase timeout value for startupdate
  tests/installation/start_install.pm
Labels: qe-yam

#16904 Bump timeout for mediacheck in aarch64
  tests/installation/mediacheck.pm
Labels: qe-yam

#16816 we need to reduce modules for regression migration cases at powerVM
  lib/utils.pm
Labels: qe-yam

#16927 ALP test profile for automated installation of Bedrock
  data/yam/agama/auto/alp.sh
  schedule/yast/opensuse/agama_autoinst.yaml
  tests/yam/agama/auto/auto.pm
  tests/yam/agama/auto/url_prepare.pm
Labels: qe-yam

#16922 Recover workaround for bsc#1129504
  tests/installation/disable_grub_timeout.pm
  tests/installation/upgrade_select.pm
Labels: qe-yam

#16846 Removing soft failure bsc#1163000 marked as WONTFIX
  lib/service_check.pm
Labels: qe-yam

#16892 Ensure 'Add' button clicked in Network Settings
  tests/yast2_gui/yast2_network_settings.pm
Labels: qe-yam

#16929 Update for alp auto-installation
  lib/bootloader_setup.pm
  schedule/yam/agama_auto.yaml
  schedule/yast/opensuse/agama_autoinst.yaml
  tests/yam/agama/auto.pm
  tests/yam/agama/auto/auto.pm
Labels: qe-yam

#16822 Put timeout scale logic into YuiRestClient.pm
  lib/Installation/PerformingInstallation/PerformingInstallationController.pm
  lib/Installation/ProductSelection/ProductSelectionController.pm
  lib/YuiRestClient/Wait.pm
  tests/installation/performing_installation/perform_installation.pm
  tests/installation/product_selection/install_SLES.pm
Labels: qe-yam

#16938 Use ip address instead of DNS name before joining to domain
  tests/network/samba/samba_adcli.pm
Labels: qe-core

#16695 Ensure staging tests are using libyui-rest-api
  schedule/staging/RAID1@64bit-staging.yaml
  schedule/staging/cryptlvm_minimal_x@64bit-staging.yaml
  schedule/staging/default_install@64bit-staging.yaml
  schedule/staging/ext4@uefi-staging.yaml
  schedule/staging/gnome@64bit-staging.yaml
Labels: qe-yam
