Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2023-05, with the labels that each got.

#16941 Using Agama to perform auto-installation of Tumbleweed
  data/yam/agama/auto/alp_tw.json
  tests/yam/agama/auto.pm
Labels: qe-yam

#16968 grub2_test: ZFS is not present on SLE 15+
  tests/boot/grub2_test.pm
Labels: Ready, qe-core

#16980 Add assert option in firefox_open_url
  lib/x11test.pm
Labels: Ready, qe-core

#16988 Modify raid partitioning for chunksize=null
  lib/Installation/Partitioner/LibstorageNG/v4_3/ExpertPartitionerController.pm
  schedule/staging/RAID1@64bit-staging-Y.yaml
Labels: qe-yam

#16977 s390tools: Drop dasd_reload check
  tests/qam-minimal/s390tools.pm
Labels: Ready, qe-core

#16986 Add second host if mirror.suse.cz is down
  lib/x11test.pm
  tests/x11/firefox/firefox_appearance.pm
  tests/x11/firefox/firefox_developertool.pm
  tests/x11/firefox/firefox_extcontent.pm
  tests/x11/firefox/firefox_extensions.pm
  tests/x11/firefox/firefox_fullscreen.pm
  tests/x11/firefox/firefox_headers.pm
  tests/x11/firefox/firefox_html5.pm
  tests/x11/firefox/firefox_localfiles.pm
  tests/x11/firefox/firefox_pagesaving.pm
  tests/x11/firefox/firefox_passwd.pm
  tests/x11/firefox/firefox_pdf.pm
  tests/x11/firefox/firefox_private.pm
  tests/x11/firefox/firefox_ssl.pm
  tests/x11/firefox/firefox_urlsprotocols.pm
Labels: Ready, qe-core

#16942 Update autoyast profile for textmode installation
  data/autoyast_sle15/autoyast_sle_powervm.xml.ep
Labels: qe-yam

#16996 Fix autoyast pattern and user issues on qem test
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
  lib/autoyast.pm
  schedule/qam/common/15-common_base_installation_ay.yaml
Labels: qe-core

#17015 Increase timeout for smt-mirror
  tests/smt/smt_server_install.pm
Labels: enhancement

#17018 Apply workaround for bsc#1202234 for autoyast install
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
  tests/qa_automation/patch_and_reboot.pm
Labels: qe-core

#17025 Remove chunk size for RAID1 test_data
  schedule/staging/RAID1@64bit-staging.yaml
  schedule/staging/RAID1@s390x-staging.yaml
  schedule/yast/opensuse/raid/raid1_gpt_leap.yaml
  schedule/yast/raid/raid0_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid10_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid1_sle_gpt.yaml
  schedule/yast/raid/raid1_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid1_sle_gpt_uefi.yaml
  schedule/yast/raid/raid5_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid6_sle_gpt_prep_boot_pvm.yaml
  test_data/yast/lvm_raid1/lvm+raid1_mds.yaml
  test_data/yast/lvm_raid1/lvm+raid1_mds_hyperv.yaml
  test_data/yast/lvm_raid1/lvm+raid1_mds_xen.yaml
  test_data/yast/raid/raid0_prep_boot.yaml
  test_data/yast/raid/raid10_prep_boot.yaml
  test_data/yast/raid/raid1_gpt_uefi_test_data.yaml
  test_data/yast/raid/raid1_prep_boot.yaml
  test_data/yast/raid/raid5_prep_boot.yaml
  test_data/yast/raid/raid6_prep_boot.yaml
Labels: qe-yam

#17035 Set grub2 timeout to infinite
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
Labels: qe-core

#17042 Add NIC to the default firewall zone 'public' in AutoYaST
  data/autoyast_qam/15-common_base_installation.xml.ep
Labels: qe-core

#17040 Apply workaround yast2_security due to graphical glitch
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam

#17044 Fix nfs-server exportfs timeout issue
  lib/nfs_common.pm
Labels: qe-yam

#17053 Add agama auto install sh script for Tumbleweed
  data/yam/agama/auto/alp_tw.sh
Labels: qe-yam

#17051 bind: Change retry message soft fail to info
  tests/console/bind.pm
Labels: Ready, qe-core

#16956 Add Playwright automation test
  lib/susedistribution.pm
  schedule/yam/agama/agama_installation.yaml
  tests/yam/agama/agama_installation.pm
Labels: qe-yam

#17027 Fix shim for LTSS-ERICSSON
  lib/qam.pm
  tests/qam-minimal/install_update.pm
Labels: Ready, qe-core

#17078 Use machine in condition to not affect aarch64 jobs
  lib/qam.pm
  tests/qam-minimal/install_update.pm
Labels: Ready, qe-core

#17082 Remove progress reference from soft failure
  lib/x11test.pm
Labels: qe-core

#17085 Create 15-SP5 files
  data/autoyast_qam/15-SP5_installation.xml.ep
  schedule/qam/15-SP5/lvm_thin_provisioning.yaml
  schedule/qam/15-SP5/mau-extratests-phub.yaml
  schedule/qam/15-SP5/mau-filesystem.yaml
  schedule/qam/15-SP5/mau-filesystem@zkvm.yaml
  schedule/qam/15-SP5/mau-userspace.yaml
  schedule/qam/15-SP5/powerpc-utils.yaml
  schedule/qam/15-SP5/qam-allpatterns.yaml
  schedule/qam/15-SP5/qam-create_hdd_ha_textmode.yaml
  schedule/qam/15-SP5/qam-create_hdd_sle_sap_gnome.yml
  schedule/qam/15-SP5/qam-create_hdd_sles4sap_gnome.yml
  schedule/qam/15-SP5/qam-gnome.yaml
  schedule/qam/15-SP5/qam-minimal-RAID1.yaml
  schedule/qam/15-SP5/qam-minimal-base-installation-ay.yaml
  schedule/qam/15-SP5/qam-minimal-base.yaml
  schedule/qam/15-SP5/qam-regression-firefox.yaml
  schedule/qam/15-SP5/qam-regression-firefox_fips.yaml
  schedule/qam/15-SP5/qam-regression-installation.yaml
  schedule/qam/15-SP5/qam-regression-other_fips.yaml
  schedule/qam/15-SP5/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
  schedule/qam/15-SP5/qam-sle_sles4sap_scc_gnome_sapconf.yml
  schedule/qam/15-SP5/qam-sle_sles4sap_scc_gnome_saptune.yml
  schedule/qam/15-SP5/qam-sles4sap_wmp_hana_node1.yaml
  schedule/qam/15-SP5/qam-sles4sap_wmp_hana_node2.yaml
  schedule/qam/15-SP5/qam-textmode.yaml
  schedule/qam/common/mau-extratests-desktop.yaml
  schedule/qam/common/mau-extratests1.yaml
  schedule/qam/common/mau-extratests2.yaml
  schedule/qam/common/mau-webserver.yaml
Labels: qe-core

#17087 Save y2logs in test 'patterns' if any issue
  tests/console/patterns.pm
Labels: qe-core

#17050 Do not pipe output into a pager for wicked service
  tests/autoyast/wicked.pm
Labels: qe-yam

#17088 zypper_lifecycle: Force reinstall release-notes
  tests/console/zypper_lifecycle.pm
Labels: Ready, qe-core

#17090 samba_adcli: Use script_retry for network cmds
  tests/network/samba/samba_adcli.pm
Labels: Ready, qe-core

#17067 Remove workaround of bsc#1206132
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#17097 Remove chunk_size from RAID1 settings on 15-SP5
  schedule/qam/15-SP5/qam-minimal-RAID1.yaml
Labels: qe-core

#17089 Test all available python3 new versions if any
  tests/console/python3_new_version_check.pm
Labels: qe-core

#16994 Recover only yast logs in Agama auto-install
  lib/yam/agama/agama_base.pm
  tests/yam/agama/auto.pm
Labels: qe-yam

#17101 salt_master: Workround harmless error message
  lib/saltbase.pm
Labels: Ready, qe-core

#16823 Unify qam-yast_self_update+15@uefi for sle15sp3 and sle15sp4 using single test module for registration
  lib/Distribution/Sle/15_current.pm
  lib/Installation/ModuleRegistration/SeparateRegCodesController.pm
  lib/Installation/ModuleRegistration/SeparateRegCodesPage.pm
  schedule/yast/qam-yast_self_update.yaml
  schedule/yast/qam-yast_self_update_libyui.yaml
  schedule/yast/sle/flows/default_sle15sp3_aarch64.yaml
  schedule/yast/sle/flows/default_sle15sp3_s390x_kvm.yaml
  schedule/yast/sle/flows/default_sle15sp3_x86.yaml
  schedule/yast/sle/flows/default_sle15sp4_x86.yaml
  schedule/yast/textmode/ha_textmode.yaml
  schedule/yast/textmode/ha_textmode_minimal_base.yaml
  schedule/yast/textmode/ha_textmode_minimal_base_s390x.yaml
  schedule/yast/textmode/ha_textmode_s390x.yaml
  tests/installation/module_registration/add_additional_regcodes.pm
  tests/installation/module_registration/add_ha_regcode.pm
  tests/installation/module_registration/add_ltss_regcode.pm
  tests/installation/module_registration/register_extensions_and_modules.pm
Labels: qe-yam

#17102 bootloader_uefi decrease chance of needle match timeout
  lib/bootloader_setup.pm
  tests/installation/bootloader_uefi.pm
Labels: Ready

#17117 salt_master: Check master log only on master node
  lib/saltbase.pm
Labels: Ready, qe-core

#17126 Add softfail for bsc#1211591 to salt test
  lib/saltbase.pm
Labels: qe-core

#17136 Set password in pre_run_hook for agama_base
  lib/yam/agama/agama_base.pm
Labels: qe-yam

#17120 Don't add development-tools on maintenance tests
  schedule/qam/common/mau-extratests-desktop.yaml
  tests/x11/libqt5_qtbase.pm
Labels: Ready, qe-core

#17142 Enhance the logic to use right container image in sssd-389ds test
  tests/console/sssd_389ds_functional.pm
Labels: qe-core

#17058 Check Python3 module for 3.11 instead of 3.10
  tests/console/check_migration_features.pm
Labels: qe-yam

#17047 Enable automation for YaST in Container in ALP
  schedule/alp/alp_yast.yaml
Labels: qe-yam

#17127 Create autoyast installation testsuite to publish s390x image for sles12sp5 migration tests
  data/autoyast_sle12/create_hdd/create_hdd_sles_regression_s390x.xml.ep
Labels: qe-yam

#16999 Login properly into the systems installed by Agama and verify OS
  lib/yam/agama/agama_base.pm
  schedule/yam/agama_auto.yaml
  test_data/yam/agama_auto_bedrock.yaml
  test_data/yam/agama_auto_micro.yaml
  test_data/yam/agama_auto_tumbleweed.yaml
  tests/yam/agama/validate_product.pm
Labels: qe-yam

#17164 Drop python2 module support on 15sp1-ltss
  tests/console/zypper_lifecycle.pm
Labels: qe-yam

#17177 Remove stop_timeout_system_reboot_now test module at default 15sp4 aarch64 yaml file
  schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi.yaml
  schedule/yast/sle/flows/default_sle15sp4_aarch64.yaml
Labels: qe-yam

#16940 Automate auto-installation of SUSE ALP Micro
  data/yam/agama/auto/alp.sh
  data/yam/agama/auto/alp_micro.jsonnet
  tests/yam/agama/auto.pm
Labels: qe-yam
