Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-01, with the labels that each got.

#18332 Update validate_zfcp_multipath to current infrastructure
  tests/console/validate_zfcp_multipath.pm
Labels: qe-yam

#18387 Workaround for rmt scc cred timeout bsc#1218084
  lib/repo_tools.pm
Labels: Ready, qe-core

#18375 sudo: Fix sudo id -un
  tests/console/sudo.pm
Labels: Ready

#18385 No need to reboot VM if no package update for sle-micro
  tests/microos/cockpit_service.pm
Labels: qe-core

#18372 Fix refreshment issue for iscsi_client
  lib/YaST/workarounds.pm
  lib/yast2_widget_utils.pm
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#18391 Avoid bsc#1180307 in 'ncurses' test
  tests/console/ncurses.pm
Labels: qe-core

#18394 Remove system preparation form usb_install test
  schedule/yam/test_cases/usb_install.yaml
Labels: qe-yam

#18395 Edit conditional schedule for continuous migration test
  schedule/migration/migration_offline_scc_deregistration_aarch64.yaml
  schedule/migration/migration_offline_scc_deregistration_ppc64le.yaml
  schedule/migration/migration_offline_scc_deregistration_x86_64.yaml
Labels: qe-yam

#18402 Don't register to SCC for opensuse install
  tests/installation/bootloader_uefi.pm
Labels: qe-core

#18405 Add softfail for bsc#1217773
  data/journal_check/bug_refs.json
Labels: qe-yam

#18396 containers: Add upstream podman integration tests
  lib/main_containers.pm
  tests/containers/podman_integration.pm
Labels: WIP

#18406 Move Leap 15.4/15.5 incidents installation tests to use autoyast
  data/autoyast_opensuse/opensuse_leap.xml.ep
  schedule/functional/leap15_incidents/incident_update.yaml
Labels: qe-core

#18413 Remove softfail for #bsc992113
  lib/y2lan_restart_common.pm
Labels: qe-yam

#18439 Use podman on newer sle; wait for effective container running
  tests/console/sssd_389ds_functional.pm
Labels: qe-core

#18300 Check secure boot status with efivars
  lib/YaST/EFItools.pm
  schedule/yast/autoyast_non_secure_boot.yaml
  test_data/yast/autoyast/profiles/non_secure_boot.yaml
  tests/console/verify_secure_boot.pm
  tests/installation/verify_secure_boot_bios.pm
Labels: qe-yam

#18452 Ensure to use stdout in valgrind and quote matching on assertion
  tests/console/valgrind.pm
Labels: qe-core

#18451 Fix left_sectors size on sle_micro 6.0
  tests/microos/image_checks.pm
Labels: qe-core

#18450 Don't need 'handle_uefi_boot_disk_workaround' in slem self-install
  tests/microos/selfinstall.pm
Labels: qe-core

#18455 Remove desktop module from textmode ay profiles
  data/yam/autoyast/create_hdd_textmode_aarch64.xml
  data/yam/autoyast/create_hdd_textmode_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_minimal_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_default_patterns_s390x.xml
Labels: qe-yam

#18407 Add new y2log errors in ignore list
  lib/opensusebasetest.pm
Labels: qe-yam

#18424 Merge yaml file of skip_registration and releasenotes_origin+unregistered
  schedule/yam/test_cases/skip_registration.yaml
  schedule/yast/releasenotes_origin+unregistered.yaml
  schedule/yast/releasenotes_origin+unregistered_aarch64.yaml
  schedule/yast/releasenotes_origin+unregistered_pvm.yaml
  schedule/yast/releasenotes_origin+unregistered_x86_64.yaml
  schedule/yast/skip_registration/skip_registration_pvm.yaml
  schedule/yast/skip_registration/skip_registration_x86_64.yaml
Labels: qe-yam

#18434 Fix sporadic issues in yast2_instserver
  lib/y2_module_guitest.pm
  tests/yast2_gui/yast2_instserver.pm
Labels: qe-yam

#18484 Revisit soft-failure bsc#1203004 for GMC
  lib/y2_installbase.pm
  tests/installation/licensing/verify_license_translations.pm
Labels: qe-yam

#18474 No '-p' parameter needed for SUSEConnect to activate base product on migrated system
  tests/console/system_prepare.pm
Labels: qe-yam

#18462 Enable variable to softfail only some specific subtests
  tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
  tests/systemd_testsuite/runner.pm
Labels: qe-core

#18464 Adapt svirt backend to be able to boot systems with root ssh disabled
  lib/opensusebasetest.pm
  tests/boot/boot_to_desktop.pm
Labels: qe-core

#18498 Add skip_registartion schedule for maintenance
  schedule/yast/maintenance/skip_registration.yaml
Labels: qe-yam

#18441 Add function to detect RC builds and update release_notes_from_url
  lib/y2_installbase.pm
  tests/installation/release_notes_from_url.pm
Labels: qe-yam

#18501 Change condition for apply_workaround_poo124652
  lib/y2_module_guitest.pm
  tests/yast2_gui/yast2_instserver.pm
Labels: qe-yam

#18493 Remove softfailure for bsc#1192992
  lib/x11utils.pm
Labels: qe-yam

#18519 Revisit launch_yast2_module_x11 to use parameter to apply workaround
  lib/y2_module_guitest.pm
  tests/yast2_gui/yast2_instserver.pm
Labels: qe-yam

#18448 Reduce yaml files usage
  schedule/yam/test_cases/select_modules_and_patterns+registration.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@pvm.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x_zvm.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration_aarch64.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration_x86_64.yaml
Labels: qe-yam

#18534 Add python3 to avoid dependency popup
  tests/installation/module_selection/select_nonconflicting_modules.pm
Labels: qe-yam

#18533 Revert "Add skip_registartion schedule for maintenance"
  schedule/yast/maintenance/skip_registration.yaml
Labels: WIP

#18538 Make s390x kvm setup information more visable
  tests/installation/bootloader_zkvm.pm
Labels: qe-core

#18537 Enable root ssh on slem 6.0 firstrun
  tests/jeos/firstrun.pm
Labels: qe-core

#18390 Adapt yast2 modules tests of configuring firewall for Tumbleweed
  tests/console/yast2_ftp.pm
  tests/console/yast2_rmt.pm
  tests/console/yast2_tftp.pm
  tests/console/yast2_vnc.pm
Labels: qe-yam

#18523 Merge activate_encrypted_volume* schedules for different archs
  schedule/yam/test_cases/activate_encrypted_volume+force_recompute.yaml
  schedule/yam/test_cases/activate_encrypted_volume+import_users.yaml
  schedule/yast/encryption/activate_encrypted_volume+force_recompute.yaml
  schedule/yast/encryption/activate_encrypted_volume+import_users_aarch64.yaml
Labels: qe-yam

#18496 Reduce yaml files for RAID0 testsuites
  schedule/yam/test_cases/raid0_sle_gpt.yaml
  schedule/yast/raid/raid0_sle_gpt_uefi.yaml
  schedule/yast/raid/raid0_sle_gpt_uefi_aarch64.yaml
Labels: qe-yam

#18525 Install a pip package via local http server
  tests/console/python3_setuptools.pm
Labels: qe-core

#18553 Enable flatpak tests for 15+
  lib/main_common.pm
Labels: Ready, qe-core

#18549 Add error message in detect_yast2_failures ignore list
  lib/opensusebasetest.pm
Labels: qe-yam

#18554 containers: Add catatonit package to use in podman integration tests
  tests/containers/podman_integration.pm
Labels: WIP

#18551 Change pbl log file verification
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core
