Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-06, with the labels that each got.

#19443 Remove release package from SCC_ADDONS_DROP
  tests/yam/migration/setup_registration.pm
Labels: qe-yam

#19447 Fix Elemental openQA test
  data/elemental/cloud-config.yaml
  tests/elemental/installation.pm
Labels: bug, Ready

#19449 Ay profile for skip_registration_functional
  data/autoyast_sle15/autoyast_no_scc_reg.xml
  schedule/functional/minimal+proxy_SCC-postreg_SUSEconnect.yaml
Labels: Ready, qe-core

#19468 Add "--gpg-auto-import-keys" option to install openSUSE-repos-NVIDIA
  tests/console/opensuse_repos.pm
Labels: qe-core

#19466 Add support for Elemental based on SLE Micro 5.5
  data/elemental/cloud-config.yaml
  data/elemental/install.yaml
  tests/elemental/installation.pm
Labels: enhancement, Ready

#19475 Use podman instead of docker in hawk_gui test module
  tests/ha/hawk_gui.pm
Labels: WIP

#19481 Refresh repos if zypper gets return 106
  tests/console/opensuse_repos.pm
Labels: qe-core

#19484 Revert "Remove release package from SCC_ADDONS_DROP"
  tests/yam/migration/setup_registration.pm
Labels: qe-yam

#19478 Use snapper rollback to get to state before patch
  lib/utils.pm
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19479 Quick fix for SUSEConnect -d
  tests/yam/migration/setup_registration.pm
Labels: qe-yam

#19485 containers: Increase subuid range
  tests/containers/rootless_docker.pm
  tests/containers/rootless_podman.pm
Labels: WIP

#19492 Revert "Use latest kernel instead active to get debuginfo"
  lib/kdump_utils.pm
Labels: Ready

#19427 Move single yaml test suite to yaml test case path
  schedule/yam/test_cases/autologin@yast.yaml
  schedule/yam/test_cases/boot_linuxrc.yaml
  schedule/yam/test_cases/cryptlvm_iscsi.yaml
  schedule/yam/test_cases/do_not_import_ssh_keys.yaml
  schedule/yam/test_cases/dud_development_tools.yaml
  schedule/yam/test_cases/fstab_mount_by.yaml
  schedule/yam/test_cases/gpt.yaml
  schedule/yam/test_cases/import_ssh_keys.yaml
Labels: qe-yam

#19501 Add version slem 5.1 to white list for bsc#1226203
  data/journal_check/bug_refs.json
Labels: qe-yam

#19502 installtest: Drop partition setup & Fix remove ISO repo
  data/autoyast_qam/12_installtest.xml.ep
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19504 Add back repos to HA image
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19505 containers: Use registry.opensuse.org/opensuse/nginx instead of httpd
  tests/containers/podman_netavark.pm
Labels: WIP

#19510 Support CRASH_MEMORY on yast2 kdump
  lib/kdump_utils.pm
Labels: Ready, qe-core

#19527 containers: Increase timeout for podman upstream tests
  tests/containers/podman_integration.pm
Labels: urgent

#19526 P.C. get instance empty and skip serial log SAP
  lib/publiccloud/azure.pm
  lib/publiccloud/ec2.pm
  lib/publiccloud/gce.pm
  lib/publiccloud/provider.pm
Labels: WIP

#19536 Add softfail for opensuse repo refreshing issue
  tests/console/opensuse_repos.pm
Labels: qe-core

#19506 Uncheck hide development modules
  schedule/yast/qam-yast_self_update_view_development.yaml
  schedule/yast/sle/flows/default_sle15sp6_x86_view_development.yaml
Labels: qe-yam

#19559 containers: Use our own nginx & haproxy images
  data/containers/docker-compose.yml
  tests/containers/compose.pm
Labels: urgent

#19539 Update AY profile to fix s390x installation issue
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
Labels: qe-yam

#19586 Remove wsl patterns from autoyast profiles for support images
  data/autoyast_sle15/create_hdd/create_hdd_gnome_allpatterns_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_aarch64.xml
  data/yam/autoyast/autoyast_pcm_lgm_allpatterns_ppc64le.xml.ep
  data/yam/autoyast/create_hdd_gnome_allpatterns_aarch64.xml
  data/yam/autoyast/create_hdd_gnome_sdk_allpatterns_aarch64.xml
  data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep
  data/yam/autoyast/support_images/create_hdd_hpc_development_node_x86_64.xml.ep
  data/yam/autoyast/support_images/create_hdd_hpc_management_server_aarch64.xml.ep
  data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep
  data/yam/autoyast/support_images/create_hdd_hpc_textmode_x86_64.xml.ep
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
  lib/utils.pm
Labels: qe-yam

#19584 Move, unify upload_y2logs and add retry
  lib/guest_installation_and_configuration_base.pm
  lib/hacluster.pm
  lib/qam.pm
  lib/sles4sap.pm
  lib/utils.pm
  lib/virt_autotest/utils.pm
  lib/y2_base.pm
  lib/y2snapper_common.pm
  tests/virt_autotest/reboot_and_wait_up_upgrade.pm
Labels: Ready, qe-core

#19594 update_install: Add back phub repo with exception
  data/autoyast_qam/15_installtest.xml.ep
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19548 Add deregistration case for MU migration tests
  schedule/yast/maintenance/create_hdd_maintenance_deregistered.yaml
  tests/yam/migration/setup_registration.pm
Labels: qe-yam

#19602 containers: Add test for podman-remote package
  lib/main_containers.pm
  tests/containers/podman_remote.pm
Labels: WIP

#19611 containers: Skip podman-remote package test on Staging
  tests/containers/podman_remote.pm
Labels: urgent

#19613 containers: Do not check_reboot_changes if package was not installed
  tests/containers/podman_remote.pm
Labels: urgent

#19615 containers: Fix containers volume options
  tests/containers/podman_netavark.pm
Labels: WIP

#19616 containers: Use select_console for transactional systems
  tests/containers/podman_remote.pm
Labels: WIP
