Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-03, with the labels that each got.

#18772 Increase timeout for assert_screen inside nis_server.pm
  tests/x11/nis_server.pm
Labels: qe-yam

#18775 Apply the glitch workaround in yast2_security
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam

#18780 Increase the minimal size for XFS
  data/yam/autoyast/multipath.xml
Labels: qe-yam

#18798 Update sle15 autoyast profile for TERADATA flavor
  data/autoyast_qam/15-common_base_installation.xml.ep
  lib/autoyast.pm
Labels: Ready, qe-core

#18802 PC: Fix ssh key corner cases
  lib/publiccloud/utils.pm
  tests/publiccloud/run_ltp.pm
Labels: Verification-Runs-needed

#18811 Update condition for ipxe installer
  tests/installation/ipxe_install.pm
Labels: qe-yam

#18821 Make sure focus is in text window before typing
  tests/x11/oomath.pm
Labels: qe-core

#18833 Propose new configuration from scratch if unknown udev devices
  tests/console/yast2_bootloader.pm
Labels: qe-core

#18843 Fix sudo test logic for NOPASSWD
  tests/console/sudo.pm
Labels: qe-core

#18854 Add some delay for pam test script to handle race condition
  data/pam_test/pam_deprecated.sh
Labels: qe-core

#18864 Add more delay for pam test script to handle race condition
  data/pam_test/pam_deprecated.sh
Labels: qe-core

#18847 Make sure the focus is on xterm before closing it
  tests/x11/steam.pm
Labels: qe-core

#18857 Split long lines in qesapdeploy lib
  lib/qesapdeployment.pm
Labels: WIP

#18878 Quick PR to update product checking for cross product migration
  tests/console/check_system_info.pm
Labels: qe-yam

#18880 Replace the regression migration test from gnome to textmode
  data/yam/autoyast/support_images/sles12sp5_install_all_patterns_ppc64le_multi-user.xml
  schedule/migration/ppc64le_regression_test_offline_textmode.yaml
Labels: qe-yam

#18890 Update 'pycairo_sample.svg' file
  data/python/pycairo_sample.svg
Labels: qe-core

#18827 Make stable validate_lvm_raid1 reboot
  tests/console/validate_lvm_raid1.pm
Labels: qe-yam

#18903 Revert "Update 'pycairo_sample.svg' file"
  data/python/pycairo_sample.svg
Labels: qe-core

#18904 Update 'pycairo_sample.svg' file
  data/python/pycairo_sample_new.svg
  tests/console/python_pycairo.pm
Labels: qe-core

#16315 Change conflict handling and add some features
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#18905 Get dynamic wwid for zfcp-multipath
  tests/console/validate_zfcp_multipath.pm
Labels: qe-yam

#18928 Create test module libgit2
  data/libgit2/pygit2_test.py
  lib/python_version_utils.pm
  schedule/functional/extra_tests_textmode.yaml
  tests/console/libgit2.pm
Labels: qe-core

#18866 Add test module for man pages
  schedule/functional/extra_tests_textmode.yaml
  schedule/qam/common/mau-extratests1.yaml
  tests/console/man_pages.pm
Labels: Ready, qe-core

#18822 Revisit soft-failures bsc#1151130 and bsc#1151135
  tests/yast2_cmd/yast_dns_server.pm
Labels: qe-yam

#18941 Add 'sle-module-python3' to autoyast config file
  data/autoyast_sle15/create_hdd/create_hdd_gnome_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_allpatterns_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_disabled_firewall.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_sdk_allpatterns_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_we_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_gnome_x86_64_uefi.xml
  data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_minimal_base_sdk_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_textmode_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_textmode_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_textmode_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_textmode_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_x86_64_uefi.xml
Labels: qe-core

#18962 Use ay profile for multipath installation
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/15-common_base_installation.xml.ep
  tests/console/kdump_and_crash.pm
Labels: Ready, qe-core

#18973 Fix libgit2 issue
  tests/console/libgit2.pm
Labels: qe-core

#18986 Add some timeout for krb5 test
  tests/console/krb5.pm
Labels: qe-core
