Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-10, with the labels that each got.

#20323 Remove fatal flag from openssl_tlsv1_3
  tests/fips/openssl/openssl_tlsv1_3.pm
Labels: qe-security

#20318 Extend white list for bsc#1215378
  data/journal_check/bug_refs.json
Labels: Ready, qe-core

#20330 update_install: Add cyrus-sasl conflicts
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#20332 Boot agama in OSD in architectures using qemu
  lib/Distribution/Sle/AgamaDevel.pm
Labels: qe-yam

#20312 Remove agama_grub2 for ppc64le
  schedule/yam/agama_auto_ppc64le.yaml
  schedule/yam/agama_ppc64le.yaml
  tests/yam/agama/agama_grub2.pm
Labels: qe-yam

#20341 Don't install legacy module packages on SLERT
  tests/fips/openjdk/openjdk_fips.pm
Labels: qe-security

#20240 Create agama auto-installation selecting gnome pattern
  data/yam/agama/auto/gnome_tumbleweed.json
  tests/yam/agama/agama_auto.pm
Labels: qe-yam

#20310 Fix sporadic time sync issue for year_2038_detection test
  tests/console/year_2038_detection.pm
Labels: qe-core

#20348 Make sure screen is changed after first grub phase
  lib/transactional.pm
Labels: qe-core

#20344 health_check: Increase grub2 timeout
  lib/transactional.pm
Labels: Ready, qe-core

#20351 Agama: enable installation for full encryption with focus on booting
  schedule/yam/agama_full_disk_encryption.yaml
Labels: qe-yam

#20360 Workaround for aarch64 performance issue
  lib/mm_network.pm
  tests/network/setup_multimachine.pm
  tests/security/cc/setup_net_test_env.pm
Labels: qe-security

#20347 Boot agama in OSD in s390x with zVM
  lib/susedistribution.pm
  tests/installation/bootloader_s390.pm
Labels: qe-yam

#20361 Add grub menu page for Leap
  lib/Distribution/Opensuse/Leap/16Latest.pm
  lib/DistributionProvider.pm
  lib/Yam/Agama/Pom/GrubMenuLeapPage.pm
Labels: qe-yam

#20371 start_install: Increase timeout
  tests/installation/start_install.pm
Labels: Ready, qe-core

#20373 functional: Change test order
  schedule/functional/extra_tests_textmode_phub.yaml
Labels: Ready, qe-core

#20116 Universal network bonding test
  data/network_bonding/dnsmasq.conf
  data/network_bonding/kea-dhcp4.conf
  lib/network_utils.pm
  lib/registration.pm
  schedule/functional/extra_tests_network_bonding.yaml
  schedule/microos/bonding.yaml
  tests/console/suseconnect_scc.pm
  tests/network/network_bonding.pm
  tests/network/network_bonding_setup.pm
Labels: Ready, qe-core

#20405 Install openssl1.1 binary when legacy module isn't available
  lib/security/openssl_misc_utils.pm
Labels: qe-security

#20399 Agama: enable installation for full encryption on SLES
  lib/Distribution/Sle/AgamaDevel.pm
  lib/Yam/Agama/Pom/GrubMenuSlesPage.pm
Labels: qe-yam

#20389 Agama s390x ca-certificates-s390x workaround
  tests/yam/agama/agama.pm
Labels: qe-yam

#20414 Fix Agama Sle 16.0 distribution issue
  lib/Distribution/Sle/16Latest.pm
  lib/DistributionProvider.pm
Labels: qe-yam

#20370 Use desktop runner to refresh screen
  tests/x11/toolkits/fltk.pm
Labels: qe-core

#20418 Fix method import in Agama default test
  tests/yam/agama/agama.pm
Labels: qe-yam

#20157 Reduce yaml files for minimal+base_yast
  schedule/yam/test_cases/minimal+base_yast.yaml
  schedule/yast/minimal+base/minimal+base@s390x_zvm.yaml
  schedule/yast/minimal+base/minimal+base@svirt-xen-hvm.yaml
  schedule/yast/minimal+base/minimal+base@yast-s390x.yaml
  schedule/yast/minimal+base/minimal+base@yast-svirt-hyperv.yaml
  schedule/yast/minimal+base/minimal+base@yast-xen-pv.yaml
  schedule/yast/minimal+base/minimal+base@yast.yaml
  schedule/yast/minimal+base/minimal+base@yast_aarch64.yaml
  schedule/yast/minimal+base/minimal+base@yast_x86_64.yaml
  schedule/yast/sle/flows/default_aarch64.yaml
  schedule/yast/sle/flows/default_ppc64le.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
  schedule/yast/sle/flows/default_s390x_zvm.yaml
  schedule/yast/sle/flows/default_svirt-xen-hvm.yaml
  schedule/yast/sle/flows/default_svirt-xen-pv.yaml
  schedule/yast/sle/flows/default_x86_64.yaml
  test_data/yam/minimal+base_yast.yaml
  test_data/yast/minimal+base_yast@s390x.yaml
Labels: qe-yam

#20439 Schedule salt smoke test on SLE staging
  schedule/jeos/sle/jeos-main.yaml
  schedule/staging/cryptlvm_minimal_x@64bit-staging.yaml
  schedule/staging/gnome@64bit-staging.yaml
  schedule/staging/minimal+base@64bit-staging.yaml
Labels: qe-core

#20394 Set boot parameter 'console' on grub2 entry after installation for Leap 16.0
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Distribution/Opensuse/Leap/16Latest.pm
  lib/Distribution/Sle/16Latest.pm
  lib/Yam/Agama/Pom/GrubEntryEditionPage.pm
  lib/Yam/Agama/Pom/GrubMenuBaseBug1231658Page.pm
Labels: qe-yam

#20425 Enable agama_auto_gnome for Leap 16.0
  data/yam/agama/auto/gnome_leap.json
Labels: qe-yam

#20412 Ensure sshd installed before testing openssh client
  tests/fips/openssh/openssh_fips.pm
Labels: qe-security

#20411 Add PyNaCl and libsodium test
  data/python/pynacl/test_pynacl.py
  lib/python_version_utils.pm
  schedule/functional/stack_tests_python.yaml
  tests/console/python3_pynacl.pm
Labels: Ready, qe-core

#20463 Introduce test for gnutls crypto_policies
  tests/security/crypto_policies/crypto_policies_tests.pm
Labels: qe-security

#20473 Need remove cc pattern from AY profiles for bsc#1231607
  data/yam/autoyast/support_images/create_hdd_hpc_development_node_aarch64.xml.ep
  data/yam/autoyast/support_images/create_hdd_hpc_textmode_aarch64.xml.ep
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp4_install_textmode_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_gnome_all_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp5_install_textmode_all_patterns_x86_64.xml
Labels: qe-yam

#20447 Schedule salt smoke tests on micro-os
  lib/main_micro_alp.pm
  tests/console/salt.pm
Labels: qe-core

#20434 Agama: fix validate product. SLE to SLES
  test_data/yam/agama_sle.yaml
Labels: qe-yam

#20489 Fix screen match issue on vnc_two_passwords
  tests/x11/vnc_two_passwords.pm
Labels: qe-core

#20495 Use correct casing for FIPS environment var
  tests/fips/fips_setup.pm
Labels: qe-security

#20488 Is openssh installed on 15SP2
  tests/fips/openssh/openssh_fips.pm
Labels: qe-security

#20493 Make sure nic is connected before adding route
  lib/mm_network.pm
  tests/network/firewalld_policy_objects.pm
Labels: qe-core

#20507 Quickfix for journal_check
  data/journal_check/bug_refs.json
Labels: qe-yam

#20513 Disable screensaver for leap 15.x upgrade tw test
  products/opensuse/main.pm
  schedule/functional/upgrade_Leap_15.1_gnome.yaml
Labels: qe-core
