Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-11, with the labels that each got.

#20523 Click close button to close opensuse welcome page
  lib/x11utils.pm
Labels: qe-core

#20545 Clean old settings from yam profiles
  data/yam/autoyast/autoyast_scc_up.xml
Labels: qe-yam

#20547 Quickfix for staging blackout
  schedule/staging/ext4@uefi-staging.yaml
Labels: qe-yam

#20543 Wait more time at grub phase for ppc64le-emu machine
  lib/transactional.pm
Labels: qe-core

#20552 Wipe audit logs after update on Micro
  tests/transactional/install_updates.pm
Labels: qe-security

#20478 Add migration testsuites for SLED15SP6 to SLED15SP7: AUTOYAST files
  data/yam/autoyast/support_images/sled_install_all_patterns.xml
  data/yam/autoyast/support_images/sled_install_default_patterns.xml
Labels: qe-yam

#20502 Remove hardcode password at data folder
  data/389ds/instance.inf
  data/autoyast_opensuse/autoyast_btrfs_luks1_separate_boot.xml
  data/autoyast_opensuse/autoyast_btrfs_luks2.xml
  data/autoyast_opensuse/autoyast_multi_btrfs.xml
  data/autoyast_opensuse/opensuse_leap.xml.ep
  data/autoyast_sle15/autoyast_btrfs_luks1_separate_boot.xml
  data/autoyast_sle15/autoyast_btrfs_luks2.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_multipath_lvm_encrypt_textmode_x86_64.xml
  data/kiwi/appliance.kiwi
  data/mitigation/xen/get_guest_ip.sh
  data/pam_test/pam.sh
  data/pam_test/pam_deprecated.sh
  data/security/autoyast/create_hdd_textmode_cc_aarch64.xml
  data/security/autoyast/create_hdd_textmode_cc_s390x.xml
  data/security/autoyast/create_hdd_textmode_cc_x86_64.xml
  data/security/autoyast/create_hdd_textmode_cc_x86_64_uefi.xml
  data/security/autoyast_sles15_stig.xml
  data/slepos/kiwi_build_image.sh
  data/yam/autoyast/home_encrypted.xml
  data/yam/autoyast/multi_btrfs.xml
  data/yam/autoyast/raid_encrypted_home_sle12sp5_x86_64.xml.ep
  data/yam/autoyast/raid_encrypted_home_x86_64.xml.ep
  data/yam/autoyast/resize_luks2.xml
  data/yam/autoyast/reuse-encrypted.xml
  lib/services/389ds_server.pm
  tests/console/pam.pm
  tests/cpu_bugs/kvm_guest_mitigations.pm
  tests/cpu_bugs/xen_domu_mitigation_test.pm
  tests/kiwi_images_test/kiwi_build_image.pm
Labels: qe-core

#20536 Add softfail for systemd-testkit version
  tests/console/start_systemd_testkit_offline.pm
Labels: qe-core

#20554 Reduce yaml files for raid scenarios
  schedule/yam/test_cases/raid_sle_gpt.yaml
  schedule/yast/raid/raid0_sle_gpt_prep_boot.yaml
  schedule/yast/raid/raid0_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid10_sle_gpt_prep_boot.yaml
  schedule/yast/raid/raid10_sle_gpt_uefi.yaml
  schedule/yast/raid/raid1_sle_gpt_prep_boot.yaml
  schedule/yast/raid/raid1_sle_gpt_uefi.yaml
  schedule/yast/raid/raid5_sle_gpt_prep_boot.yaml
  schedule/yast/raid/raid5_sle_gpt_uefi.yaml
  schedule/yast/raid/raid6_sle_gpt_prep_boot.yaml
  schedule/yast/raid/raid6_sle_gpt_uefi.yaml
  test_data/yast/raid/raid0_prep_boot_test_data_pvm.yaml
Labels: qe-yam

#20367 Test slem on powervm
  lib/main_micro_alp.pm
  tests/console/perl_bootloader.pm
  tests/transactional/rebootmgr.pm
Labels: qe-core

#20571 Ignore bsc#1230472 for journal_check
  data/journal_check/bug_refs.json
Labels: qe-core

#20566 Remove pipefail from wireguard test and improve test run time (poo#168589)
  tests/network/wireguard.pm
Labels: qe-core

#20574 Wait more time at grub phase for svirt-vmware70 machine
  lib/transactional.pm
Labels: qe-core

#20587 NFSv2 dropped also on 15-SP6
  lib/nfs_common.pm
Labels: Ready, qe-core

#20585 Skip update maintenance repo on base system
  tests/transactional/install_updates.pm
Labels: qe-yam

#20457 Reduce yaml files for skip_registration
  schedule/yam/test_cases/skip_registration.yaml
Labels: WIP, qe-yam

#20601 Worarkound missing test patch
  data/console/test_openssl_nodejs.sh
  data/qam/crypto_rsa_dsa.patch
  tests/console/openssl_nodejs.pm
Labels: Ready, qe-core

#20608 Worarkound missing test patch
  data/console/test_openssl_nodejs.sh
  tests/console/openssl_nodejs.pm
Labels: Ready, qe-core

#20599 Remove unecessary patterns for ppc64le all patterns migration
  lib/y2_installbase.pm
  tests/installation/logs_from_installation_system.pm
Labels: qe-yam

#20619 containers: Remove soft-failure for bsc#1232522
  tests/containers/buildah.pm
Labels: WIP

#20636 update_install: Fix two small issues
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#20629 Send_key home each time when deselect patterns
  lib/y2_installbase.pm
Labels: qe-yam

#20655 Quick fix for iscsi_client on SP6 (final version)
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#20660 evolution: Update tests for 15-SP6
  lib/thunderbird_common.pm
  tests/x11/evolution/evolution_prepare_servers.pm
  tests/x11/evolution/evolution_smoke.pm
Labels: Ready, qe-core

#20644 Change redis to valkey in Factory
  schedule/functional/extra_tests_textmode.yaml
  tests/console/valkey.pm
Labels: qe-core

#20663 evolution_prepare_servers: Remove workaound module
  tests/x11/evolution/evolution_prepare_servers.pm
Labels: Ready, qe-core

#20664 zypper_lifecycle: Add LTSS_ES exception
  tests/console/zypper_lifecycle.pm
Labels: Ready, qe-core

#20666 Pull test data from our own Git repository
  tests/security/ibmtss/ibmtss_basic_function.pm
Labels: qe-security

#20681 Use different sources for SLE and TW
  tests/security/ibmtss/ibmtss_basic_function.pm
Labels: qe-security

#20672 Boot Agama in OSD in s390x kvm
  tests/installation/bootloader_zkvm.pm
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#20433 Add migration testsuites for SLES15SP6 migration path of Texmode default pattern
  data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_default_patterns_x86_64.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_aarch64.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_x86_64.xml
Labels: qe-yam

#20691 Swap AY file extension to ep
  data/yam/autoyast/support_images/autoyast_sles15sp6_media_install_textmode_default_patterns_s390x.xml.ep
Labels: qe-yam

#20429 Boot from harddisk after agama installation
  lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
  schedule/yam/agama_from_usb.yaml
  tests/yam/agama/agama_boot_from_hdd.pm
Labels: qe-yam

#20690 Adapt version of regression testsuite to the package version
  tests/security/ibmtss/ibmtss_basic_function.pm
Labels: qe-security

#20699 zypper_lifecycle: Install new packages with solver_focus
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#20697 Install new packages due to dependency change
  tests/console/python3_pipx.pm
  tests/console/python3_setuptools.pm
Labels: qe-core

#20526 Allow certain snapshots to be labeled 'snapperd_data_t'
  lib/y2snapper_common.pm
Labels: Ready, qe-yam, qe-core

#20705 Use correct keylime configuration path on 15SP7
  tests/security/tpm2/keylime/keylime.pm
Labels: qe-security

#20710 Ignore failure on optional copy operation
  tests/security/tpm2/keylime/keylime.pm
Labels: qe-security

#20708 Increase timeout to 120s for nmcli device disconnect
  tests/microos/networkmanager.pm
Labels: Ready, qe-core
