Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-02, with the labels that each got.

#18555 Add temporary s390x condition for suseconnect
  lib/registration.pm
Labels: qe-yam

#18566 Press i key to unselect beta modules on Micro
  lib/registration.pm
Labels: Ready

#18557 Reduce yaml files for RAID1 test suite
  schedule/yast/raid/raid1_sle_gpt.yaml
  schedule/yast/raid/raid1_sle_gpt_prep_boot_pvm.yaml
  schedule/yast/raid/raid1_sle_gpt_uefi_aarch64.yaml
  test_data/yast/raid/raid1_gpt_test_data.yaml
  test_data/yast/raid/raid1_prep_boot_test_data_pvm.yaml
Labels: qe-yam

#18568 Remove select_modules_and_patterns+registration@s390x.yaml
  schedule/yast/select_modules_and_patterns+registration/select_modules_and_patterns+registration@s390x.yaml
Labels: qe-yam

#18573 Apply the glitch workaround in yast2_security
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam

#18577 Add wait_still_screen in change_desktop
  tests/installation/change_desktop.pm
Labels: qe-yam

#18584 Remove softfailure of bsc#950763
  lib/utils.pm
Labels: qe-yam

#18564 Remove softfail bsc#1073281: failed to start NIS/YP clients to NIS domain binder
  tests/console/yast2_nis.pm
Labels: qe-yam

#18597 Remove soft-failure of bsc#1142559 for yast2_keyboard test module
  tests/yast2_gui/yast2_keyboard.pm
Labels: qe-yam

#18598 welcome: Increase timeout on ppc64le
  tests/installation/welcome.pm
Labels: Ready, qe-core

#18599 partitioning_finish: Increase timeout for partitioning
  tests/installation/partitioning_finish.pm
Labels: Ready, qe-core

#18607 Install openldap2 packages in SLES15SP3 migration regression cases
  tests/migration/online_migration/zypper_patch.pm
  tests/migration/openldap_configuration.pm
  tests/update/patch_sle.pm
Labels: qe-yam

#18619 No need install openldap for regression 15sp3 jobs
  tests/migration/openldap_configuration.pm
Labels: qe-yam

#18611 Add schedule and condition for 15SP3 skip_registration
  schedule/yast/skip_registration/skip_registration_15sp3.yaml
  tests/installation/addon_products_sle.pm
Labels: qe-yam

#18638 updates_packagekit_gpk: Retry on update failure
  tests/update/updates_packagekit_gpk.pm
Labels: qe-core

#18663 Edit skip_registration schedule
  schedule/yast/skip_registration/skip_registration_15sp3.yaml
Labels: qe-yam

#18668 Don't install pattern 'alp_elemental_client' on slem6.0
  tests/microos/patterns.pm
Labels: qe-core

#18676 Edit skip_registration schedule
  schedule/yast/skip_registration/skip_registration_15sp3.yaml
Labels: qe-yam

#18650 Ignore bsc#1195060 from data/journal_check/bug_refs.json
  data/journal_check/bug_refs.json
  tests/console/journal_check.pm
Labels: qe-yam

#18653 Update profile for uefi machine
  data/autoyast_qam/12-common_base_installation.xml.ep
Labels: Ready, qe-core

#18695 Create a default YAML schedule for aarch64
  schedule/yast/sle/flows/default_aarch64.yaml
  schedule/yast/sle/guided_ext4/guided_ext4_aarch64.yaml
  schedule/yast/sle/guided_xfs/guided_xfs.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_aarch64.yaml
Labels: qe-yam

#18679 containers: Refactor firewall tests
  lib/main_containers.pm
  tests/containers/docker_firewall.pm
  tests/containers/firewall.pm
  tests/containers/podman_firewall.pm
Labels: WIP

#18722 Quick fix for missing pattern installation on aarch64
  schedule/yast/select_modules_and_patterns/select_modules_and_patterns_aarch64.yaml
Labels: qe-yam

#18715 Add <kdump> section in autoyast_sle-micro_updates.xml.ep
  data/autoyast_sle15/autoyast_sle-micro_updates.xml.ep
Labels: qe-yam

#18728 Containers: netavark shall skip install of pkg present
  tests/containers/podman_netavark.pm
Labels: WIP

#18725 Accept default disk selection for guided_btrfs@ipmi
  schedule/yast/sle/guided_btrfs/guided_btrfs_ipmi.yaml
Labels: qe-yam

#18705 Add key setps for s390x qemu tests
  schedule/functional/extra_tests_qemu.yaml
Labels: qe-core

#18710 Quick fix for installer_extended on aarch64
  schedule/yast/installer_extended/installer_extended_aarch64.yaml
Labels: qe-yam

#18609 Reduce number of YAML files for ha_textmode_skip_reg*
  schedule/yam/test_cases/ha_textmode_skip_registration.yaml
  schedule/yam/test_cases/ha_textmode_skip_registration_minimal_base.yaml
  schedule/yast/textmode/ha_textmode_skip_registration.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_minimal_base.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_minimal_base_aarch64.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_minimal_base_pvm.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_pvm.yaml
  schedule/yast/textmode/ha_textmode_skip_registration_s390x.yaml
  test_data/yam/skip_registration/default_repos_ha_textmode.yaml
Labels: qe-yam

#18741 Install the latest dpdk packages on sle15sp6
  tests/console/dpdk.pm
Labels: qe-core

#18718 Update perl-bootloader log test
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core

#18750 Fix availbale disk space check and md name
  data/qam/mdadm.sh
Labels: Ready, qe-core

#18768 Add autoyast profiles for hpc15sp3 installation
  data/yam/autoyast/support_images/hpc15sp3_install_development_node_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/hpc15sp3_install_management_server_default_patterns_aarch64.xml
  data/yam/autoyast/support_images/hpc15sp3_install_textmode_default_patterns_x86_64.xml
Labels: qe-yam

#18678 Move the php tests to stack_tests_php testsuite
  schedule/qam/common/mau-webserver.yaml
  schedule/qam/common/stack_tests_php.yaml
  tests/console/php_version.pm
Labels: qe-core

#18769 Uninstall package libopenssl-1_1-devel before migration
  lib/migration.pm
  tests/migration/online_migration/zypper_patch.pm
  tests/update/patch_sle.pm
Labels: qe-yam
