Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-04, with the labels that each got.

#18983 Schedule libgit2 test
  schedule/functional/extra_tests_textmode.yaml
Labels: qe-core

#18995 Add default schedule for s390x kvm on textmode
  schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
Labels: qe-yam

#19014 Fix leap kde test switch x11 console issue
  lib/utils.pm
Labels: qe-yam

#18936 Add rollback after slem migration
  lib/version_utils.pm
  schedule/sle-micro/migration_with_scc_proxy.yaml
  tests/microos/rollback.pm
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#19039 Extend timeout to get the expected needle
  lib/YaST/NetworkSettings/NetworkCardSetup/VLANAddressTab.pm
Labels: qe-yam

#18985 Add python3 in AutoYaST profiles for > SLE 15 SP5 where not is default
  data/yam/autoyast/bug-872532_ix64ph1069.xml
  data/yam/autoyast/bug-876411_btrfs_h5_autoinst.xml
  data/yam/autoyast/bug-877438_ix64ph1029.xml
  data/yam/autoyast/bug-879147_autoinst.xml
  data/yam/autoyast/bug-887126_autoinst.xml
  data/yam/autoyast/bug-887653_autoinst_jy-snapshot.xml
  data/yam/autoyast/create_hdd_gnome_aarch64.xml
  data/yam/autoyast/create_hdd_gnome_allpatterns_aarch64.xml
  data/yam/autoyast/create_hdd_gnome_disabled_firewall.xml
  data/yam/autoyast/create_hdd_gnome_ppc64le.xml
  data/yam/autoyast/create_hdd_gnome_s390x.xml
  data/yam/autoyast/create_hdd_gnome_sdk_allpatterns_aarch64.xml
  data/yam/autoyast/create_hdd_gnome_sdk_allpatterns_s390x.xml
  data/yam/autoyast/create_hdd_gnome_x86_64.xml
  data/yam/autoyast/create_hdd_gnome_x86_64_uefi.xml
  data/yam/autoyast/create_hdd_textmode_aarch64.xml
  data/yam/autoyast/create_hdd_textmode_powervm.xml
  data/yam/autoyast/create_hdd_textmode_s390x.xml
  data/yam/autoyast/create_hdd_textmode_x86_64.xml
  data/yam/autoyast/disk_as_md_member.xml
  data/yam/autoyast/disk_as_pv.xml
  data/yam/autoyast/error.xml
  data/yam/autoyast/ext4.xml
  data/yam/autoyast/firstboot.xml
  data/yam/autoyast/gnome.xml
  data/yam/autoyast/home_encrypted.xml
  data/yam/autoyast/lvm.xml
  data/yam/autoyast/multi_btrfs.xml
  data/yam/autoyast/multipath.xml
  data/yam/autoyast/nfs_share.xml
  data/yam/autoyast/resize_luks2.xml
  data/yam/autoyast/reuse-encrypted.xml
  data/yam/autoyast/sles_zvm.xml
  data/yam/autoyast/tftp.xml
Labels: qe-yam

#19038 Add libgit2 test on ppc64le/s390x
  schedule/functional/extra_tests_textmode.yaml
  tests/console/libgit2.pm
Labels: qe-core

#19047 vnc_two_passwords: Increase vnc_password_dialog timeout
  tests/x11/vnc_two_passwords.pm
Labels: Ready, qe-core

#19055 Use generic main_common::is_updates_tests
  lib/repo_tools.pm
Labels: Ready, qe-core

#19052 containers: Add missing dependency for podman upstream tests
  tests/containers/podman_integration.pm
Labels: WIP

#19065 Fix 12-SP3 ay update repo
  data/autoyast_qam/12-common_base_installation.xml.ep
Labels: Ready, qe-core

#19070 Add white list to bug_refs for slem 6.0
  data/journal_check/bug_refs.json
Labels: qe-core

#19023 Update perl-Bootloader test for sle micro
  lib/main_micro_alp.pm
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core

#19092 Replace reboot process for slem rollback
  tests/microos/rollback.pm
Labels: WIP, qe-yam

#19090 Add mau-filesystem on s390x
  schedule/qam/12-SP5/mau-filesystem.yaml
  tests/console/lvm.pm
Labels: qe-core

#19086 Create 15-SP6 files
  data/autoyast_qam/15-SP6_installation.xml.ep
  data/autoyast_qam/15-SP6_installtest.xml.ep
  schedule/qam/15-SP6/lvm_thin_provisioning.yaml
  schedule/qam/15-SP6/mau-extratests-phub.yaml
  schedule/qam/15-SP6/mau-filesystem.yaml
  schedule/qam/15-SP6/mau-filesystem@zkvm.yaml
  schedule/qam/15-SP6/mau-userspace.yaml
  schedule/qam/15-SP6/powerpc-utils.yaml
  schedule/qam/15-SP6/qam-allpatterns.yaml
  schedule/qam/15-SP6/qam-create_hdd_ha_textmode.yaml
  schedule/qam/15-SP6/qam-create_hdd_sle_sap_gnome.yml
  schedule/qam/15-SP6/qam-create_hdd_sles4sap_gnome.yml
  schedule/qam/15-SP6/qam-gnome.yaml
  schedule/qam/15-SP6/qam-minimal-RAID1.yaml
  schedule/qam/15-SP6/qam-minimal-base-installation-ay.yaml
  schedule/qam/15-SP6/qam-minimal-base.yaml
  schedule/qam/15-SP6/qam-regression-firefox.yaml
  schedule/qam/15-SP6/qam-regression-firefox_fips.yaml
  schedule/qam/15-SP6/qam-regression-installation.yaml
  schedule/qam/15-SP6/qam-regression-other_fips.yaml
  schedule/qam/15-SP6/qam-sle_sles4sap_scc_gnome_netweaver_cli.yml
  schedule/qam/15-SP6/qam-sle_sles4sap_scc_gnome_sapconf.yml
  schedule/qam/15-SP6/qam-sle_sles4sap_scc_gnome_saptune.yml
  schedule/qam/15-SP6/qam-sles4sap_wmp_hana_node1.yaml
  schedule/qam/15-SP6/qam-sles4sap_wmp_hana_node2.yaml
  schedule/qam/15-SP6/qam-textmode.yaml
  schedule/qam/common/mau-extratests-desktop.yaml
  schedule/qam/common/mau-extratests1.yaml
  schedule/qam/common/mau-extratests2.yaml
  schedule/qam/common/mau-webserver.yaml
Labels: Ready, qe-core

#19103 Replace addon_others with addon_products in create_hdd_maintenance.xml.ep
  data/yam/autoyast/support_images/create_hdd_maintenance.xml.ep
Labels: qe-yam

#18993 Add schedule for migration in MU
  schedule/migration/migration_autoyast.yaml
Labels: qe-yam

#18756 Provide migration from SLES 12 SP5 to SLES 15 SP4 in aggregated updates
  schedule/migration/migration_autoyast.yaml
  schedule/yast/maintenance/autoyast_create_hdd_maintenance.yaml
Labels: qe-yam

#18796 Remove private_key qesap terraform variables
  data/sles4sap/qe_sap_deployment/mr_test_azure_uri.yaml
  data/sles4sap/qe_sap_deployment/mr_test_ec2.yaml
  data/sles4sap/qe_sap_deployment/mr_test_ec2_product.yaml
  data/sles4sap/qe_sap_deployment/mr_test_gcp.yaml
  data/sles4sap/qe_sap_deployment/qesap_aws.yaml
  data/sles4sap/qe_sap_deployment/qesap_aws_fencing.yaml
  data/sles4sap/qe_sap_deployment/qesap_aws_sapconf.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_fencing_msi.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_fencing_spn.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_roles.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_sapconf.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_sapconf_no_reg.yaml
  data/sles4sap/qe_sap_deployment/qesap_azure_uri.yaml
  data/sles4sap/qe_sap_deployment/qesap_gcp.yaml
  data/sles4sap/qe_sap_deployment/qesap_gcp_fencing.yaml
  data/sles4sap/qe_sap_deployment/qesap_gcp_sapconf.yaml
  data/sles4sap/qe_sap_deployment/sles4sap_aws_generic.yaml
  data/sles4sap/qe_sap_deployment/sles4sap_azure_generic.yaml
  data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_maintenance.yaml
  data/sles4sap/qe_sap_deployment/sles4sap_azure_generic_uri.yaml
  data/sles4sap/qe_sap_deployment/trento_azure.yaml
  tests/sles4sap/publiccloud/qesap_terraform.pm
  tests/sles4sap/qesapdeployment/configure.pm
Labels: WIP

#19123 Remove scc_deregister from create_hdd_maintenance_desktop
  schedule/migration/migration_autoyast.yaml
  schedule/yast/maintenance/autoyast_create_hdd_maintenance.yaml
Labels: qe-yam

#19125 Remove at-spi* packages from profile
  data/yam/autoyast/bug-887126_autoinst.xml
Labels: qe-yam

#19130 Remove desktop addon from create_hdd_textmode
  data/autoyast_sle15/create_hdd/create_hdd_textmode_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_textmode_s390x.xml
Labels: Ready, qe-core

#19127 Use zdup to do update stack job migration testing
  schedule/migration/migration_zdup_updatestack.yaml
Labels: qe-yam

#19140 Add retry for samba dns resolve test
  tests/network/samba/samba_adcli.pm
Labels: Ready, qe-core

#19134 Update chrome test due to new UI
  tests/x11/chrome.pm
Labels: Ready, qe-core

#19145 Reset console for sles15sp3 MU migration
  schedule/migration/migration_autoyast.yaml
Labels: qe-yam

#19147 Add retry for dns resolve test
  tests/console/dns_srv.pm
Labels: qe-core

#19152 Revisit soft-failure bsc1192331
  lib/utils.pm
Labels: qe-yam

#19160 Remove server-applications module from SLED
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19122 Verify cluster health at the end
  lib/sles4sap_publiccloud.pm
  tests/sles4sap/publiccloud/hana_sr_takeover.pm
  tests/sles4sap/publiccloud/hana_sr_test_secondary.pm
Labels: WIP

#19150 Ship libnfsmap1 in place of nfsidmap on sle15sp6
  tests/network/autofs_client.pm
  tests/network/autofs_server.pm
Labels: Ready, qe-core

#19166 Fix package dependency issue for libssh test
  tests/console/libssh.pm
Labels: Ready, qe-core

#19002 Use default partition for powerVM
  data/yam/autoyast/create_hdd_textmode_powervm.xml
Labels: qe-yam

#19168 Fix timing issue on slem NM tests
  tests/microos/networkmanager.pm
Labels: Ready, qe-core

#19175 pc: Change permissions of log files so we can copy them
  lib/publiccloud/instance.pm
Labels: WIP

#19177 Add rmt-server-pubcloud conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19167 Deregister dropped module for maintenance migration
  tests/console/scc_cleanup_reregister.pm
Labels: qe-yam

#19182 Add libcontainers-openSUSE-policy conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19207 containers: Add skopeo upstream tests
  lib/main_containers.pm
  tests/containers/podman_integration.pm
  tests/containers/skopeo_integration.pm
Labels: WIP

#19205 Fix network configuration on s390x for slem NM test
  tests/microos/networkmanager.pm
Labels: WIP, qe-core

#19191 Enhance migration code in maintenance
  schedule/migration/migration_autoyast.yaml
  tests/console/scc_cleanup_reregister.pm
  tests/yam/migration/reboot_to_boot_screen.pm
  tests/yam/migration/setup_registration.pm
  tests/yam/migration/setup_upgrade.pm
Labels: qe-yam

#19212 Enable source pool if no updated source package available
  tests/console/openssl_nodejs.pm
Labels: Ready, qe-core

#19219 Skip puthon39 test on 15-SP5, no pip package
  tests/console/python3_setuptools.pm
Labels: Ready, qe-core
