Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-12, with the labels that each got.

#20716 Include agama config attached to the job in openQA
  lib/Yam/Agama/agama_base.pm
Labels: qe-yam

#20715 Update slem 6.2 journal log white list
  data/journal_check/bug_refs.json
Labels: qe-core

#20648 Add migration testsuites for SLES15SP6 migration path of Gnome role with all patterns
  data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_aarch64.xml
  data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp6_install_gnome_all_patterns_x86_64.xml
Labels: qe-yam

#20626 Fix sporadic fails in disable_boot_menu_timeout
  lib/Installation/InstallationSettings/InstallationSettingsPage.pm
Labels: qe-yam

#20725 Cleanup create_hdd_migration_ppc64le.ep
  data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
Labels: qe-yam

#20729 Update a slem autoyast profile to get update repo from scc only
  data/autoyast_sle15/autoyast_sle-micro_updates.xml.ep
Labels: qe-yam

#20742 Reshape AgamaUpAndRunning sync point
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Distribution/Sle/AgamaDevel.pm
  lib/Yam/Agama/Pom/AgamaUpAndRunningOpensusePage.pm
  lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
  lib/Yam/Agama/Pom/AgamaUpAndRunningSlePage.pm
Labels: qe-yam

#20748 Need to switch to 'repo to be tested for next snapshot'
  lib/main_micro_alp.pm
Labels: qe-core

#20746 Remove hardcode password for first user and the root passwords in Agama unattended jsonnet profiles
  data/yam/agama/auto/alp_tumbleweed.jsonnet
  data/yam/agama/auto/default_leap.json
  data/yam/agama/auto/default_sle.json
  data/yam/agama/auto/default_tumbleweed.json
  data/yam/agama/auto/default_tumbleweed.sh
  data/yam/agama/auto/gnome_leap.json
  data/yam/agama/auto/gnome_tumbleweed.json
  data/yam/agama/auto/leap16.json
  data/yam/agama/auto/leap16.sh
Labels: qe-yam

#20759 Change powerVM autoyast boot timeout to -1
  data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
Labels: qe-yam

#20756 Fix SMT autoyast profile for 15sp7 spvm
  data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
  tests/migration/online_migration/yast2_migration.pm
Labels: qe-yam

#20707 Openqa cannot resize powerVM disk size since it is not QEMU backend
  tests/microos/image_checks.pm
Labels: qe-core

#20766 Create new lynis baseline for 15-SP7
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-aarch64-gnome
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-aarch64-textmode
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-ppc64le-textmode
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-s390x-gnome
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-s390x-textmode
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-x86_64-gnome
  data/lynis/baseline-lynis-audit-system-nocolors-15-SP7-x86_64-textmode
  schedule/security/lynis/lynis_create_baseline.yaml
  tests/security/lynis/lynis_create_baseline.pm
Labels: qe-security

#20776 Quickfix double redirection in upload_agama_logs
  lib/Yam/Agama/agama_base.pm
Labels: qe-yam

#20780 Add networkmanager test for slem on powerVM
  tests/microos/networkmanager.pm
Labels: qe-core

#20791 Quickfix for upload_agama_logs
  lib/Yam/Agama/agama_base.pm
Labels: qe-yam

#20788 Boot Agama in OSD in PowerVM
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/bootloader_pvm.pm
  lib/bootloader_setup.pm
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#20787 validate_packages_and_patterns: Get sles-ltss-release update repo
  tests/console/validate_packages_and_patterns.pm
Labels: Ready, qe-core

#20792 Ignore bsc#1231457 for journal_check
  data/journal_check/bug_refs.json
Labels: qe-core

#20814 Make git test not fatal
  tests/console/gpg.pm
Labels: qe-security

#20816 Quickfix for agama_auto password problem
  data/yam/agama/auto/default_leap.json
  data/yam/agama/auto/default_sle.json
  data/yam/agama/auto/default_tumbleweed.json
  data/yam/agama/auto/gnome_leap.json
  data/yam/agama/auto/gnome_tumbleweed.json
  data/yam/agama/auto/leap16.json
Labels: qe-yam

#20819 Bump timeout for refreshing repos in Agama unattended
  lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
Labels: qe-yam

#20812 Drop bluetooth service in aws ay profile
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_aarch64.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_ppc64le.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_s390x.xml
  data/autoyast_sle15/create_hdd/create_hdd_pcm_aws_x86_64.xml
Labels: Ready, qe-core

#20820 Install SLES for SAP for agama testing
  data/yam/agama/auto/default_sap.json
  data/yam/agama/auto/default_sap_no_scc.json
  test_data/yam/agama_sap.yaml
Labels: qe-yam

#20813 Increase timeout in transactional-update install
  tests/microos/cockpit_service.pm
  tests/microos/patterns.pm
Labels: Ready, qe-core

#20835 Fix serial console settings for agama install
  tests/installation/ipxe_install.pm
Labels: qe-core

#20834 Ensure only one agama.auto in bootloader parameters
  lib/bootloader_setup.pm
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-yam

#20844 Poo#174574 add s390x full-qu schedule
  schedule/yast/sle/flows/default_s390x_kvm_flavor_full.yaml
Labels: qe-security

#20846 Introduce retry mechanism for IMA counting of measurements
  tests/security/ima/ima_kernel_cmdline_hash.pm
  tests/security/ima/ima_kernel_cmdline_template.pm
  tests/security/ima/ima_measurement.pm
Labels: qe-security

#20686 Ensure dialog Password_needed is reached
  tests/yast2_gui/yast2_security.pm
Labels: qe-yam

#20839 Retrieve logs when failing to sync during boot
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#20851 Avoid auto installation conflict with dasd format on zVM
  tests/installation/bootloader_s390.pm
Labels: qe-yam

#20856 Ensure SELINUX is enabled if expected
  tests/security/selinux/selinux_setup.pm
Labels: qe-security

#20829 Use posts script to enable sshd
  data/yam/agama/auto/default_sle.jsonnet
  data/yam/agama/auto/default_sle_no_scc.jsonnet
Labels: qe-yam

#20850 Add Agama installation support for powerVM
  lib/bootloader_pvm.pm
  lib/bootloader_setup.pm
  tests/installation/agama_reboot.pm
Labels: qe-core

#20863 Ensure match reboot popup for autoyast test on powerVM
  tests/autoyast/installation.pm
Labels: qe-yam

#20873 Fix remote_vnc_controller can't boot up issue
  lib/opensusebasetest.pm
Labels: qe-yam

#20872 Ensure match reboot for autoyast test on yast X86_64
  data/yam/autoyast/resize_luks2.xml
  tests/autoyast/installation.pm
Labels: qe-yam

#20877 Ignore known error of Spectre-V2-LFENCE for slem 5.1
  data/journal_check/bug_refs.json
Labels: qe-yam
