Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-09, with the labels that each got.

#20103 Workaround for slem tests on ppc64le
  lib/opensusebasetest.pm
  tests/transactional/host_config.pm
Labels: qe-core

#20102 Move Public Cloud common ssh opts to ~/.ssh/config
  data/publiccloud/ssh_config
  lib/publiccloud/instance.pm
  lib/publiccloud/provider.pm
  lib/publiccloud/utils.pm
  tests/publiccloud/prepare_instance.pm
Labels: Verification-Runs-needed

#20119 Reboot if needed after installing packages on Micro
  lib/services/sshd.pm
  lib/ssh_crypto_policy.pm
Labels: qe-security

#19951 Created a test module to check libjpeg-turbo version
  data/imagemagick/lizard.jpeg
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_phub.yaml
  schedule/qam/15-SP6/mau-extratests-phub.yaml
  tests/console/libjpeg_turbo.pm
Labels: Ready, qe-core

#20113 Create page object for reboot screen in agama
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Yam/Agama/Pom/RebootPage.pm
  schedule/yam/agama.yaml
  test_data/yam/agama_tumbleweed.yaml
  tests/yam/agama/agama.pm
  tests/yam/agama/auto.pm
Labels: qe-yam

#20110 Reduce yaml files for cryptlvm+cancel_existing
  schedule/yam/test_cases/cryptlvm+cancel_existing.yaml
  schedule/yast/encryption/cryptlvm+cancel_existing.yaml
  schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
  test_data/yast/encryption/cryptlvm+cancel_existing_ppc64le.yaml
Labels: qe-yam

#20109 Added new DNS server address configuration
  tests/microos/networkmanager.pm
Labels: qe-core

#20145 Make sure only one package per line for installing
  tests/console/install_packages.pm
  tests/console/qam_zypper_patch.pm
Labels: qe-core

#20154 perl_bootloader: Increase bootloder timeout
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core

#20159 zypper_patch: Use force resolution
  tests/console/qam_zypper_patch.pm
Labels: Ready, qe-core

#20173 Add milestone flag for zypper_migration
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#20177 Fix console selection in Agama
  lib/susedistribution.pm
Labels: qe-yam

#20170 Upload all /var/log/pk_backend_zypp* logs
  lib/opensusebasetest.pm
Labels: Ready, qe-core

#20178 Add missing gnutls package to nested image used to test swtpm
  tests/security/create_swtpm_hdd/build_hdd.pm
  tests/security/swtpm/swtpm_env_setup.pm
Labels: qe-security

#20169 Move Public Cloud ssh opts to CLI in HanaSR tests
  lib/publiccloud/instance.pm
  lib/sles4sap_publiccloud.pm
  lib/sles4sap_publiccloud_basetest.pm
  t/12_sles4sap_publicccloud.t
  tests/sles4sap/publiccloud/qesap_terraform.pm
Labels: WIP, qe-sap-ha

#20187 Add missed packages for wicked tests
  data/autoyast_sle15/autoyast_wicked_aarch64.xml
  data/autoyast_sle15/autoyast_wicked_ppc64le.xml
Labels: qe-core

#20192 Ignore journal log: kernel: SED: plpks not available
  data/journal_check/bug_refs.json
Labels: qe-core

#20081 Reduce yaml for activate_encrypted_volume
  schedule/yast/encryption/activate_encrypted_volume+force_recompute_pvm.yaml
  schedule/yast/encryption/activate_encrypted_volume+import_users_pvm.yaml
Labels: qe-yam

#20190 Create Agama installation for full encryption
  schedule/yam/agama_full_disk_encryption.yaml
  tests/yam/agama/import_agama_profile.pm
  tests/yam/agama/patch_agama_tests.pm
Labels: qe-yam

#20216 Upload logs for agama even test passed
  lib/Yam/Agama/agama_base.pm
Labels: qe-yam

#20210 Add reboot scenario after raid installation
  schedule/yam/test_cases/raid0_sle_gpt.yaml
  schedule/yam/test_cases/raid_sle_gpt.yaml
Labels: qe-core

#20222 Recategory function for agama logs
  lib/Yam/Agama/agama_base.pm
Labels: qe-yam

#20227 Replace sleep() with stdout checking logic
  tests/security/apparmor/aa_notify.pm
Labels: qe-security

#20199 Integrate the web automation script for agama in openQA
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Yam/Agama/Pom/RebootPage.pm
  lib/Yam/Agama/Pom/RebootTextmodePage.pm
  schedule/yam/agama_s390x.yaml
  tests/yam/agama/agama.pm
Labels: qe-yam

#20228 Upload logs for agama even test passed
  lib/Yam/Agama/agama_base.pm
  schedule/yam/agama.yaml
  schedule/yam/agama_auto.yaml
  schedule/yam/agama_auto_dolomite_select_installation_device.yaml
  schedule/yam/agama_auto_tumbleweed.yaml
  schedule/yam/agama_auto_tumbleweed_select_installation_device.yaml
  schedule/yam/agama_s390x.yaml
  schedule/yam/control_center_container.yaml
  tests/yam/agama/agama.pm
  tests/yam/agama/agama_auto.pm
  tests/yam/validate/validate_first_user.pm
Labels: qe-yam

#20236 Make stable agama in ppc64le by processing grub2
  schedule/yam/agama.yaml
  tests/yam/agama/agama_grub2.pm
Labels: qe-yam

#20248 Check FIPS vars in the correct way or bailout
  tests/fips/fips_setup.pm
Labels: qe-security

#20066 Adjust test to use new package name for Tumbleweed
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core

#20265 Remove useless check for variables
  tests/fips/fips_setup.pm
Labels: qe-security

#20268 Update version check to include SP7 and micro6.1
  tests/console/perl_bootloader.pm
Labels: Ready, qe-core

#20273 Add softfail for bsc#1205931 on sle_micro 6.0
  data/journal_check/bug_refs.json
Labels: qe-yam

#20270 Use serial terminal for testing squid reverse proxy
  tests/fips/squid/squid_reverse_proxy.pm
Labels: qe-security

#20275 Fix Agama: add dmesg before and after assert_script_run
  tests/yam/agama/import_agama_profile.pm
  tests/yam/agama/patch_agama_tests.pm
Labels: qe-yam

#20286 Update test repo setup/teardown
  tests/fips/libica_upstream_testsuite.pm
Labels: qe-security

#20298 All patterns
  lib/Tomcat/ModjkTest.pm
  lib/y2_installbase.pm
  schedule/functional/create-hdd-allmodules-allpatterns.yaml
Labels: Ready, qe-core

#20294 Added packagehub related test modules to extra_tests_textmode_phub job
  lib/main_common.pm
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_phub.yaml
  tests/console/libgit2.pm
  tests/network/cifs.pm
  tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
Labels: qe-core

#20291 Introduce smoke tests for PCI Utils
  schedule/functional/extra_tests_textmode.yaml
  schedule/qam/common/mau-extratests2.yaml
  tests/console/pciutils.pm
Labels: Ready, qe-core

#20269 Open receive update flag for autoupgrade profile.
  data/yam/autoyast/autoyast_scc_up.xml
Labels: qe-yam

#20293 Adapt distri pattern for Leap 16.0
  lib/Distribution/Sle/16Latest.pm
  lib/DistributionProvider.pm
Labels: qe-yam

#20301 Boot agama in OSD in architectures using qemu
  data/yam/agama/auto/default_sle.json
Labels: qe-yam

#20311 Load pciutils test before year_2038_detection
  schedule/functional/extra_tests_textmode.yaml
  schedule/qam/common/mau-extratests2.yaml
Labels: qe-core

#20308 Remove soft-failure bsc#1206132
  lib/YaST/workarounds.pm
  tests/iscsi/iscsi_client.pm
Labels: qe-yam

#20238 Exclude yast2 modules from qam-minimal-full
  schedule/qam/common/qam-minimal-full.yaml
Labels: Ready, qe-core

#20316 Add env var for agama product selection
  tests/yam/agama/agama.pm
Labels: qe-yam

#20317 zypper_lifecycle: Workaround end of support package
  tests/console/zypper_lifecycle.pm
Labels: Ready, qe-core
