Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-07, with the labels that each got.

#19629 update_install: Add systemtap-sdt-devel conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19622 Reduce yaml files for ha_textmode
  schedule/yam/test_cases/ha_textmode.yaml
  schedule/yast/textmode/ha_textmode_aarch64.yaml
  schedule/yast/textmode/ha_textmode_pvm.yaml
  schedule/yast/textmode/ha_textmode_s390x.yaml
Labels: qe-yam

#19614 Reduce yaml files for ha_textmode_minimal_base
  schedule/yam/test_cases/ha_textmode_minimal_base.yaml
  schedule/yast/textmode/ha_textmode_minimal_base.yaml
  schedule/yast/textmode/ha_textmode_minimal_base_aarch64.yaml
  schedule/yast/textmode/ha_textmode_minimal_base_pvm.yaml
Labels: qe-yam

#19604 Remove soft failure bsc#1176901
  lib/services/registered_addons.pm
Labels: qe-yam

#19631 Change record_soft_failure to record_info
  tests/console/yast2_lan_device_settings.pm
Labels: qe-yam

#19547 Upgrade SLES12SP5 MU released to SLES15SP6 MU unreleased
  data/yam/autoyast/autoupgrade_with_maintenance_unreleased_updates.xml.ep
  data/yam/autoyast/support_images/sles12sp5_install_with_scc_addons_x86_64.xml.ep
  schedule/yast/maintenance/autoupgrade_sles12sp5_to_sles15spx_maintenance.yaml
  tests/migration/prepare_maintenance_repos.pm
  tests/migration/prepare_scc_addons.pm
Labels: qe-yam

#19644 Reduce yaml schedule files for addon_extensions_http_ftp cases
  schedule/yam/test_cases/addon_extensions_http_ftp.yaml
  schedule/yast/addon_extensions_http_ftp/addon_extensions_http_ftp@pvm.yaml
  schedule/yast/addon_extensions_http_ftp/addon_extensions_http_ftp@s390x.yaml
Labels: qe-yam

#19647 Handle new signing key for NVIDIA repo
  tests/console/qam_zypper_patch.pm
Labels: qe-core

#19646 Revert suseconnect-ng fix for s390x
  lib/registration.pm
Labels: qe-yam

#19660 Reduce yaml files for btrfs+warnings
  schedule/yam/test_cases/btrfs+warnings.yaml
  schedule/yast/btrfs/btrfs+warnings.yaml
  schedule/yast/btrfs/btrfs+warnings@s390x.yaml
  schedule/yast/btrfs/btrfs+warnings_aarch64.yaml
  schedule/yast/btrfs/btrfs+warnings_x86_64.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
Labels: qe-yam

#19589 Automate scenario with home encrypted with RAID disks directly formatted
  data/yam/autoyast/create_hdd_textmode_x86_64_raid_encrypted_home.xml
  schedule/yast/autoyast_create_hdd_textmode_raid_encrypted_home.yaml
  test_data/yast/raid/raid1_encrypted_home.yaml
  tests/console/validate_raid_encrypt_home.pm
Labels: qe-yam

#19663 Fix mount point value for raid encrypted home
  tests/console/validate_raid_encrypt_home.pm
Labels: qe-yam

#19664 Update yaml file name for raid encryted home
  data/yam/autoyast/raid_encrypted_home_x86_64.xml
  schedule/yast/autoyast_raid_encrypted_home.yaml
Labels: qe-yam

#19665 Check mdadm version
  tests/console/mdadm.pm
Labels: Ready, qe-core

#19636 Update the code of disabling installation repos for s390x
  lib/migration.pm
Labels: qe-yam

#19669 Add version check after migration in SL Micro
  lib/transactional.pm
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#19679 Update is not being installed workaround
  tests/update/updates_packagekit_gpk.pm
  tests/update/updates_packagekit_kde.pm
Labels: Ready, qe-core

#19672 Add testsuite of raid_encrypted_home
  data/yam/autoyast/raid_encrypted_home_x86_64.xml.ep
  schedule/yast/autoyast_raid_encrypted_home.yaml
Labels: qe-yam

#19666 Reduce yaml files for crypt_no_lvm and cryptlvm for powerVM
  schedule/yam/test_cases/crypt_no_lvm.yaml
  schedule/yam/test_cases/cryptlvm.yaml
  schedule/yast/encryption/crypt_no_lvm_pvm.yaml
  schedule/yast/encryption/cryptlvm_sle_15_spvm.yaml
Labels: qe-yam

#19556 Add new installation test without self updates
  data/yam/autoyast/sles15sp5_gnome_unregistered_no_self_update.xml.ep
  schedule/yast/autoyast/sles15sp5_gnome_unregistered_no_self_update.yaml
Labels: qe-yam

#19710 Skip update-test check on 15SP6
  tests/console/validate_packages_and_patterns.pm
Labels: Ready, qe-core

#19719 update_install: Disable update repos after conflict install
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19721 update_install: Add nvidia conflicts
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19724 update_install: Add nvidia aarch64 conflicts
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19728 update_install: Add xen-tools-domU conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19675 Reduce yaml files for lvm-encrypt-separate-boot
  schedule/yam/test_cases/lvm_encrypt_separate_boot.yaml
  schedule/yast/encryption/lvm_encrypt_separate_boot.yaml
  schedule/yast/encryption/lvm_encrypt_separate_boot@s390x.yaml
  schedule/yast/encryption/lvm_encrypt_separate_boot_aarch64.yaml
  schedule/yast/encryption/lvm_encrypt_separate_boot_x86_64.yaml
  schedule/yast/sle/flows/default_aarch64.yaml
  schedule/yast/sle/flows/default_ppc64le.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
  schedule/yast/sle/flows/default_x86_64.yaml
Labels: qe-yam

#19634 Reduce yaml schedule files for guided_xfs cases
  schedule/yam/test_cases/guided_xfs.yaml
  schedule/yast/sle/guided_xfs/guided_xfs@s390x_kvm.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_aarch64.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_s390x_zvm.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_svirt_xen_hvm.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_svirt_xen_pv.yaml
  schedule/yast/sle/guided_xfs/guided_xfs_x86_64.yaml
  tests/console/validate_partition_table.pm
Labels: qe-yam

#19727 Remove xorg-x11-Xvnc from autoyast file
  data/yam/autoyast/sles15sp5_gnome_unregistered_no_self_update.xml.ep
Labels: qe-yam

#19708 Move single yaml test suite to yaml test case path
  schedule/yam/test_cases/detect_yast2_failures.yaml
  schedule/yam/test_cases/gnome_install_from_source.yaml
  schedule/yam/test_cases/home_encrypted.yaml
  schedule/yam/test_cases/iscsi_ibft.yaml
  schedule/yam/test_cases/lvm+resize_lv.yaml
  schedule/yam/test_cases/nvme.yaml
  schedule/yam/test_cases/offline_install+skip_registration.yaml
  schedule/yam/test_cases/remote_ssh_controller_sle15.yaml
  schedule/yam/test_cases/remote_ssh_target_ftp_sle15.yaml
  schedule/yam/test_cases/remote_vnc_controller.yaml
  schedule/yam/test_cases/remote_vnc_target_nfs.yaml
  schedule/yam/test_cases/repo_inst.yaml
  schedule/yam/test_cases/rmt_server_install.yaml
  schedule/yam/test_cases/sles+sdk+proxy_SCC_via_YaST_pvm.yaml
  schedule/yam/test_cases/ssh-x.yaml
  schedule/yam/test_cases/zfcp.yaml
  schedule/yast/rmt_server_install/rmt_server_install.yaml
  schedule/yast/sle/flows/default_s390x_zvm_textmode.yaml
Labels: qe-yam

#19734 Add verify_consistency_self_update and verify_yast2_control_center tests
  lib/y2_module_consoletest.pm
  schedule/yam/test_cases/verify_consistency_self_update.yaml
  tests/yam/verify_consistency_self_update.pm
Labels: qe-yam

#19405 Add a new test to verify python311_virtualenv
  schedule/functional/stack_tests_python.yaml
  tests/console/python3_setuptools.pm
  tests/console/python_virtualenv.pm
Labels: qe-core

#19746 Fail the multi-machine test if gateway is not reachable
  lib/network_utils.pm
Labels: qe-core

#19715 Reduce yaml files for lvm_multipath and lvm_multipath_encrypted
  schedule/yam/test_cases/lvm_multipath.yaml
  schedule/yam/test_cases/lvm_multipath_encrypted.yaml
  schedule/yast/lvm_multipath_aarch64.yaml
  schedule/yast/lvm_multipath_encrypted.yaml
  schedule/yast/lvm_multipath_encrypted_aarch64.yaml
  schedule/yast/lvm_multipath_encrypted_x86_64.yaml
  schedule/yast/lvm_multipath_pvm.yaml
  test_data/yast/lvm_multipath_encrypted.yaml
Labels: qe-yam

#19760 update_install: Fix the conflict rollback
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19767 Remove view development module from sles15sp6 maintenance update
  schedule/yast/qam-yast_self_update_view_development.yaml
  schedule/yast/sle/flows/default_sle15sp6_x86.yaml
Labels: qe-yam

#19771 Resolve conflict between "openssl-ibmca" packages
  tests/qam-updinstall/update_install.pm
Labels: qe-core

#19774 containers: Use nmap's ncat for netavark upstream tests
  lib/main_containers.pm
  tests/containers/netavark_integration.pm
Labels: WIP

#19776 Add wait_for_idle_cluster after resource move
  tests/ha/filesystem.pm
Labels: WIP

#19757 Adapt raid_encrypted_home_x86_64.xml file for SLES15SP3 installation
  data/yam/autoyast/raid_encrypted_home_x86_64.xml.ep
  tests/console/validate_raid_encrypt_home.pm
Labels: qe-yam

#19748 Skip reinstalling bootloader if encrypted
  tests/console/perl_bootloader.pm
  tests/transactional/trup_smoke.pm
Labels: Ready, qe-core

#19781 pc: Set SCAP_REPORT
  lib/publiccloud/provider.pm
Labels: urgent

#19786 Update sles12sp5_install_with_scc_addons_x86_64 profile name
  data/yam/autoyast/support_images/installation_with_scc_addons_x86_64.xml.ep
Labels: qe-yam

#19759 Add autoyast installation test for svirt-xen-hvm
  data/yam/autoyast/create_hdd_textmode_xen_hvm.xml
  tests/autoyast/installation.pm
Labels: qe-yam

#19800 Publish qcow2 image with tsm enabled
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19769 Reduce yaml files for multipath
  schedule/yam/test_cases/multipath.yaml
  schedule/yast/multipath_pvm.yaml
Labels: qe-yam

#19803 Reduce yaml schedule files for minimal+role_minimal testsuites
  schedule/yam/test_cases/minimal+role_minimal.yaml
  schedule/yast/minimal+role_minimal/minimal+role_minimal.yaml
  schedule/yast/minimal+role_minimal/minimal+role_minimal@pvm.yaml
  schedule/yast/minimal+role_minimal/minimal+role_minimal_aarch64.yaml
  schedule/yast/minimal+role_minimal/minimal+role_minimal_x86_64.yaml
Labels: qe-yam

#19822 update_install: Remove phub repo on all qemu updates
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19825 Resolve conflict between 'openmpi*-config' packages
  tests/qam-updinstall/update_install.pm
Labels: Ready

#19826 Use correct FIPS setup workflow in env mode
  tests/fips/fips_setup.pm
Labels: qe-security

#19812 Reduce yaml files for msdos
  schedule/yam/test_cases/msdos.yaml
  schedule/yast/msdos/msdos.yaml
  schedule/yast/msdos/msdos@pvm.yaml
  schedule/yast/msdos/msdos@s390x.yaml
  schedule/yast/msdos/msdos@svirt-xen-pv.yaml
  schedule/yast/msdos/msdos_aarch64.yaml
  schedule/yast/msdos/msdos_x86_64.yaml
  schedule/yast/sle/flows/default_svirt-hyperv.yaml
Labels: qe-yam

#19830 update_install: Add patterns-base-fips-certified conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19810 [PoC] Introduce HPVS testing in IBM Cloud
  data/containers/ibm_hpvs/bci-busybox
  data/containers/ibm_hpvs/workload.yaml
  schedule/ibm.yaml
  tests/containers/prepare_hpvs.pm
Labels: Ready

#18644 Fix evolution smoke test
  data/evolution/evolution-backup.tar.gz
  lib/x11test.pm
  schedule/functional/gnome.yaml
  tests/x11/evolution/evolution_smoke.pm
Labels: qe-core

#19841 Add legacy module for ntp in 15-SP4
  tests/security/ntpd.pm
Labels: qe-security

#19850 Enter passphrase on encrypted s390x disk
  lib/security_boot_utils.pm
Labels: qe-security
