Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2024-05, with the labels that each got.

#19222 containers: Drop packagehub dependencies for upstream tests
  data/containers/htpasswd
  lib/containers/bats.pm
  lib/main_containers.pm
  tests/containers/podman_integration.pm
  tests/containers/skopeo_integration.pm
Labels: WIP

#19224 Update chrome test
  tests/x11/chrome.pm
Labels: Ready, qe-core

#19173 Register desktop appliaction after media migration from 12SP5 on ppc64le
  schedule/migration/ppc64le_regression_test_offline_textmode.yaml
  tests/console/system_prepare.pm
Labels: qe-yam

#19236 Set firewall setting in profile for 12SP5 on s390x
  data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
Labels: qe-yam

#19253 Add new white list for bsc#1215378
  data/journal_check/bug_refs.json
Labels: qe-core

#19249 Adapt automation in Yam scope to not check the beta popup
  schedule/yast/encryption/cryptlvm+cancel_existing.yaml
  schedule/yast/encryption/cryptlvm+cancel_existing_pvm.yaml
  schedule/yast/rmt_server_install/rmt_server_install.yaml
  schedule/yast/select_modules_and_patterns/select_modules_and_patterns.yaml
  schedule/yast/sle/flows/default.yaml
  schedule/yast/sle/flows/default_aarch64.yaml
  schedule/yast/sle/flows/default_ppc64le.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
  schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
  schedule/yast/sle/flows/default_s390x_zvm.yaml
  schedule/yast/sle/flows/default_svirt-xen-hvm.yaml
  schedule/yast/sle/flows/default_svirt-xen-pv.yaml
  schedule/yast/sle/flows/default_x86_64.yaml
  schedule/yast/sle/flows/default_x86_64_flavor_full.yaml
Labels: qe-yam

#19250 Fix ppc64le online migration schedule for misc group
  schedule/migration/autoyast_regression_test_online_pre@pvm.yaml
Labels: qe-yam

#19235 Add accept_beta module for mu schedules 15SP6
  schedule/yast/sle/flows/default_sle15sp4_beta_s390x_kvm.yaml
  schedule/yast/sle/flows/default_sle15sp4_beta_x86.yaml
Labels: qe-yam

#19255 Extend runc upstream tests to SLE 15-SP4 & 15-SP5
  lib/main_containers.pm
  tests/containers/runc_integration.pm
Labels: WIP

#19239 Fix some logic issues for qam autoyast config files
  data/autoyast_qam/12-common_base_installation.xml.ep
  data/autoyast_qam/12_installation.xml.ep
  data/autoyast_qam/15_installation.xml.ep
Labels: qe-core

#19264 Fix and update bind test
  data/qam/handle_bind_source_dependencies.sh
  tests/console/bind.pm
Labels: Ready, qe-core

#19248 Ignore failure bsc#1223178 in sshd test module only for ppc64le
  tests/console/sshd.pm
Labels: qe-yam

#19272 Enable vnc-server in firewalld configuration and fix network config issue
  data/autoyast_qam/12_installation.xml.ep
Labels: Ready, qe-core

#19273 Fix required module for bind and expected failure
  tests/console/bind.pm
Labels: Ready, qe-core

#19277 Change license language text for English
  schedule/yast/installer_extended/installer_extended_x86_64.yaml
  test_data/yast/installer_extended/installer_extended_aarch64.yaml
  test_data/yast/installer_extended/installer_extended_ppc64le_s390x.yaml
Labels: qe-yam

#19262 Implement packages' vendor change in yast2 migration jobs
  tests/migration/online_migration/yast2_migration.pm
Labels: qe-yam

#19289 Add schedule with select_patterns module for yast-mru-install-minimal-with-addons
  schedule/yast/maintenance/yast_mru_install_minimal_with_addons_restapi_pcm.yaml
Labels: qe-yam

#19284 Add autoyast xml.ep for migration 15-sp4 pvm
  data/yam/autoyast/create_hdd_migration_ppc64le_15sp4.xml.ep
  lib/autoyast.pm
Labels: WIP, qe-yam

#19298 vmware: create macvlan with gateway and subnet
  tests/containers/podman_netavark.pm
Labels: Ready

#19286 Fix Elemental test
  data/elemental/cloud-config.yaml
  data/journal_check/bug_refs.json
  products/elemental
  tests/elemental/installation.pm
Labels: Ready

#19304 Upload also systemd log for mdadm tests
  tests/console/mdadm.pm
Labels: Ready, qe-core

#19318 Remove unknown flag from old snapper
  tests/console/snapper_create.pm
Labels: urgent

#19297 Skip loading kontact and khelpcenter on unsupported architecture
  lib/main_common.pm
  t/data/test_schedule.out
Labels: Ready, qe-core

#19319 Remove x11 testings for power cases from yaml schedule file
  schedule/migration/online_regression_upgrade@pvm.yaml
Labels: qe-yam

#19314 Remove workaround for bsc#1189543
  lib/registration.pm
Labels: qe-yam

#19313 Add setting for installation via full media on power VM
  tests/console/system_prepare.pm
  tests/installation/addon_products_sle.pm
Labels: qe-yam

#19328 Add BETA_WE variable and code to handle it
  lib/registration.pm
Labels: Ready, qe-core

#19287 Correct KDUMP settings for s390x
  data/yam/autoyast/create_hdd_textmode_s390x.xml
  test_data/yast/yast2_ncurses/textmode_lzo_fadump.yaml
Labels: qe-yam

#19334 update_install: Add regionServiceClientConfig{Azure,EC2,GCE} conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19336 Add new whitelist for bsc#1215405
  data/journal_check/bug_refs.json
Labels: qe-core

#19342 Fix cleanup in tests/publiccloud/run_ltp.pm
  tests/publiccloud/run_ltp.pm
Labels: WIP

#19203 Convert 1st phase of continuous migration into support image
  data/yam/autoyast/autoyast_scc_up.xml
Labels: qe-yam

#19339 Check if repos existed before disable repos
  lib/migration.pm
Labels: qe-yam

#19350 Workaround to remove python3-argcomplete before migration
  tests/migration/online_migration/zypper_patch.pm
Labels: qe-yam

#19354 Add back modules to HA image
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19359 Add --auto-agree-with-licenses to preinstall solver
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19355 nfs: Incease test timeout
  tests/network/nfs.pm
Labels: Ready, qe-core

#19360 Enlarge welcome timeout value on s390x
  tests/installation/welcome.pm
Labels: qe-yam

#19321 Include latest SPs in create_hdd_maintenance ay script
  data/yam/autoyast/support_images/create_hdd_maintenance.xml.ep
Labels: qe-yam

#19366 Change waiting time for grub2
  data/yam/autoyast/autoyast_scc_up.xml
Labels: qe-yam

#19348 Add autoyast profile for 15spX prepare migration job
  data/yam/autoyast/create_hdd_migration_ppc64le.xml.ep
Labels: qe-yam

#19376 Update encrypted devices number in crypttab
  test_data/yast/encryption/full_lvm_enc_luks2.yaml
Labels: qe-yam

#19365 Reduce yaml file for cryptlvm
  schedule/yam/test_cases/cryptlvm.yaml
  schedule/yast/encryption/cryptlvm_sle_15.yaml
  schedule/yast/encryption/cryptlvm_sle_15_x86_64.yaml
Labels: qe-yam

#19377 Change grub timeout setting
  tests/migration/online_migration/zypper_patch.pm
Labels: qe-yam

#19383 containers: Minimize dependency on registry mirror
  lib/containers/common.pm
  lib/containers/containerd_crictl.pm
  lib/containers/containerd_nerdctl.pm
  lib/containers/engine.pm
  lib/containers/utils.pm
  lib/main_containers.pm
  tests/containers/container_engine.pm
  tests/containers/firewall.pm
  tests/containers/podman_netavark.pm
  tests/containers/podman_network_cni.pm
  tests/containers/rootless_podman.pm
Labels: WIP

#19388 update_install: Add conflicts for dpdk on aarch64
  data/autoyast_qam/15_installtest.xml.ep
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#19387 Fix encrypted device num issue
  test_data/yast/encryption/crypt_no_lvm_enc_luks2.yaml
  test_data/yast/encryption/full_lvm_enc_luks2.yaml
Labels: qe-yam

#19386 Added yaml schedule file for powerVM prepare job
  schedule/yast/autoyast/autoyast_install_for_migr_spvm.yaml
Labels: qe-yam

#19382 Reduce yaml file for crypt_no_lvm
  schedule/yam/test_cases/crypt_no_lvm.yaml
  schedule/yast/encryption/crypt_no_lvm.yaml
  schedule/yast/encryption/crypt_no_lvm_x86_64.yaml
Labels: qe-yam

#19398 containers: Add CAP_NET_RAW capability for ping
  lib/containers/common.pm
Labels: urgent

#19403 Add a workaround to enable wicked service
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#19060 Run OpenStack/Cloud image in QEMU
  data/jeos/g_cloudinit.cfg
  lib/main_common.pm
  lib/version_utils.pm
  tests/boot/cloud_init.pm
  tests/jeos/verify_cloudinit.pm
Labels: Ready

#19421 Revert "Add a workaround to enable wicked service"
  tests/migration/online_migration/zypper_migration.pm
Labels: qe-yam

#19430 Remove phub repo
  data/autoyast_qam/15_installtest.xml.ep
Labels: Ready, qe-core

#19435 De-registers the system and base product
  tests/yam/migration/setup_registration.pm
Labels: qe-yam

#19436 Enable upgrade test from leap to tw on aarch64
  lib/opensusebasetest.pm
  tests/installation/setup_zdup.pm
Labels: qe-core
