Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-04, with the labels that each got.

#21620 Add system param check for sles16
  tests/sles4sap/sys_param_check.pm
Labels: qe-core

#21630 Remove kdump test from QE-Core for sle16
  schedule/functional/toolchain_sle16.yaml
Labels: Ready, qe-core

#21631 Replace 'body' with 'content' for sle16 script
  data/agama_auto/sle_default.jsonnet
  data/agama_auto/sle_default_ipmi_no_reg.jsonnet
  data/agama_auto/sle_default_pvm.jsonnet
  data/agama_auto/sle_default_pvm_no_reg.jsonnet
  data/agama_auto/sle_default_s390x_kvm.jsonnet
  data/agama_auto/sle_default_s390x_kvm_no_reg.jsonnet
Labels: qe-core

#21636 Replace 'body' with 'content' for HANAperf SLE16 agama.json
  data/autoyast_hanaperf/agama-config.jsonnet
Labels: qe-sap-ha

#21637 Replace body section with content in SLES for SAP & HA jsonnet files
  data/sles4sap/agama/sles_ha_default.jsonnet
  data/sles4sap/agama/sles_sap_default.jsonnet
  data/sles4sap/agama/sles_sap_default_ppc64le.jsonnet
Labels: qe-sap-ha

#21640 Replace validate_product with validate_base_product
  schedule/yam/agama_ppc64le.yaml
Labels: qe-yam

#21422 Increase robustness of publiccloud::basetest _cleanup subroutine
  lib/publiccloud/basetest.pm
  lib/publiccloud/provider.pm
  tests/publiccloud/check_registercloudguest.pm
  tests/publiccloud/check_services.pm
  tests/publiccloud/run_ltp.pm
  tests/publiccloud/slem_basic.pm
Labels: Ready

#21649 containers: Add soft-failure for bsc#1239088 on SLEM 6.0+
  tests/containers/container_engine.pm
Labels: urgent

#21650 containers: Remove soft-failure on bsc#1239088
  tests/containers/container_engine.pm
Labels: urgent

#21653 containers: crun is expected only on SLEM 6.1+
  tests/containers/container_engine.pm
Labels: urgent

#21651 Add profiles for addons on s390x/ppc64le
  data/yam/agama/auto/sles_addons_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_addons_ssh_pub_key_ppc64le.jsonnet
Labels: qe-yam

#21655 containers: Only SLEM 6.1 uses crun
  tests/containers/container_engine.pm
Labels: urgent

#21657 containers: Only SLEM 6.0 & 6.1 use crun
  tests/containers/container_engine.pm
Labels: urgent

#21548 AutoYaST compatibility focus on unsupported sections
  data/yam/agama/auto/autoyast_unsupported.xml
  lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
  schedule/yam/agama_autoyast_unsupported.yaml
  tests/yam/agama/agama.pm
Labels: qe-yam

#21668 containers: docker always uses runc
  tests/containers/container_engine.pm
Labels: urgent

#21591 Use autoyast for qam jobs
  schedule/qam/12-SP3/qam-regression-installation.yaml
  schedule/qam/12-SP5/qam-regression-installation.yaml
  schedule/qam/15-SP2/qam-regression-installation.yaml
  schedule/qam/15-SP2/qam-textmode.yaml
  schedule/qam/15-SP3/qam-regression-installation.yaml
  schedule/qam/15-SP4/qam-regression-installation.yaml
  schedule/qam/15-SP5/qam-regression-installation.yaml
  schedule/qam/15-SP6/qam-regression-installation.yaml
Labels: qe-core

#21662 Add inst.finish in kernel boot parameters for ovmdrv test
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#21669 Erase the root disk before installation
  data/agama_auto/sle_default_pvm.jsonnet
Labels: Ready, qe-core

#21673 Don't start apache too often
  tests/console/apache.pm
Labels: qe-core

#21680 containers: Use oci_runtime instead of runtime variable
  tests/containers/container_engine.pm
Labels: urgent

#21676 On SLED is gnome-terminal default_gui_terminal
  lib/x11utils.pm
Labels: Ready, qe-core

#21690 Move java source Tcheck from gitlab to OSADO data
  data/security/openjdk/Shell.java
  data/security/openjdk/Tcheck.java
  lib/openjdktest.pm
Labels: qe-security

#21694 Fix ay for test network_configuration
  data/autoyast_qam/12-common_base_installation.xml.ep
Labels: Ready, qe-core

#21693 Thunderbird handle new donate tab
  lib/thunderbird_common.pm
Labels: Ready, qe-core

#21702 Add wireguard test for sle16
  tests/network/wireguard.pm
Labels: qe-core

#21698 Add workaround for qemu crash on ppc64le
  lib/bootloader_setup.pm
Labels: Ready, qe-core

#21703 Move fwupd and tuned tests from kernel squad to core
  lib/main_common.pm
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_sle16.yaml
  tests/console/fwupd.pm
  tests/console/tuned.pm
Labels: qe-core

#21706 Ensure register extra module to base product before migration
  lib/registration.pm
Labels: qe-yam

#21729 Modify the selinux policy for apache
  tests/console/php_postgresql.pm
Labels: qe-core

#21739 Improve reboot and logs in Agama
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Yam/Agama/Pom/RebootTextmodePage.pm
  tests/yam/agama/agama.pm
  tests/yam/agama/agama_auto.pm
Labels: qe-yam

#21754 Revert "Re-enable ansible-test for SLE"
  tests/console/ansible.pm
Labels: Ready, qe-core

#21717 Fix micro target version check
  lib/transactional.pm
  lib/version_utils.pm
Labels: qe-yam

#21759 Skip fwupd tests on 390x as ACPI ESRT table it not supported
  schedule/functional/extra_tests_textmode.yaml
Labels: Ready, qe-core

#21704 Add individual package to unattended installation
  data/yam/agama/auto/template.libsonnet
Labels: qe-yam

#21761 Don't remove system default python when doing cleanup
  schedule/functional/stack_tests_python_sle16.yaml
  tests/console/python3_pipx.pm
  tests/console/python3_pynacl.pm
  tests/console/python3_setuptools.pm
  tests/console/python3_websocket_client.pm
  tests/console/python_scientific.pm
  tests/console/python_virtualenv.pm
Labels: qe-core

#21771 User serial terminal for test 'mtab'
  tests/console/mtab.pm
Labels: Ready, qe-core

#21775 Un-schedule fwupd test for s390x on sle16
  schedule/functional/extra_tests_textmode_sle16.yaml
Labels: qe-core

#21776 systemtap: Update yaml schedule on 12-SP5
  schedule/qam/common/mau-extratests2.yaml
Labels: Ready, qe-core

#21769 Do not use curl for minimal role
  tests/console/sshd.pm
Labels: qe-yam

#21758 Add profiles for oemdrv test
  data/yam/agama/auto/autoinst_aarch64.jsonnet
  data/yam/agama/auto/autoinst_x86_64.jsonnet
Labels: qe-yam

#21764 Automate to set the hostname during Agama installation
  lib/autoyast.pm
  schedule/yam/agama_extended.yaml
  schedule/yam/agama_extended_unattended.yaml
  test_data/yam/agama_sle_extended.yaml
  tests/yam/validate/validate_hostname.pm
Labels: qe-yam

#21527 Adapt `import_agama_profile` test step to use dynamic generated JSON profiles
  lib/autoyast.pm
  tests/yam/agama/boot_agama.pm
  tests/yam/agama/import_agama_profile.pm
Labels: qe-yam

#21781 Drop jsonnet file of sles_packages
  data/yam/agama/auto/sles_packages.jsonnet
Labels: qe-yam

#21790 Add dummy.xml file
  data/yam/autoyast/dummy.xml
Labels: qe-yam

#21687 Add unattended installation with TPM FDE
  data/yam/agama/auto/lib/storage.libsonnet
  data/yam/agama/auto/template.libsonnet
  t/01_style.t
Labels: qe-yam

#21774 Add sle-module-systems-management for 15-SP6
  data/autoyast_qam/15_installtest.xml.ep
  lib/registration.pm
Labels: qe-core

#21749 Rename Public Cloud cleanups
  lib/opensusebasetest.pm
  lib/publiccloud/basetest.pm
  lib/publiccloud/provider.pm
  tests/sles4sap/saptune/mr_test.pm
  variables.md
Labels: WIP

#21788 Skip add SCC product on TD
  lib/registration.pm
  schedule/qam/common/mau-extratests-desktop.yaml
Labels: Ready, qe-core

#21808 Skip add SCC product on TD for sle15sp4
  lib/registration.pm
Labels: qe-core

#21782 Add kea test
  data/network_bonding/kea-dhcp4.conf
  schedule/functional/kea.yaml
  tests/network/kea_client.pm
  tests/network/kea_server.pm
Labels: Ready, qe-core

#21442 Format directly home and configure boot partition
  data/yam/agama/auto/lib/storage.libsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/whole_disk_and_boot_unattended.yaml
  test_data/yam/whole_disk_and_boot_unattended.yaml
  tests/console/validate_blockdevices.pm
Labels: qe-yam

#21763 Use networkmanager to configure wireguard server and client
  schedule/functional/wireguard_nm.yaml
  tests/network/wireguard_nm.pm
Labels: qe-core

#21834 Fix rm registercloudguest in serial console
  lib/registration.pm
Labels: qe-yam

#21861 Change `PRETTY_NAME` check value for sle16
  tests/console/check_os_release.pm
Labels: qe-core

#21842 Update packages testing for ansible
  schedule/qam/15-SP4/mau-extratests-phub.yaml
  schedule/qam/15-SP5/mau-extratests-phub.yaml
  schedule/qam/15-SP6/mau-extratests-phub.yaml
  schedule/qam/15-SP7/mau-extratests-phub.yaml
  schedule/qam/common/mau-extratests1.yaml
  tests/console/ansible.pm
Labels: Ready, qe-core

#21685 Prepare Basic HA Test Modules for SLES 16
  lib/hacluster.pm
  lib/sles4sap.pm
  schedule/ha/bv/ha_crash_test_node.yaml
  schedule/ha/bv/haproxy_hawk_node.yaml
  schedule/ha/bv/migration/migration_rolling_upgrade.yaml
  schedule/ha/bv/pacemaker_cts_node.yaml
  schedule/ha/qam/common/qam_cluster_node.yaml
  schedule/ha/qam/common/qam_haproxy_hawk_node.yaml
  schedule/ha/qam/common/qam_migration_rolling_upgrade.yaml
  schedule/sles4sap/netweaver/netweaver_cluster_node.yaml
  schedule/sles4sap/netweaver/netweaver_cluster_systemd.yaml
  t/11_hacluster.t
  tests/ha/await_upgrade_or_update.pm
  tests/ha/check_after_reboot.pm
  tests/ha/check_hawk.pm
  tests/ha/ctdb.pm
  tests/ha/dlm.pm
  tests/ha/fencing.pm
  tests/ha/filesystem.pm
  tests/ha/ha_cluster_crash_test.pm
  tests/ha/ha_cluster_init.pm
  tests/ha/ha_cluster_join.pm
  tests/ha/haproxy.pm
  tests/ha/iscsi_client_setup.pm
  tests/ha/priority_fencing_delay.pm
  tests/ha/qnetd.pm
  tests/ha/remove_node.pm
  tests/sles4sap/ensa/ensa2_web_methods_checks.pm
  tests/sles4sap/hana_install.pm
  tests/sles4sap/netweaver_patch.pm
  tests/sles4sap/sap_suse_cluster_connector.pm
Labels: qe-sap-ha

#21874 update_install: Use solver for conflict patch too
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21866 Schedule gurb_test and change grub timeout on sle16
  data/agama_auto/sle_default.jsonnet
  data/agama_auto/sle_default_pvm.jsonnet
  data/agama_auto/sle_default_s390x_kvm.jsonnet
  schedule/functional/sle16/agama-create-hdd-textmode.yaml
  schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml
Labels: qe-core

#21801 New schedule for lvm TPM FDE
  schedule/yam/agama_tpm_fde_unattended.yaml
  tests/yam/validate/validate_tpm_fde.pm
Labels: qe-yam

#21883 containers: Use go1.24 for runc upstream tests
  tests/containers/bats/runc.pm
Labels: urgent

#21884 Add ulp live patch testing for sle16
  tests/kernel/ulp_openposix.pm
Labels: qe-core

#21867 Fix import gpg key
  tests/migration/online_migration/yast2_migration.pm
Labels: qe-yam

#21906 containers/bats: Ignore error on rm
  lib/containers/bats.pm
Labels: urgent

#21907 containers/bats: Add missing env command
  lib/containers/bats.pm
Labels: urgent

#21905 Install eog as it is not installed by default
  tests/x11/exiv2.pm
Labels: qe-core

#21893 Add systems-management for QR test
  tests/installation/addon_products_sle.pm
Labels: qe-core

#21881 Test Agama post-partitioning scripts
  data/yam/agama/auto/lib/scripts_post_partitioning.libsonnet
  data/yam/agama/auto/sles_packages_ppc64le.jsonnet
  data/yam/agama/auto/sles_packages_s390x.jsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/agama_extended_unattended.yaml
  schedule/yam/agama_extended_unattended_ppc64le.yaml
  schedule/yam/agama_extended_unattended_s390x.yaml
  tests/yam/validate/validate_post_partitioning.pm
Labels: qe-yam

#21895 Agama headless installation
  schedule/yam/agama_headless.yaml
  schedule/yam/agama_headless_pvm.yaml
  schedule/yam/agama_headless_s390x.yaml
  tests/yam/agama/agama.pm
  tests/yam/agama/boot_agama.pm
  tests/yam/agama/validate_headless.pm
Labels: qe-yam

#20963 Update container registry links
  lib/containers/urls.pm
Labels: Ready

#21873 Fix check_target_version
  lib/transactional.pm
Labels: qe-yam
