Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-05, with the labels that each got.

#21939 containers: De-schedule podman on SLEM & Leap Micro
  lib/main_containers.pm
Labels: urgent

#21940 update_install: Softfail on expected update-test-trivial failure
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21837 Create sles_gnome and sles_gnome_unattended installations
  schedule/yam/agama_gnome.yaml
  schedule/yam/agama_gnome_s390x.yaml
  schedule/yam/agama_gnome_unattended.yaml
Labels: qe-yam

#21952 usr_sbin_nscd: Don't schedule on TW
  schedule/security/apparmor_profile.yaml
Labels: Ready

#21978 Fix the ram size for qemu test on s390x
  tests/qemu/kvm.pm
  tests/qemu/qemu.pm
Labels: qe-core

#21972 Remove access_beta_distribution from YaST schedules
  schedule/yast/sle/flows/default_aarch64.yaml
  schedule/yast/sle/flows/default_aarch64_flavor_full.yaml
  schedule/yast/sle/flows/default_ipmi.yaml
  schedule/yast/sle/flows/default_ppc64le.yaml
  schedule/yast/sle/flows/default_s390x_kvm.yaml
  schedule/yast/sle/flows/default_s390x_kvm_flavor_full.yaml
  schedule/yast/sle/flows/default_s390x_kvm_textmode.yaml
  schedule/yast/sle/flows/default_s390x_svirt.yaml
  schedule/yast/sle/flows/default_s390x_zvm.yaml
  schedule/yast/sle/flows/default_s390x_zvm_textmode.yaml
  schedule/yast/sle/flows/default_svirt-hyperv.yaml
  schedule/yast/sle/flows/default_svirt-xen-hvm.yaml
Labels: qe-yam

#21981 Remove beta handling from default_x86_64.yaml
  schedule/yast/sle/flows/default_svirt-xen-pv.yaml
  schedule/yast/sle/flows/default_x86_64.yaml
  schedule/yast/sle/flows/default_x86_64_flavor_full.yaml
Labels: qe-yam

#21986 Need to get the dynamic interface name instead of hard-coding eth0
  tests/microos/networkmanager.pm
Labels: qe-core

#21928 Update the zgrep search log to agama_auto-agama-logs.tar.gz for ibft validation
  tests/installation/validation/ibft.pm
Labels: qe-yam

#21991 Remove beta tests from installer_extended schedule
  schedule/yam/test_cases/installer_extended.yaml
Labels: qe-yam

#22010 Stop firewall before disabling it in wicked tests
  tests/wicked/before_test.pm
Labels: qe-core

#21915 Add validation to check that installed repos are the ones expected and enabled
  schedule/yam/agama.yaml
  schedule/yam/agama_auto.yaml
  test_data/yam/agama_sle.yaml
Labels: qe-yam

#22020 Add ip=dhcp in kernel parameter on powerVM
  lib/bootloader_pvm.pm
Labels: qe-yam

#22022 Adapt test data for new module of systems management
  test_data/yast/skip_registration/default_repos.yaml
Labels: qe-yam

#22037 bats/podman: Remove libcriu2 dependency
  tests/containers/bats/podman.pm
Labels: urgent

#22038 bats: Install specific ncat version from upstream
  lib/containers/bats.pm
Labels: urgent

#22049 Remove workaround for bsc#1242721
  data/agama_auto/sle_default_gnome.jsonnet
Labels: Ready, qe-core

#22039 Add ntp_client test for sle15SPX and sle16
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/extra_tests_textmode_sle16.yaml
  schedule/qam/15-SP2/qam-textmode.yaml
  schedule/qam/15-SP3/qam-textmode.yaml
  schedule/qam/15-SP4/qam-textmode.yaml
  schedule/qam/15-SP5/qam-textmode.yaml
  schedule/qam/15-SP6/qam-textmode.yaml
  schedule/qam/15-SP7/qam-textmode.yaml
Labels: qe-core

#22052 Add some debug info for agama install failure
  tests/installation/agama_reboot.pm
Labels: Ready, qe-core

#22075 Wait longer to make sure openQA job is running
  tests/openqa/osautoinst/test_running.pm
Labels: qe-core

#22097 bats/runc: Ignore checkpoint test as root
  data/containers/bats/skip.yaml
  tests/containers/bats/README.md
Labels: urgent

#22102 Add required addons for sle15sp7 kiwi test
  data/kiwi/appliance_sle15sp7.kiwi
  tests/kiwi_images_test/kiwi_build_image.pm
Labels: qe-core

#22113 Minor BATS fixes
  data/containers/bats/skip.yaml
  lib/containers/bats.pm
Labels: urgent

#22120 Exclude journal_remote on 15-SP7 until it's added
  schedule/qam/common/mau-extratests1.yaml
Labels: Ready, qe-core

#22131 Re-schedule more tests on sle16
  schedule/functional/extra_tests_textmode_sle16.yaml
  schedule/functional/sle16/extra_tests_textmode.yaml
  schedule/functional/sle16/stack_tests_python.yaml
  schedule/functional/sle16/toolchain.yaml
  tests/console/cron.pm
  tests/console/golang.pm
  tests/console/mta.pm
  tests/console/pciutils.pm
  tests/console/pkcon.pm
  tests/console/sssd_389ds_functional.pm
  tests/console/valgrind.pm
  tests/console/zziplib.pm
Labels: qe-core

#22141 SLE16 Full validate_repos of install jobs
  schedule/security/sle16/agama.yaml
  schedule/security/sle16/agama_remote_s390x.yaml
Labels: qe-security

#22144 containers: Skip IPv6 in isolation test on s390x
  tests/containers/isolation.pm
Labels: urgent

#22137 year_2038: Skip testing for s390
  tests/console/year_2038_detection.pm
Labels: Ready, qe-core

#22146 Simplify 'sssd_389ds_functional' test
  tests/console/sssd_389ds_functional.pm
Labels: qe-core, qe-security

#22160 bats: Fix aardvark-dns test
  lib/containers/bats.pm
Labels: urgent

#22185 Changed SLE DVD1 mirror URL on AutoYast template
  data/yam/autoyast/sles15sp3+_create_hdd_gnome_unregistered_no_self_update.xml.ep
Labels: qe-yam

#22181 Add bsc#1218471 to the journal check bug refs
  data/journal_check/bug_refs.json
Labels: qe-core

#22184 install_patterns: Workaround GDM crash on 15-SP7 ppc64le
  lib/opensusebasetest.pm
Labels: Ready, qe-core

#22018 Wipe existed disks on powerVM for Autoyast scenarios in Agama
  data/yam/agama/auto/autoyast_supported.xml
Labels: qe-yam

#21865 Ensure disabling questions bypass the encryption popup in Agama
  data/yam/agama/auto/lib/scripts_pre.libsonnet
  data/yam/agama/auto/lvm_encrypted_ppc64le.jsonnet
  data/yam/agama/auto/scripts.jsonnet
  data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_addons_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_default_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_gnome_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_lvm_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_packages_ppc64le.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_sap_default_ssh_pub_key.jsonnet
Labels: qe-yam

#22180 Update code for aaa_base
  tests/console/aaa_base.pm
Labels: qe-core

#22204 Added URI to agama repo validation
  test_data/yam/agama_sle.yaml
Labels: qe-yam
