Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-02, with the labels that each got.

#21100 Quickfix for wiping filesystems before installing
  data/yam/agama/auto/lvm_encrypted.jsonnet
Labels: qe-yam

#21101 Quickfix for sporadic grub issue on PowerVM
  data/yam/agama/auto/lvm_encrypted.jsonnet
Labels: qe-yam

#21102 redis: Don't add redis7 on 15-SP7
  tests/console/redis.pm
Labels: Ready, qe-core

#20897 Simplify AutoYaST profiles for sles12sp5 support image
  data/autoyast_sle12/create_hdd/create_hdd_sap_sles.xml.ep
  data/yam/autoyast/sles12sp5_create_hdd_gnome_unregistered_no_self_update_s390x.xml.ep
  data/yam/autoyast/support_images/autoyast_sles12sp5_media_def_patterns_minimal_x86_64.xml
  data/yam/autoyast/support_images/create_hdd_ha_sles.xml.ep
  data/yam/autoyast/support_images/create_hdd_sap_textmode_sles.xml.ep
  data/yam/autoyast/support_images/sles12sp5_install_all_patterns_s390x.xml
  data/yam/autoyast/support_images/sles12sp5_install_default_patterns_s390x.xml
  data/yam/autoyast/support_images/sles15sp6_install_textmode_hpc_x86_64.xml
Labels: qe-yam

#21110 Install wget during ASE installation on SLE16
  tests/sles4sap/ase_install.pm
Labels: Ready

#21112 disk_boot: Don't wait grub2 also on UEFI
  tests/microos/disk_boot.pm
Labels: Ready

#21117 Improve lftp test
  tests/security/vsftpd/lftp.pm
Labels: qe-security

#21119 Remove the hardcode password on the data directory
  data/agama_auto/leap_default.jsonnet
Labels: qe-core

#21075 Fix snapshot ID capture in snapper_zypp test
  tests/console/snapper_zypp.pm
Labels: qe-core

#21115 zypper_lifecycle: Info instead of soft fail
  tests/console/zypper_lifecycle.pm
Labels: Ready, qe-core

#21120 Enable s390x install tests on sle16
  schedule/functional/sle16/agama-create-hdd-textmode_s390x_kvm.yaml
  tests/installation/agama_reboot.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-core

#21122 clamav: Use repo/fixed to avoid cleanup
  tests/console/clamav.pm
Labels: Ready, qe-core

#21118 Fix hash comparison
  tests/security/vsftpd/lftp.pm
Labels: qe-security

#21140 Install package 'rsync' if it doesn't exist
  tests/console/rsync_client.pm
  tests/console/rsync_server.pm
Labels: qe-core

#21139 autofs_server: Remove soft-fail bsc#1215649
  tests/network/autofs_server.pm
Labels: Ready, qe-core

#21145 Quick-PR Remove files with root password in plaintext
  data/yam/agama/auto/default_no_scc_plain_password.jsonnet
  data/yam/agama/auto/leap_default_plain_password.jsonnet
  data/yam/agama/auto/leap_gnome_plain_password.jsonnet
  data/yam/agama/auto/sle_multipath_scc_plain_password.jsonnet
Labels: qe-yam

#21150 Enable back ntp-wait in journalctl test for SLE12
  tests/console/cron.pm
  tests/console/journalctl.pm
Labels: Ready, qe-core

#21154 Upload audit log in post_fail_hook
  lib/Utils/Logging.pm
Labels: qe-core

#21153 Use http protocol to access OSD repo due to cc
  lib/repo_tools.pm
  lib/utils.pm
Labels: qe-core

#21136 Add CI/CD check to avoid uses of plain password on data directory
  t/01_style.t
Labels: qe-core

#21156 Schedule samba AD tests also in FIPS mode
  schedule/security/fips/fips_ker_mode_textmode_extra.yaml
  tests/network/samba/samba_adcli.pm
Labels: qe-security

#21171 Close the oomath welcome pop-up window
  lib/x11test.pm
Labels: Ready, qe-core

#21167 vnc_two_passwords: Refactor outdated test
  tests/x11/vnc_two_passwords.pm
Labels: Ready, qe-core

#21182 Allow ftp full access when enable selinux
  tests/console/vsftpd.pm
Labels: qe-core

#21184 Adapt krb5 tests for SLE16
  lib/mm_tests.pm
  tests/security/krb5/krb5_crypt_prepare.pm
Labels: qe-security

#21188 Adjust usage of record_info in python3_beautifulsoup4
  tests/console/python3_beautifulsoup4.pm
  tests/console/python3_websocket_client.pm
Labels: qe-core

#21200 Fix WE module variable in scheduling
  schedule/security/fips/fips_ker_mode_gnome.yaml
Labels: qe-security

#21201 Add whitelist for bsc#1234013
  data/journal_check/bug_refs.json
Labels: Ready, qe-core

#21211 Handle CC testing on s390x when ssh root login is disabled
  lib/selinuxtest.pm
  schedule/security/cc_audit_tests_part2.yaml
  tests/security/selinux/selinux_setup.pm
Labels: qe-security

#21204 Enable wizard on encrypted Leap system
  tests/console/perl_bootloader.pm
  tests/installation/bootloader_uefi.pm
  tests/jeos/firstrun.pm
Labels: Ready

#21210 vsftpd: Remove soft-fail bsc#1176813
  tests/console/vsftpd.pm
Labels: Ready, qe-core

#21220 update_install: Add libica-devel conflicts on s390x
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21251 Add sealert tests
  tests/security/selinux/setroubleshootd.pm
Labels: qe-security

#21240 Btrfs
  lib/main_common.pm
  schedule/qam/12-SP3/mau-filesystem.yaml
  schedule/qam/12-SP5/mau-filesystem.yaml
  schedule/qam/15-SP2/mau-filesystem.yaml
  schedule/qam/15-SP3/mau-filesystem.yaml
  schedule/qam/15-SP4/mau-filesystem.yaml
  schedule/qam/15-SP5/mau-filesystem.yaml
  schedule/qam/15-SP6/mau-filesystem.yaml
  tests/console/btrfsmaintenance.pm
Labels: Ready, qe-core

#21253 Selinux is enabled by default on Leap 16.0
  lib/version_utils.pm
Labels: qe-core

#21236 year_2038: Remove soft failure bsc#1188626
  tests/console/year_2038_detection.pm
Labels: Ready

#21266 update_install: Fix TD patches
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21279 rmt_feature: Use ASSET_1 for data file
  tests/console/rmt/rmt_feature.pm
Labels: Ready, qe-core

#21234 Added JSONNET package to OpenQA workers
  os-autoinst-distri-opensuse-deps.spec
Labels: qe-yam

#21166 Create test suite for AutoYaST compatibility focus on supported sections
  data/yam/agama/auto/autoyast_supported.xml
  lib/autoyast.pm
Labels: qe-yam

#21310 Fix module numbers > 16
  lib/registration.pm
Labels: qe-yam

#21267 Add register to proxy scc support for Agama
  lib/bootloader_pvm.pm
  lib/bootloader_setup.pm
  lib/registration.pm
  tests/console/system_prepare.pm
  tests/installation/bootloader_zkvm.pm
  tests/installation/ipxe_install.pm
Labels: qe-core
