Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-03, with the labels that each got.

#21294 Authorize TPM after reinstalling bootloader
  tests/transactional/trup_smoke.pm
Labels: qe-core

#21320 Expand vsftpd test coverage
  tests/security/vsftpd/vsftpd.pm
Labels: qe-security

#21351 Refactor gnutls_client test
  tests/fips/gnutls/gnutls_client.pm
Labels: qe-security

#21346 Wipe disk for SAP unattended (ppc64le)
  data/yam/agama/auto/sles_sap_default_ppc64le.jsonnet
Labels: qe-yam

#21334 Remove Unsupported Sections in ay
  data/yam/agama/auto/autoyast_supported.xml
Labels: qe-yam

#21255 year_2038: Remove soft-fail poo#127343
  tests/console/year_2038_detection.pm
Labels: Ready, qe-core

#21377 Fix format issue for sle_default_ppc64le.jsonnet
  data/yam/agama/auto/sle_default_ppc64le.jsonnet
Labels: qe-yam

#21239 Create unattended installation for NVMe with Agama
  schedule/yam/agama_nvme.yaml
  test_data/yam/agama_nvme.yaml
Labels: qe-yam

#21403 Ajdust build_hdd.pm to run on SLE16.
  tests/security/create_swtpm_hdd/build_hdd.pm
Labels: qe-security

#21414 Skip pcm module for sle16 in flask test
  tests/console/flask.pm
Labels: qe-core

#21419 Remove root password for scripts_ssh_pub_key.jsonnet
  data/yam/agama/auto/scripts_ssh_pub_key.jsonnet
Labels: qe-yam

#21427 Un-schedule ‘apache-nss’ test from tumbleweed and sle16
  schedule/qam/common/mau-webserver.yaml
Labels: qe-core

#21322 Create unattended installation for lvm multipath encrypted
  data/yam/agama/auto/lvm_multipath_encrypted.jsonnet
  schedule/yam/agama_lvm_multipath_encrypted_unattended.yaml
  test_data/yam/agama_lvm_multipath_encrypted.yaml
Labels: qe-yam

#21433 ay: Use only major version on sle12 pcm
  lib/autoyast.pm
Labels: Ready, qe-core

#21415 sway: Use openSUSE brand on o3
  tests/sway/sway.pm
Labels: Ready, qe-core

#21440 Add pcm in 'zypper_lr_validate'
  tests/console/zypper_lr_validate.pm
Labels: qe-core

#21447 Fix Salt installation for missing modules
  data/yam/autoyast/salt.xml
Labels: qe-yam

#21450 Reset virtio console in case output can't show in serial terminal
  tests/console/krb5.pm
Labels: qe-core

#21460 Fix 'sudo' logic for sle16
  tests/console/sudo.pm
Labels: Ready, qe-core

#21409 Add unattended installation via Full Medium and register system
  data/yam/agama/auto/sles_default.jsonnet
  data/yam/agama/auto/sles_default_no_registration.jsonnet
  data/yam/agama/auto/sles_default_no_registration_ppc64le.jsonnet
  data/yam/agama/auto/sles_default_ppc64le.jsonnet
  data/yam/agama/auto/sles_lvm.jsonnet
  data/yam/agama/auto/sles_lvm_no_reg.jsonnet
  data/yam/agama/auto/sles_lvm_ppc64le.jsonnet
  data/yam/agama/auto/sles_multipath.jsonnet
  data/yam/agama/auto/sles_multipath_no_reg.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4_home_filesystem_xfs.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4_no_reg.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4_ppc64le.jsonnet
  data/yam/agama/auto/sles_root_filesystem_xfs.jsonnet
  data/yam/agama/auto/sles_root_filesystem_xfs_no_reg.jsonnet
  data/yam/agama/auto/sles_root_filesystem_xfs_ppc64le.jsonnet
  schedule/yam/agama_post_registration.yaml
  schedule/yam/agama_post_registration_ppc64le.yaml
  schedule/yam/agama_post_registration_s390x.yaml
  tests/yam/validate/post_registration.pm
Labels: qe-yam

#21461 containers: Limit isolation test
  lib/main_containers.pm
  tests/containers/isolation.pm
Labels: urgent

#21408 Add unattended installation with localization changed
  data/yam/agama/auto/sles_change_localization.jsonnet
  schedule/yam/agama_change_localization_unattended.yaml
Labels: qe-yam

#21467 mdadm: Fix failing mdadm.sh
  data/qam/mdadm.sh
  tests/console/mdadm.pm
Labels: Ready, qe-core

#21473 start_systemd_testkit_offline: Revert softfail and remove false fail
  tests/console/start_systemd_testkit_offline.pm
Labels: Ready, qe-core

#21491 containers: Fix skopeo cleanup
  tests/containers/skopeo.pm
Labels: urgent

#21492 containers: Remove check_bsc1200623
  tests/containers/rootless_podman.pm
Labels: urgent

#21494 Update fake ssh public key for s390x
  data/yam/agama/auto/lvm_encrypted_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_default_no_registration_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_lvm_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_root_filesystem_ext4_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_root_filesystem_xfs_ssh_pub_key.jsonnet
Labels: qe-yam

#21498 Fix release notes url check
  tests/installation/release_notes_from_url.pm
Labels: qe-yam

#21493 Close GIMP welcome page
  tests/x11/flatpak.pm
Labels: qe-yam

#21507 Add ssh public key in autoyast profile
  data/yam/agama/auto/autoyast_supported.xml
Labels: qe-yam

#21510 Increase timeout value for passphase on s390x
  lib/utils.pm
Labels: qe-yam

#21513 containers: Validate script output on isolation test
  lib/main_containers.pm
  tests/containers/isolation.pm
Labels: WIP

#21516 Remove commented code
  tests/installation/release_notes_from_url.pm
Labels: qe-yam

#21505 Remove haveged package test refer bsc#1239023
  tests/console/gpg.pm
Labels: qe-core

#21407 Add workaround for PVM first boot issue
  lib/bootloader_pvm.pm
Labels: qe-core

#21501 SAPHanaSR-showAttr output is now parsed to decode_json() like format
  lib/saputils.pm
  lib/sles4sap_publiccloud.pm
  t/12_sles4sap_publiccloud.t
  t/18_saputils.t
Labels: qe-sap-ha

#16497 Reduce execution of compile tests by checking changed files only
  .github/workflows/ci.yml
  Makefile
Labels: qe-core

#21523 Exclude syscall_thrasher from encrypted s390x
  tests/security/eal4/syscall_thrasher.pm
Labels: qe-security

#21504 Add a schedule to test basic NetWeaver cluster in pvm_hmc
  schedule/sles4sap/pvm_nw_cluster_node.yaml
  tests/ha/barrier_init.pm
  tests/sles4sap/netweaver_cluster.pm
  tests/sles4sap/netweaver_filesystems.pm
Labels: qe-sap-ha

#21446 Add necessary changes and schedule network tests for SLES
  schedule/qam/common/mau-extratests-desktop.yaml
  tests/x11/network/NM_wpa2_enterprise.pm
  tests/x11/network/hwsim_wpa2_enterprise_setup.pm
  tests/x11/network/yast2_network_use_nm.pm
Labels: qe-core

#21567 New schedule without hostname validation for arch ppc64le
  schedule/yam/agama_ppc64le.yaml
Labels: qe-yam

#21565 Solve storage JSONNET profile definition error
  data/yam/agama/auto/lib/storage.libsonnet
  data/yam/agama/auto/template.libsonnet
Labels: qe-yam

#21496 Add CI check for jsonnet
  .github/workflows/ci.yml
  Makefile
  tools/check_jsonnet
Labels: qe-yam

#21572 update_install: Don't run snapper rollback on sle11
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21530 Add test module to validate the base product
  schedule/yam/agama.yaml
  schedule/yam/agama_auto.yaml
  schedule/yam/agama_autoyast_supported_ppc64le.yaml
  schedule/yam/agama_autoyast_supported_qemu.yaml
  schedule/yam/agama_autoyast_supported_s390x.yaml
  schedule/yam/agama_from_usb.yaml
  schedule/yam/agama_remote_pvm.yaml
  schedule/yam/agama_remote_s390x.yaml
  schedule/yam/agama_s390x.yaml
  tests/yam/validate/validate_base_product.pm
Labels: qe-yam

#21544 Fix s390x booting of Full medium
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-yam

#21575 Fix s390x booting of Full medium
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-yam

#21579 Update installtest ay profiles
  data/autoyast_qam/12_installtest.xml.ep
  data/autoyast_qam/15_installtest.xml.ep
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#21394 Add select pattern for agama interactive installation
  schedule/yam/agama_software_patterns.yaml
  schedule/yam/agama_software_patterns_s390x.yaml
  tests/yam/validate/validate_installed_patterns.pm
Labels: qe-yam

#21550 Automate support extension in unattended installation (HA)
  data/yam/agama/auto/lib/addons.libsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/agama_unattended_patterns.yaml
  tests/yam/validate/validate_installed_patterns.pm
Labels: qe-yam

#21580 Quick fix to get PUBLISH_HDD_1 work
  schedule/yam/agama_lvm_encrypted_unattended.yaml
  schedule/yam/agama_lvm_encrypted_unattended_ppc64le.yaml
  schedule/yam/agama_lvm_encrypted_unattended_s390x.yaml
Labels: qe-yam

#21590 Avoid to set SCC_URL in bootloader for Agama Full medium testings
  lib/registration.pm
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_zkvm.pm
Labels: qe-yam

#21328 Add scenario for mediacheck of both installation mediums
  lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
  schedule/yam/agama_check_installation_medium.yaml
  tests/yam/agama/agama_check_installation_medium.pm
Labels: qe-yam

#21599 Add schedule files for ha test
  schedule/yam/agama_unattended_patterns_ppc64le.yaml
  schedule/yam/agama_unattended_patterns_s390x.yaml
Labels: qe-yam

#21603 Extend handle interrupted status to older versions
  tests/console/btrfsmaintenance.pm
Labels: Ready, qe-core

#21604 Add live.password for Full medium testing on s390x
  tests/installation/bootloader_zkvm.pm
Labels: qe-yam

#21597 Change agama install boot_options
  lib/autoyast.pm
  lib/bootloader_pvm.pm
  lib/bootloader_setup.pm
  lib/version_utils.pm
  schedule/ha/bv/agama_install_sles_ha.yaml
  tests/installation/agama_reboot.pm
  tests/installation/bootloader_s390.pm
  tests/installation/bootloader_uefi.pm
  tests/installation/ipxe_install.pm
  tests/yam/agama/boot_agama.pm
  variables.md
Labels: Ready

#21606 start_systemd_testkit_offline: Add header info
  tests/console/start_systemd_testkit_offline.pm
Labels: Ready, qe-core

#21607 Shorten mediacheck module name
  schedule/yam/agama_check_installation_medium.yaml
  tests/yam/agama/check_installation_medium.pm
Labels: WIP, qe-yam

#21613 Add timeout to oqs_provider execute binary
  tests/security/oqs_provider_openssl.pm
Labels: qe-security
