Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-06, with the labels that each got.

#22214 bats/podman: Update SKIP for podman 5.5.0
  data/containers/bats/skip.yaml
Labels: urgent

#22227 Minor BATS fixes
  data/containers/bats/skip.yaml
  tests/containers/bats/README.md
Labels: urgent

#22232 Revert "Exclude journal_remote on 15-SP7 until it's added"
  schedule/qam/common/mau-extratests1.yaml
Labels: Ready, qe-core

#22231 evolution: Use Server Applications module for dovecot
  tests/x11/evolution/evolution_prepare_servers.pm
Labels: Ready, qe-core

#22182 Add unattended installation with raid0
  data/yam/agama/auto/lib/storage.libsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/agama_raid_unattended.yaml
Labels: qe-yam

#22254 containers: Test registry package only on supported products
  lib/main_containers.pm
  tests/containers/registry.pm
Labels: urgent

#22247 Adapt rmt validate_repos test data
  test_data/yam/agama_rmt.yaml
Labels: qe-yam

#22263 Make sure NIC is up after installation
  schedule/functional/sle16/agama-create-hdd-gnome.yaml
  schedule/functional/sle16/agama-create-hdd-textmode.yaml
  tests/installation/network_check.pm
Labels: qe-core

#22244 kea: Change kea log path
  data/network_bonding/kea-dhcp4.conf
  tests/network/kea_server.pm
Labels: Ready, qe-core

#22145 Add more tests which are running on sle15sp7 but not on sle16 yet
  lib/serial_terminal.pm
  schedule/functional/sle16/extra_tests_textmode.yaml
  schedule/functional/sle16/extra_tests_textmode2.yaml
  tests/console/btrfs_balance.pm
  tests/console/libgit2.pm
  tests/console/wpa_supplicant.pm
  tests/console/zypper_lifecycle.pm
  tests/network/cifs.pm
  tests/systemd_testsuite/prepare_systemd_and_testsuite.pm
Labels: qe-core

#22282 bats: Increase timeout
  lib/containers/bats.pm
Labels: urgent

#22284 bats: mkdir should not fail
  lib/containers/bats.pm
Labels: urgent

#22291 Translate existing jsonnet to template
  data/yam/agama/auto/lib/base.libsonnet
  data/yam/agama/auto/template.libsonnet
Labels: qe-yam

#22294 Enable long URLs in s390x zVM
  tests/installation/bootloader_s390.pm
Labels: qe-yam

#22274 Validate RMT URI in validate_repos
  test_data/yam/agama_rmt.yaml
Labels: qe-yam

#22279 Report SELinux AVCs after each HA & SAP test module
  lib/hacluster.pm
  lib/sles4sap.pm
  tests/ha/check_logs.pm
  tests/ha/fencing.pm
  tests/ha/qnetd.pm
Labels: qe-sap-ha

#21745 Create unattended scenario with home encrypted and resizing
  data/yam/agama/auto/lib/storage.libsonnet
  data/yam/agama/auto/template.libsonnet
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Yam/Agama/Pom/EnterPassphraseForHomePage.pm
  lib/filesystem_utils.pm
  schedule/yam/agama_full_disk_encryption.yaml
  schedule/yam/agama_full_disk_encryption_ppc64le.yaml
  schedule/yam/agama_unattended.yaml
  schedule/yam/resize_partitions_unattended.yaml
  test_data/yam/agama_resize.yaml
  test_data/yam/agama_resize_aarch64.yaml
  tests/console/validate_blockdevices.pm
  tests/yam/agama/boot_encrypted_partitions.pm
  tests/yam/agama/boot_full_disk_encryption.pm
Labels: qe-yam

#22339 Remove unused profiles after applied template
  data/yam/agama/auto/sles_change_localization.jsonnet
  data/yam/agama/auto/sles_default_no_registration.jsonnet
  data/yam/agama/auto/sles_default_no_registration_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_default_no_registration_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_gnome_ssh_pub_key.jsonnet
  data/yam/agama/auto/sles_gnome_ssh_pub_key_ppc64le.jsonnet
  data/yam/agama/auto/sles_sap_default_ssh_pub_key.jsonnet
Labels: qe-yam

#22155 Add wireshark cli test
  schedule/functional/extra_tests_textmode.yaml
  schedule/functional/sle16/extra_tests_textmode.yaml
  schedule/qam/common/mau-extratests1.yaml
  tests/console/wireshark_cli.pm
Labels: Ready, qe-core

#22377 mau-extratests2: Don't schedule ipv6 tests on 12-SP3
  schedule/qam/common/mau-extratests1.yaml
  schedule/qam/common/mau-extratests2.yaml
Labels: Ready, qe-core

#22312 kernel: Enhance kselftests runner while using git tag
  tests/kernel/run_kselftests.pm
Labels: qe-kernel

#22367 Add condition to check if pygit exsited
  tests/console/libgit2.pm
Labels: qe-core

#22399 Restrict BATS patches to each package test directory
  data/containers/bats/skip.yaml
  lib/containers/bats.pm
Labels: urgent

#22400 Fix container-suseconnect test
  lib/containers/container_images.pm
Labels: urgent

#22404 Fix for sysm related failures in MU
  lib/Installation/ModuleRegistration/ModuleRegistrationPage.pm
Labels: qe-yam

#22378 aa_prepare: Replace nscd with samba
  tests/security/apparmor/aa_prepare.pm
Labels: Ready

#22408 Replace 'agama profile import' with 'agama config load'
  lib/autoyast.pm
  tests/yam/agama/import_agama_profile.pm
Labels: qe-yam

#22258 Add unattended support for DASD
  data/yam/agama/auto/lib/dasd.libsonnet
  data/yam/agama/auto/template.libsonnet
Labels: qe-yam

#22417 Add console definition for ppc64le
  tests/yam/agama/boot_agama.pm
Labels: Ready, qe-core

#22418 bind: Fix TFAIL variable
  tests/console/bind.pm
Labels: Ready, qe-core

#22300 Create unattended installation for migration to 16.0
  data/yam/autoyast/textmode.xml
  data/yam/autoyast/textmode_ppc64le.xml
  data/yam/autoyast/textmode_s390x.xml
  schedule/yam/agama_migration_15sp7_textmode.yaml
Labels: qe-yam

#22385 Add kdump over NFS test
  lib/kdump_utils.pm
  schedule/storage/nfs.yaml
  tests/kernel/kdump_over_nfs.pm
  tests/kernel/nfs_barriers.pm
Labels: qe-kernel

#22419 dnsmasq: Add retry when query failed
  tests/console/dnsmasq.pm
Labels: Ready, qe-core

#22382 Adapt installation console to tty2 instead of tty7
  lib/susedistribution.pm
  tests/yam/agama/validate_headless.pm
Labels: qe-yam

#22415 Add qa head repo for hostapd
  data/wpa_supplicant/wpa_supplicant_wo_dhcp_test.sh
  tests/console/wpa_supplicant.pm
Labels: qe-core

#22433 bind: Fix single test retry
  tests/console/bind.pm
Labels: Ready, qe-core

#22427 Save/restore Agama settings during installation
  tests/yam/migration/restore_upgrade_env.pm
  tests/yam/migration/setup_upgrade_env.pm
Labels: qe-yam

#22454 Use Server Applications module for dovecot
  tests/network/config_services.pm
  tests/x11/evolution/evolution_prepare_servers.pm
Labels: Ready, qe-core

#22467 kselftests: Add timeout option
  tests/kernel/run_kselftests.pm
Labels: qe-kernel

#22472 Remove unused jsonnet file
  data/yam/agama/auto/lvm_encrypted_ppc64le.jsonnet
Labels: qe-yam

#22481 Save/restore SCC_URL during migration test
  tests/yam/migration/restore_upgrade_env.pm
  tests/yam/migration/setup_upgrade_env.pm
Labels: qe-yam

#22482 Removed version from addons jsonnet library
  data/yam/agama/auto/lib/addons.libsonnet
Labels: qe-yam

#22486 Read AGAMA_VERSION to detect which version of Agama is running
  schedule/yam/agama.yaml
  schedule/yam/agama_autoyast_supported_s390x.yaml
  schedule/yam/agama_autoyast_unsupported.yaml
  schedule/yam/agama_check_installation_medium.yaml
  schedule/yam/agama_desktop.yaml
  schedule/yam/agama_dud.yaml
  schedule/yam/agama_extended.yaml
  schedule/yam/agama_extensions_and_patterns.yaml
  schedule/yam/agama_extensions_and_patterns_ppc64le.yaml
  schedule/yam/agama_extensions_and_patterns_s390x.yaml
  schedule/yam/agama_from_usb.yaml
  schedule/yam/agama_full_disk_encryption.yaml
  schedule/yam/agama_full_disk_encryption_ppc64le.yaml
  schedule/yam/agama_full_disk_encryption_s390x.yaml
  schedule/yam/agama_gnome.yaml
  schedule/yam/agama_gnome_ppc64le.yaml
  schedule/yam/agama_gnome_s390x.yaml
  schedule/yam/agama_headless.yaml
  schedule/yam/agama_headless_pvm.yaml
  schedule/yam/agama_headless_s390x.yaml
  schedule/yam/agama_lvm.yaml
  schedule/yam/agama_lvm_encrypted.yaml
  schedule/yam/agama_lvm_encrypted_s390x.yaml
  schedule/yam/agama_lvm_s390x.yaml
  schedule/yam/agama_non_default_root_filesystem.yaml
  schedule/yam/agama_non_default_root_filesystem_ppc64le.yaml
  schedule/yam/agama_non_default_root_filesystem_s390x.yaml
  schedule/yam/agama_post_registration_ppc64le.yaml
  schedule/yam/agama_post_registration_s390x.yaml
  schedule/yam/agama_ppc64le.yaml
  schedule/yam/agama_remote_pvm.yaml
  schedule/yam/agama_remote_s390x.yaml
  schedule/yam/agama_s390x.yaml
  schedule/yam/agama_software_patterns.yaml
  schedule/yam/agama_software_patterns_s390x.yaml
  tests/yam/agama/agama_arrange.pm
Labels: qe-yam

#22497 Fix 'lshw' test issue on s390x
  tests/console/lshw.pm
Labels: qe-core
