Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-10, with the labels that each got.

#23471 Merge FIPS tests for ENV and KERN mode on SLE16 pvm_hmc
  schedule/security/fips/sle16/fips_env_mode_powervm.yaml
  schedule/security/fips/sle16/fips_sle16_powervm_hmc.yaml
Labels: qe-security

#23483 update_install: Fix issues and add new code
  tests/qam-updinstall/SLFO_update_install.pm
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#23500 update_install: Check patch log if patch has been already installed
  tests/qam-updinstall/update_install.pm
Labels: qe-core

#23502 Update installtest SLE 15 ay profile
  data/autoyast_qam/15_installtest.xml.ep
Labels: qe-core

#23546 Make sure test user has permission to access serial console
  tests/console/libgcrypt.pm
Labels: qe-security
