Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-08, with the labels that each got.

#22838 rabbitmq: Enable on SLE16 & update
  schedule/functional/sle16/extra_tests_textmode2.yaml
  schedule/functional/stack_tests_python.yaml
  schedule/qam/common/mau-extratests1.yaml
  tests/console/rabbitmq.pm
Labels: Ready, qe-core

#22859 Shutdown PVM setup when test completes
  schedule/functional/sle16/agama-create-hdd-textmode_pvm.yaml
Labels: qe-core

#22813 Ensure creation of the "after install" snapshot was removed
  schedule/yam/agama.yaml
  schedule/yam/agama_unattended.yaml
  tests/yam/validate/validate_snapshot.pm
Labels: qe-yam

#22870 Blktests trtypes
  data/kernel/post_process
  tests/kernel/blktests.pm
Labels: qe-kernel

#22620 Add more validations for the output of /etc/os-release
  schedule/yam/agama.yaml
  schedule/yam/agama_from_usb.yaml
  schedule/yam/agama_ppc64le.yaml
  schedule/yam/agama_remote_s390x.yaml
  schedule/yam/agama_s390x.yaml
  schedule/yam/agama_unattended.yaml
  test_data/yam/agama_sap.yaml
  test_data/yam/agama_sle.yaml
  tests/console/validate_repos.pm
  tests/yam/validate/validate_product.pm
Labels: qe-yam

#22888 Remove not needed including
  lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
Labels: qe-yam

#22890 Limit qemu-linux-user package to SLES 16.0 & Tumbleweed.
  tests/containers/bats/README.md
  tests/containers/bats/buildah.pm
  tests/containers/bats/runc.pm
Labels: urgent

#22892 Test tomcat on sle16
  lib/Tomcat/ApacheProxyTest.pm
  tests/x11/tomcat.pm
Labels: Ready, qe-core

#22899 containers: Skip rootless_docker on public cloud
  lib/main_containers.pm
Labels: urgent

#22920 LTP: Log network with ss
  lib/LTP/utils.pm
Labels: qe-kernel

#22903 Workaround: LTSS to LTSS migration bug bsc#1241014
  tests/migration/online_migration/zypper_migration.pm
Labels: bug, enhancement, qe-sap-ha

#22914 Add s390x schedule file for sle16 MU job
  schedule/qam/16/create_hdd_textmode_increment_s390x.yaml
  schedule/qam/16/create_hdd_textmode_staging_s390x.yaml
Labels: qe-core

#22937 Bump timeout for check_screen on Agama aarch64 bootup
  lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
Labels: qe-yam

#22975 bats/aardvark: Use netcat-openbsd for SLES < 16
  tests/containers/bats/aardvark.pm
Labels: urgent

#22978 Ensure creation of the "after install" snapshot was removed
  schedule/yam/agama.yaml
  schedule/yam/agama_unattended.yaml
  tests/yam/validate/validate_snapshots.pm
Labels: qe-yam

#23031 Ensure console selection after boot process in power kvm
  lib/susedistribution.pm
Labels: qe-yam

#23034 Add SLFO_update_install
  schedule/qam/16/create-ibs-hdd-textmode.yaml
  schedule/qam/common/qam-incidentinstall.yaml
  tests/console/setup_ibs_repos.pm
  tests/qam-updinstall/SLFO_update_install.pm
Labels: Ready, qe-core

#23046 Add systemd regression test for more sle versions
  schedule/qam/common/mau-systemd-bsc_1241079.yaml
Labels: qe-core

#23051 Revert prepare_test_data for ppc64le
  tests/console/validate_raid.pm
Labels: qe-yam

#23047 Adapt for 'boot from disk' on ppc64le development
  lib/Distribution/Opensuse/AgamaDevel.pm
  lib/Distribution/Opensuse/Leap/16Latest.pm
  lib/Distribution/Sle/16Latest.pm
  lib/Distribution/Sle/AgamaDevel.pm
Labels: qe-yam

#23053 Adapt validate_raid for SLES16 ppc64le
  tests/console/validate_raid.pm
Labels: qe-yam

#23015 Add validate_connectivity to lvm scenario
  schedule/yam/agama_lvm.yaml
  schedule/yam/agama_lvm_unattended.yaml
  tests/yam/validate/validate_connectivity.pm
Labels: qe-yam

#23082 Add missed including for is_ppc64le
  lib/Distribution/Opensuse/Leap/16Latest.pm
  lib/Distribution/Sle/16Latest.pm
Labels: qe-yam

#23066 Ensure console selection after boot process in power kvm
  lib/susedistribution.pm
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#23084 Don't define reg_url if SCC is used for Agama install
  tests/installation/ipxe_install.pm
Labels: qe-core

#22987 Add test for alert informing the user that Agama could not fetch profile
  lib/Yam/Agama/Pom/AgamaUpAndRunningPage.pm
  tests/yam/agama/agama.pm
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#23083 Adapt install entry old behavior on Leap
  lib/Distribution/Opensuse/Leap/16Latest.pm
Labels: qe-yam

#23096 containers/podman-py: python3-podman is not available on SLES
  lib/main_containers.pm
Labels: urgent

#23036 Test if registrationURL in profile is prefered over kernel parameter
  tests/yam/validate/validate_suseconnect_url.pm
Labels: qe-yam

#23119 Quick fix for greedy regex in validate_suseconnect_url
  tests/yam/validate/validate_suseconnect_url.pm
Labels: qe-yam

#23117 Update test code about validate_packages_and_patterns for sle16
  tests/console/validate_packages_and_patterns.pm
Labels: qe-core

#23132 Update the test data of repos for medium installation testsuites
  test_data/yam/agama_sap_media.yaml
  test_data/yam/agama_sle_media.yaml
Labels: qe-yam

#23133 containers: Skip docker-py tests on public cloud
  lib/main_containers.pm
Labels: urgent

#23081 Add addition and removal of patterns in unatttended installation
  data/yam/agama/auto/lib/software.libsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/agama_software_selection_unattended.yaml
  schedule/yam/agama_software_selection_unattended_s390x.yaml
Labels: qe-yam

#23141 Pc check ip change
  lib/publiccloud/instance.pm
  lib/sles4sap_publiccloud.pm
  tests/publiccloud/bsc_1205002.pm
  tests/sles4sap/publiccloud/azure_fence_agents_test.pm
  tests/sles4sap/publiccloud/qesap_prevalidate.pm
  tests/sles4sap/publiccloud/qesap_terraform.pm
  tests/sles4sap/sap_deployment_automation_framework/setup_publiccloud_instances.pm
Labels: Verification-Runs-needed

#23071 Avoid set inst.register_url for scc.suse.com on AGAMA test
  lib/registration.pm
Labels: qe-yam

#23152 Quickfix for boot_agama on Leap 16
  lib/Distribution/Opensuse/Leap/16Latest.pm
Labels: qe-yam

#23150 Update the grub of migration menu match for sle16 migration
  tests/yam/migration/migration_unattended.pm
Labels: qe-yam
