Repository os-autoinst/os-autoinst-distri-opensuse, pull requests merged in 2025-07, with the labels that each got.

#22338 klp: Add SLE 16 support
  lib/klp.pm
Labels: qe-kernel

#22536 bats/buildah: Fix BATS_SKIP for 15-SP4
  data/containers/bats/skip.yaml
Labels: urgent

#22546 Increase timeout for redis test
  tests/console/redis.pm
Labels: qe-core

#22549 Add Franta to qe-sec codeowners
  .github/CODEOWNERS
Labels: qe-security

#22448 Move s390x zVM setting inside bootloader code
  lib/bootloader_setup.pm
  tests/installation/bootloader_s390.pm
Labels: qe-yam

#22554 Adapt zypper lifecycle check logic on sle16
  tests/console/zypper_lifecycle.pm
Labels: qe-core

#22560 Changed IBFT validation for SLE16
  tests/installation/validation/ibft.pm
Labels: qe-yam

#22567 Schedule tests for sle16 maintenance staging
  lib/qam.pm
  schedule/qam/16/create_hdd_textmode_staging.yaml
  tests/qam-minimal/install_update.pm
Labels: qe-core

#22579 Schedule sle16 MU increment tests
  schedule/qam/16/create_hdd_textmode_increment.yaml
Labels: qe-core

#22591 Revert "containers: No need to disable SUSE secrets anymore"
  tests/containers/rootless_docker.pm
Labels: urgent

#22589 bats/buildah: Avoid SELinux hack on /tmp
  lib/containers/bats.pm
Labels: urgent

#22594 Test systemd timers: check elapsed time
  tests/yam/validate/validate_systemd_timers.pm
Labels: qe-yam

#22545 Add custom repositories for unattended installation
  data/yam/agama/auto/lib/software.libsonnet
  data/yam/agama/auto/template.libsonnet
  schedule/yam/agama_extended_unattended.yaml
  schedule/yam/agama_extended_unattended_ppc64le.yaml
  schedule/yam/agama_extended_unattended_s390x.yaml
  test_data/yam/agama_sle_extended.yaml
Labels: qe-yam

#22409 Fix tests and schedules for InfiniBand tests on sle16
  schedule/kernel/agama_ibtest-master.yaml
  schedule/kernel/agama_ibtest-slave.yaml
  tests/kernel/ibtests.pm
  tests/kernel/ibtests_prepare.pm
Labels: qe-kernel

#22622 Implement check for specific USB devices on SUT
  lib/usb.pm
  tests/kernel/usb_drive.pm
  tests/kernel/usb_nic.pm
Labels: qe-kernel

#22414 Automate rescue system
  lib/Yam/Agama/Pom/GrubMenuAgamaPage.pm
  schedule/yam/agama_check_rescue_system.yaml
  test_data/yam/agama_rescue_system.yaml
  tests/yam/agama/boot_agama.pm
  tests/yam/validate/validate_rescue_system.pm
Labels: qe-yam

#22479 Move test from 'ppc-emu' workers to power10 kvm workers
  lib/main_micro_alp.pm
Labels: Ready, qe-core

#22638 Add jobs for SLE16 Maintenance
  products/sle/main.pm
  schedule/qam/16/mau-extra-tests.yaml
  schedule/qam/16/mau-webserver.yaml
Labels: qe-core

#22660 update_install: Add docker*zsh-completion conflict
  tests/qam-updinstall/update_install.pm
Labels: Ready, qe-core

#22667 xfstests: Update xfstests scheduler for SL Micro
  schedule/filesystem/xfstests_micro_ppc.yaml
  tests/xfstests/partition.pm
Labels: qe-kernel

#22668 sudo: Replace zypper/yast2 with visudo
  tests/console/sudo.pm
Labels: Ready, qe-core

#22670 blktests: Block section requires longer timeout
  tests/kernel/blktests.pm
Labels: qe-kernel

#22646 Automate further sorting in search
  data/yam/agama/auto/lib/storage.libsonnet
  test_data/yam/whole_disk_and_boot_unattended.yaml
Labels: qe-yam

#22659 Automate selection of option to prevent copying network
  schedule/yam/agama.yaml
  schedule/yam/agama_non_default_root_filesystem.yaml
  schedule/yam/agama_unattended.yaml
  tests/yam/validate/validate_connectivity.pm
Labels: qe-yam

#22680 bats/buildah: Update BATS_SKIP
  data/containers/bats/skip.yaml
Labels: urgent

#22681 bats/podman: Add missing is_sle import
  tests/containers/bats/podman.pm
Labels: urgent

#22682 Add test data for iscsi_activation_non_root
  schedule/yam/agama_iscsi_activate_unattended.yaml
  test_data/yam/iscsi_activation_non_root.yaml
Labels: qe-yam

#22687 Remove unused schedule after moved jobs to qemu kvm
  schedule/yam/agama_autoyast_supported_ppc64le.yaml
  schedule/yam/agama_extensions_and_patterns_ppc64le.yaml
  schedule/yam/agama_full_disk_encryption_ppc64le.yaml
  schedule/yam/agama_gnome_ppc64le.yaml
  schedule/yam/agama_gnome_unattended_ppc64le.yaml
  schedule/yam/agama_headless_pvm.yaml
  schedule/yam/agama_non_default_root_filesystem_ppc64le.yaml
  schedule/yam/agama_remote_pvm.yaml
Labels: qe-yam

#22693 Fix: add check to re-check the connectivity and unknow as output
  tests/yam/validate/validate_connectivity.pm
Labels: qe-yam

#22694 containers: Remove fedora image from 3rd party-images
  lib/containers/urls.pm
Labels: urgent

#22688 cron mta: Run systemctl is active with script_retry
  schedule/qam/common/mau-extratests1.yaml
  tests/console/cron.pm
  tests/console/mta.pm
Labels: Ready, qe-core

#22692 Add TLS support for valkey test
  data/valkey/replica.conf
  data/valkey/valkey.conf
  schedule/functional/sle16/extra_tests_textmode2.yaml
  tests/console/valkey.pm
Labels: qe-core

#22707 bats: Increase timeout when installing packages
  lib/containers/bats.pm
Labels: urgent

#22712 zypper_in: Don't schedule broken opensuse_repos on maintenance
  lib/main_common.pm
Labels: Ready, qe-core

#22732 Fix for problems in sles_whole_disk_boot_unattended on aarch64
  test_data/yam/whole_disk_and_boot_unattended_aarch64.yaml
Labels: qe-yam

#22745 Fix the regular expression problem for libgit2
  tests/console/libgit2.pm
Labels: qe-core

#22701 kselftests: Use KTAP parser
  tests/kernel/run_kselftests.pm
Labels: qe-kernel

#22751 containers: Tweak curl retry options to give containers time to start
  lib/containers/container_images.pm
Labels: urgent

#22766 containers: Avoid --retry-all-errors on SLEM < 5.3
  lib/containers/container_images.pm
Labels: urgent

#22775 Adapt to new behaviour of hpc-testing
  tests/kernel/ibtests.pm
Labels: qe-kernel

#22776 Update agama security install schedule
  schedule/security/sle16/agama.yaml
Labels: qe-security

#22782 Fix: add "sle-micro: 6.2" in bug_ref for dracut-no-logger
  data/journal_check/bug_refs.json
Labels: qe-yam

#22786 containers: Drop curl --retry-all-errors option
  lib/containers/container_images.pm
  tests/containers/registry.pm
Labels: urgent

#22787 containers: Increase number of curl retries
  lib/containers/container_images.pm
  tests/containers/registry.pm
Labels: urgent

#22768 Test alert informing the user that Agama could not fetch the profile
  schedule/yam/agama_alert_popup.yaml
  tests/yam/agama/agama.pm
  tests/yam/agama/boot_agama.pm
Labels: qe-yam

#22697 xfstests: Add new test for NFS over kTLS
  tests/xfstests/partition.pm
Labels: qe-kernel

#22783 Schedule valkey test on sle15sp6 and sle15sp7
  schedule/qam/common/mau-extratests2.yaml
  tests/console/valkey.pm
Labels: Ready, qe-core

#22788 containers: Increase curl --retry for FIPS tests
  lib/containers/container_images.pm
  tests/containers/registry.pm
Labels: urgent

#22781 io_uring: Print the last commit
  tests/kernel/io_uring.pm
Labels: qe-kernel

#22793 containers: Fix registry test
  tests/containers/registry.pm
Labels: urgent

#22799 containers: Use whole utils module
  tests/containers/firewall.pm
Labels: urgent

#22806 Test pcre2 on sle16
  data/pcre/pcre-test.cpp
  data/pcre/pcre2-test.cpp
  tests/console/php_pcre.pm
Labels: qe-core

#22812 Kselftests: Improvements for -t native flag as well as known_issues
  tests/kernel/run_kselftests.pm
Labels: qe-kernel

#22610 kernel: Improve baremetal maintenance testing over IPXE
  lib/main_common.pm
  tests/kernel/update_kernel.pm
Labels: qe-kernel

#22820 Play audio file if it is not played automatically
  tests/x11/firefox_audio.pm
Labels: Ready, qe-core
